### ISSUE TITLE
Potentially incorrect Getting Started documentation for Docker

### ISSUE THREAD

**Issue by krsnaa** [allenai/allennlp#1027]
The doc recommends docker as the fastest way to get started and says that:

`$ docker run -p 8000:8000 -it --rm allennlp/allennlp`

will download the latest allennlp image, start a Docker container, and launch an interactive shell. It also exposes port 8000, which is where the demo server runs, and shuts down the container when you exit the interactive shell.

However, all it did was to bring me to a root prompt and when attempting to execute the allennlp command, it is unavailable. 
`bash: allennlp: command not found`  

After a little looking around, I figured that I had to execute `python -m allennlp.run` to get anything to happen.

Am I missing/overlooking something?

**Comment by krsnaa** [comment]
ah, just saw that the 0.4.0 branch does indicate the proper initialization sequence:
`$ python -m allennlp.run`

So, this misleading usage is only in the 0.4.1 and master branch:
`usage: allennlp [command]`

**Comment by schmmd** [comment]
Thanks @krsnaa!  This is an error due to a recent change.

I updated the documentation but I'm leaving this open to see whether we have an option to get `allennlp` to work as a command when it's not installed via pip.

**Comment by matt-gardner** [comment]
Maybe running we could install from the git repo using pip inside the docker image?  Or it could be as simple as `RUN alias allennlp='python -m allennlp.run'`.

**Comment by schmmd** [comment]
@matt-gardner running the pip install inside the docker image makes it unusable for CI.  We could have multiple Docker images for multiple use cases, but I'd rather avoid that until necessary.

Another way to be able to run AllenNLP via `python setup.py install` (or something similar)--but then `allennlp` and `python -m allennlp.run` run different code if the source changes.

**Comment by matt-gardner** [comment]
By "using pip inside the docker image", I meant something like `pip install git+git://github.com/allenai/allennlp@3c761ba9d857677efb60ae5c2dbbe321f0b3b702`, but pointing to the copy of the code in the docker image, which is essentially the same as running `python setup.py install`.  Because it's in the docker image, we probably don't need to worry about code changing.  The alias is probably the best option, except that it would only work in the base directory of the repo, so maybe adding something to `PYTHONPATH` would also be necessary.

**Comment by schmmd** [comment]
I don't think we should `pip install git+git://github.com/allenai/allennlp@3c761ba9d857677efb60ae5c2dbbe321f0b3b702` since then you cannot build a docker image for a SHA that isn't in GitHub.

One use case for the Docker image is doing local development in a consistent environment, so I think it's reasonable that the code could change.  I'd like to start doing this and Sam did this when he developed on AllenNLP.  In any case, I've certainly modified code in an AllenNLP Docker image before.

I agree the alias is probably the best option, but I'm not particularly inclined to make that change.  People still need to run `python -m allennlp.run` if they clone the repository.

**Comment by DeNeutoy** [comment]
I think it's perfectly fine to just point people to run `bin/allennlp` if they clone the repo.

**Comment by DeNeutoy** [comment]
addressed by #1034
