### ISSUE TITLE
Refactor Iterators to use less inheritance

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#1143]
The iterators are currently difficult to reason about, because they use a lot of inheritance (I did this originally). This was a bad idea and makes it difficult to think about.

**Comment by murphp15** [comment]
@DeNeutoy 
I assume this is in reference to Implementations of DataIterator? 
Is it that you would like to use composition over inheritance? 

So the change would consist of: 
1. WaitingIterator will have an instance of BasicIterator in it instead of extending it. 
2. BucketIterator will have an instance of BasicIterator in it instead of extending it. 
3. EpochTrackingBucketIterator will have an instance of BucketIterator in it instead of extending it. 

I would be happy to pick this issue up if they are the changes you are looking for.

**Comment by matt-gardner** [comment]
@joelgrus already started on this: https://github.com/allenai/allennlp/pull/1157.  I've been meaning to look over that PR and give suggestions, but we all have a paper deadline early next week, so this kind of work has been lower priority for us for a little bit (including reviewing your other PRs).

**Comment by murphp15** [comment]
@matt-gardner Thanks I will take a look at that 1157. 
Best of luck on the paper and don't worry about my PRs, I'm in no rush to get them merged, I just want to get comfortable with your codebase.

**Comment by joelgrus** [comment]
fixed by #1157
