### ISSUE TITLE
Is there a way to automatically pad <start>, <end> token?

### ISSUE THREAD

**Issue by taineleau** [allenai/allennlp#1152]
Hi,
Just switched from Torchtext to allennlp. Is there a way to automatically pad `<start>`, `<end>` token for a sentence?

**Comment by matt-gardner** [comment]
Yes, there is.  If you pass the `start_tokens` and `end_tokens` flags to the `WordTokenizer`, we'll automatically add whatever (string) tokens you want:
https://github.com/allenai/allennlp/blob/55b0411bea8ae241332aa6c96cc9b4cf189afe20/allennlp/data/tokenizers/word_tokenizer.py#L34-L37

You can see how this is done in our BiDAF configuration here:
https://github.com/allenai/allennlp/blob/55b0411bea8ae241332aa6c96cc9b4cf189afe20/training_config/bidaf.json#L13-L14
though note that this uses integers instead of strings, because we're using byte encoding for characters.

Depending on exactly what you're trying to do, though, this may or may not be what you want to do.  For language modeling or seq2seq models, for instance, you might want to handle things differently, because these tokens actually have special meaning during decoding.

**Comment by taineleau** [comment]
Thanks for the quick reply! After looking at the code you pointed out, I found myself reinventing the wheel lol.
