### ISSUE TITLE
character embedding

### ISSUE THREAD

**Issue by rashikaanand** [allenai/allennlp#1236]
Hi, my question is that lets consider that "queen" and "princess" are not present in the vocabulary, then will their character embedding give a good similarity between the two words?

**Comment by matt-gardner** [comment]
You could in principle learn a network to predict a glove embedding (or similar) from the characters themselves.  I thought someone had tried this, but I can't find the reference at the moment.  The closest I can find is [this one](https://www.semanticscholar.org/paper/Learning-to-Compute-Word-Embeddings-On-the-Fly-Bahdanau-Bosc/528c397b0e523c9a257d67bb05409b83b4cdd33d?tab=abstract), but it's not a character-level model.

So, I think the answer to your question is a "maybe", and I think this is still a research problem (though, again, I thought there was a paper that did this recently, I just can't find it with a quick search).

**Comment by rashikaanand** [comment]
Let's say if two words are present in Glove and we are also finding their character embedding, then if we use both word and character embedding for the words, then will it not reduce their similarity?

**Comment by rashikaanand** [comment]
Lets assume that the words are "queen " and "princess" and lets say they are OOV, then in allenNLP we are using CNN to calculate character embedding for these two words. My question is that will these two character embedding vectors have a high cosine similarity ?

**Comment by rashikaanand** [comment]
Hi, I compared the cosine similarity of the word embedding, character embedding, word+character embedding for the words "pretty" and "beautiful" from AllenNLP's code and see have a question. 
Word embedding cosine similarity of these two words is : 0.67, character embedding cosine similarity is : 0.20 ,  word  + character embedding cosine similarity is : 0.57.

Does this mean concatenating character embedding to word embedding and using the concatenated vector for similarity will give lower similarity compared to using just the word embeddings alone?

**Comment by nelson-liu** [comment]
hi,
The task you train your character level embeddings on is likely to have a large effect. if your goal is to simply get a good measure of similarity over both OOV and non-OOV words, I'd recommend two strategies:

(1). Train a model to explicitly mimick pretrained vectors. See [this paper from EMNLP 2017 for more details](https://www.semanticscholar.org/paper/Mimicking-Word-Embeddings-using-Subword-RNNs-Pinter-Guthrie/392c648741ae66c3f9189c54ddd31de3b31ba18f), I think this is the one @matt-gardner  was looking for earlier.

(2). Use something that was specifically built with this in mind. For example, [FastText](https://github.com/facebookresearch/fastText) builds its word vectors from subword units. See [this example in their docs](https://fasttext.cc/docs/en/unsupervised-tutorial.html#advanced-reader-measure-of-similarity)

It's not clear the allennlp character level embedding you train will be better than these two alternatives, since the former explicitly uses your goal (mimicking word vectors) as its objective and the latter is trained on massive monolingual corpora.
