### ISSUE TITLE
Split out the demo from allenai/allennlp

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1328]
Now that the demo is getting larger and the library is getting more mature, I think it's time to split the demo out from allenai/allennlp.  This will have the added benefit of shrinking our Docker distribution and reducing our build times.  We can depend on `allennlp` via a pip dependency and build a Docker image similar to https://github.com/allenai/allennlp/issues/1324.

We would need to add a build step for the demo repository and update allenai/allennlp-internal to use the new demo Docker images.

**Comment by schmmd** [comment]
Joel might start on this next week.

**Comment by joelgrus** [comment]
so I made some good progress on this:

* I have a standalone repo / Dockerfile that pip installs allennlp and builds a servable image: 

https://github.com/allenai/allennlp-demo

* I have a WIP PR that removes the demo from the main repo:

https://github.com/allenai/allennlp/pull/1338

It's pretty much done, but it's called WIP because merging it would break all of our deployment stuff.

--

I took a brief look at TeamCity and what it would take to migrate our demo deployments to the new setup, and I think it's the sort of thing where I could waste a lot of time not getting it right, so I'll probably leave the project where it is until @schmmd gets back in the office and work with him to finish that part.

**Comment by DeNeutoy** [comment]
Fixed by #1338
