### ISSUE TITLE
Warning from the function predict_json

### ISSUE THREAD

**Issue by csyhuang** [allenai/allennlp#1346]
Hi,

When using the `predict_json` method as shown below,

```
from allennlp.models.archival import load_archive
from allennlp.service.predictors import Predictor

archive = load_archive("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz")
allen_nlp_predictor = Predictor.from_archive(archive, 'constituency-parser')
results = allen_nlp_predictor.predict_json({"sentence": question})
```

I see a warning like this:
```
WARNING:allennlp.data.fields.sequence_label_field:Your label namespace was 'pos'. We recommend you use a namespace ending with 'labels' or 'tags', so we don't add UNK and PAD tokens by default to your vocabulary
```

How shall I get around this? Where can I change the label namespace?

Thanks,

Clare

**Comment by matt-gardner** [comment]
You can safely ignore that warning - it's potentially an issue at training time, and we give that warning to make sure you know what you're doing as far as including padding / OOV tokens or not when computing vocabularies.  But for an already-trained model that you're just making predictions with, you don't need to worry about it.

@DeNeutoy, why use `pos` instead of `pos_tags` for the namespace when training the model?  Are you imagining having OOV pos tags?  Or you wanted a padding token?

**Comment by DeNeutoy** [comment]
Partly historic, partly needing a padding token. Yep basically you can just ignore it.
