### ISSUE TITLE
Help with debugging potential memory leak in bidaf code on GPU

### ISSUE THREAD

**Issue by aman313** [allenai/allennlp#1360]
Hi folks,

There seems to be a memory leak in the bidaf code when using GPU for training. The memory footprint keeps rising in a pattern that I have not yet been able to decipher. I have checked that this is not a data issue as the number of tokens in all passages have been limited by a max value(~800).  
I have not been able to reproduce this while training on the CPU. Unfortunately, I am not quite sure how to pinpoint the reason for this increase in memory usage. Any suggestions about how to go about it or any tools I should use will be extremely helpful.

Cheers,
Aman

**Comment by DeNeutoy** [comment]
Hi there,

1. Have you made any modifications to the allennlp code or are you training the model in the repo?
2. How much memory does your GPU have?
3. If you have changed anything in the config, please post the whole config below.

It is expected that GPU memory use increases initially during training, because you might not start out with a batch of sentences that has the max length in the dataset. However, training should complete if you don't go OOM before this.

**Comment by matt-gardner** [comment]
Wasn't there also a driver issue that you found a while ago, @DeNeutoy?  Could that be related?

**Comment by aman313** [comment]
@DeNeutoy Thanks for the quick response and apologies for lack of details in the question.

1. I was using the allenlp code on a different dataset. The only code that I added was a different dataset reader. I tried replicating the same issue with the squad data today but was unable to do so. This suggests the issue might be due the data generator code. I am digging into it but prima facie, I am not sure why that would cause an issue as all the code does is yield instances and does not interface with the GPU memory directly.  
2. I am running the code on aws p2.xlarge instance with 12GB gpu memory. 
3. There are a few config changes I made but they were primarily to reduce the network and batch sizes. Pasting the config below. 
4. Actually I am not sure if memory leak is the correct way to characterize the problem I am facing. The code seems to run fine for hundreds of iterations before crapping out and the increase seems to be step like rather than gradual. I have started another run with logging the gpu memory usage after each iteration. Hopefully that would yield some clues if OOM strikes.

@matt-gardner : In case this is relevant, I am using cuda 9.2 with latest cudnn. driver version 396.26.

This might be a false alarm folks. Will post an update if I figure out what the issue is.
config:
[network_tiny.txt](https://github.com/allenai/allennlp/files/2098226/network_tiny.txt)

**Comment by DeNeutoy** [comment]
Ok - if you have changed the dataset reader, I would suggest that you try the `allennlp dry-run` command, which will print out statistics about your dataset and show you a few instances. This is a good thing to check, because GPU memory is definitely a function of your dataset. As an example (this actually happened to us for TriviaQA), if you have a thai word which somehow get's parsed as being 500+ characters long, the batch that it's in will have all its characters padded to 500 length, which is too large. Does that make sense?

**Comment by aman313** [comment]
Thanks a lot for that pointer. Turns out that was the precise issue I was facing. The long tokens were a result of faulty ocr and some encoding issue.
