### ISSUE TITLE
ListField of SequenceFields throws AssertionError: ListFields must contain a single field type, found set()

### ISSUE THREAD

**Issue by aribornstein** [allenai/allennlp#1391]
**Describe the bug**
Creating a list field of sequence fields in my data encoder throws an assertion error.

AssertionError: ListFields must contain a single field type, found set()

**To Reproduce**
```python
srl_tags: List[Field] = []
for frame, tags in srl.items():
            srl_tags.append(SequenceLabelField(tags, premise_field, label_namespace="SRL_tags" ))
        
        srl_tags_field: ListField = ListField(srl_tags)
        fields['srl_tags']=srl_tags_field
```

**Expected behavior**
Expect no exception since the list field is all of the same type

**System (please complete the following information):**
 - OS: g. Ubuntu)
 - Python version:3.6
 - AllenNLP version: [ "I installed from master"]

**Additional context**

**Comment by joelgrus** [comment]
The `found set()` message indicates that the ListField is empty (i.e. your `srl_tags` list is empty). I agree that the error message is not helpful here. (I'm undecided on whether this should be an error or not)

is it intentional that your `srl_tags` is empty?

**Comment by HarshTrivedi** [comment]
I faced this exception a couple of days back. It was because one of the times ListField was instantiated with empty list `[]`. I believe you are having a similar problem. In the loop, one of the times `srl_tags` is actually an empty list. When the list is non-empty, all of them are of same type though. Can you check if this is true? If so, I can help to fix it.

`ListField([])` (instantiation with empty list) does not work since the list field must know what type of field it is containing. This information is essential for batching and padding. Hence, instead of calling `my_list_field = ListField([])`, following should be used: `my_list_field =  stub_list_field.empty_field()`.  You can check usage of `empty_field` in `list_field_test.py`

**Comment by HarshTrivedi** [comment]
Can you paste your updated code? All the field names and field types should be same for all instances that are to be batched together. I believe that the instance which had an empty `ListField` is causing problem. This could potentially happen if your stub list is not of the same type as it should be.

**Comment by aribornstein** [comment]
I can paste a snippet

```python

        if (len(srl_tags)>0):
            fields['srl_tags'] = ListField(srl_tags)
        else:
        # in my actual code dummyseq is a populated SequenceLabelField 
            fields[''srl_tags'] = dummyseq.empty_field()

```

**Comment by HarshTrivedi** [comment]
Are you sure the `dummyseq` is a `ListField` of the same type that of `srl_tags`?

**Comment by aribornstein** [comment]
yes it's a ```SequenceLabelField```

**Comment by DeNeutoy** [comment]
@aribornstein I think you want:
```
        if (len(srl_tags)>0):
            fields['srl_tags'] = ListField(srl_tags)
        else:
        # in my actual code dummyseq is a populated SequenceLabelField 
            fields[''srl_tags'] = ListField(dummyseq.empty_field())
```

As Harsh was saying, keys in an instance have to have the same type, so we can batch them together. 

Additionally, you may wish to look at this in a slightly different way. If i've inferred correctly that you are trying to predict all frames for all verbs at the same time, and that you are using a BIO encoding for each verb's frame, you might want to consider using a sequence labelling of all "O" for verbs which have no frame, rather than not using one at all. You can see a concrete example of this here: https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/semantic_role_labeling.py#L66

**Comment by aribornstein** [comment]
Yes that worked!! Thank you all might have a few more questions a little later but this is amazing progress thank you!

**Comment by Statham-stone** [comment]
This code works, thank you very much.

**Comment by Statham-stone** [comment]
The ListField __init__() methos should add a parameter to specify field when the list is empty.
