### ISSUE TITLE
Dimension size not match for "Textual Entailment"

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#1466]
I tried to run Textual Entailment, with a little label field modification which is limiting to a set of ('positive', 'negative') only. However the label vocabulary turns out to be {0: '@@PADDING@@', 1: '@@UNKNOWN@@', 2: 'positive', 3: 'negative'}. Finally it leads to an assertion failed error.
Here is the line where program broke.

`check_dimensions_match(aggregate_feedforward.get_output_dim(), self._num_labels,
                               "final output dimension", "number of labels")`
Is there a way to avoid this? Following are trace stack.
Traceback (most recent call last):
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/commands/train.py", line 276, in train_model
    model = Model.from_params(vocab, params.pop('model'))
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/models/model.py", line 217, in from_params
    model = cls.by_name(choice).from_params(vocab, params)
  File "/Users/GitProjects/allennlp-as-a-library-example/my_library/models/decomposable_attention.py", line 218, in from_params
    regularizer=regularizer)
  File "/Users/GitProjects/allennlp-as-a-library-example/my_library/models/decomposable_attention.py", line 89, in __init__
    "final output dimension", "number of labels")
  File "/Users/anaconda3/envs/pytorch0.4/lib/python3.6/site-packages/allennlp/common/checks.py", line 37, in check_dimensions_match
    raise ConfigurationError(f"{dim_1_name} must match {dim_2_name}, but got {dimension_1} "
allennlp.common.checks.ConfigurationError: 'final output dimension must match number of labels, but got 3 and 4 instead'
**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [if it's not 3.6, that's probably your problem]
 - AllenNLP version: [e.g. v0.5.1, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Additional context**

**Comment by HarshTrivedi** [comment]
2 Reasons:
1. You Label Vocabulary should be {0 'positive', 1: 'negative'}
It seems that you have also changed the namespace of vocabulary for label field. By default, if you keep you namespace anything ending with tag or label, then it will not add any @@PADDING@@ and @@UNKNOWN@@ token to that namespace. If you choose to use something else, then you must explicitly say that it is non_padded in your experiment.json
```
  "vocabulary": {
    "non_padded_namespaces": ["my_namespace"]
  },
```
You probably set this namespace in your datasetreader: 
```
fields['my_namespace'] = LabelField(label)
```
If you used the provided snli reader, it shouldn't be a problem since it uses `fields['label'] = LabelField(label)`

2. Your error says 'final output dimension must match number of labels, but got **3** and **4** instead'. After you fix above, it will expect 2. Your code is generating 3 logits probably because of you didn't change the final aggregation neural network. SNLI by default has 3 labels and so default is to generate 3 logits:

```
    "aggregate_feedforward": {
      "input_dim": 400,
      "num_layers": 2,
      "hidden_dims": [200, 3],        # Change 3 to number of classes you want to predict. 2 in your case.
      "activations": ["relu", "linear"],
      "dropout": [0.2, 0.0]
    },
```

**Comment by matt-gardner** [comment]
@HarshTrivedi, thanks for helping!  What you said is _almost_ right.  You conflated the field name and the field's namespace.  Instead of

```python
fields['ny_namespace'] = LabelField(label)
```

you want

```python
fields['my_field_name'] = LabelField(label, label_namespace='my_namespace')
```

Everything else you said looked right to me (oh, and default non-padded namespaces are things that end in "tags" or "labels", not "tag" or "label").

The field names that you use are arbitrary; you just have to make sure that wherever they are read in code that you're using matching field name names (and most often this is just in [the arguments to the `forward` method](https://github.com/allenai/allennlp/blob/77298a975a8edf8032723a140f4137a0fd326e61/allennlp/models/decomposable_attention.py#L97-L100)).

The _field name_ is just used for matching inputs in the dataset reader with inputs in your model code.  The _vocabulary namespace_ is used to create separate embedding matrices for separate _kinds_ of input.  You could have multiple fields that use the same vocabulary; e.g., if you have a `Field` for a question, and a `Field` for a paragraph, as in SQuAD, they should probably share the same vocabulary.  The _field names_ here would be `"question"` and `"paragraph"`, where the _vocabulary namespace_ for both would be something like `"tokens"`.

@robbine, I'm closing this for now.  If you have more questions, or if this didn't solve your problem, feel free to re-open.
