### ISSUE TITLE
Informative error message for empty strings

### ISSUE THREAD

**Issue by maartensap** [allenai/allennlp#1591]
I had a dataset reader that was reading from a CSV, one of my lines was just a bunch of "\n\n".
When the TextField containing the string calls `as_tensor()`, the `padding_length` are missing keys (upon debugging it seems the token attribute of the text field was an empty list).

(co written with Nelson Liu by my side)

**Comment by matt-gardner** [comment]
I'm a bit confused as to the issue here.  Can you give a full stack trace?  I'm not sure that the `TextField` can catch these errors, as we need to be able to handle padding, so we can't just check for empty token lists.  This looks like it's just something that has to be handled in your `DatasetReader`, but if you give a full stack trace, it'll be more clear whether there's anything we can do here.

**Comment by nelson-liu** [comment]
(I was helping Maarten debug this yesterday)

Stack trace:

‘’’
2018-08-07 10:27:09,803 - INFO - allennlp.training.trainer - GPU 1 memory usage MB: 2976
  0%|          | 0/30479 [00:00<?, ?it/s]2018-08-07 10:27:09,804 - INFO - allennlp.training.trainer - Training
accuracy: 0.8014, f1: 0.8783, loss: 0.4108 ||:  63%|######2   | 19128/30479 [18:08<10:46, 17.57it/s]Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/commands/train.py", line 296, in train_model
    metrics = trainer.train()
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/training/trainer.py", line 679, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/training/trainer.py", line 453, in _train_epoch
    for batch in train_generator_tqdm:
  File "/home/msap/venv36/lib/python3.6/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/data/iterators/data_iterator.py", line 54, in __call__
    yield from self._yield_one_epoch(instances, shuffle, cuda_device)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/data/iterators/data_iterator.py", line 73, in _yield_one_epoch
    cuda_device=cuda_device)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/data/dataset.py", line 140, in as_tensor_dict
    for field, tensors in instance.as_tensor_dict(lengths_to_use, cuda_device).items():
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/data/instance.py", line 77, in as_tensor_dict
    cuda_device=cuda_device)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/data/fields/text_field.py", line 110, in as_tensor
    desired_num_tokens, padding_lengths)
  File "/home/msap/venv36/lib/python3.6/site-packages/allennlp/data/token_indexers/token_characters_indexer.py", line 80, in pad_token_sequence
    desired_token_length = padding_lengths['num_token_characters']
KeyError: 'num_token_characters'
‘’’

The annoying thing about debugging this is that the failure happens completely within allennlp code —- the way we ended up solving it was to set a breakpoint in his allennlp install in ’text_field.py’ . 

Hopefully there’d be something we could do in allennlp about this, the error is pretty opaque otherwise.

**Comment by nelson-liu** [comment]
Also note that it wasn’t super obvious what the problem was because his dataset didn’t have any empty strings  —- the issue was strings with only white space. Somewhere in the pipeline, allennlp must have deleted the white space (maybe the tokenizer?) and then passed on the empty string. It might be worth raising a warning or something when this happens?

**Comment by matt-gardner** [comment]
Removing spaces happens here: https://github.com/allenai/allennlp/blob/152b590caab8732792689b85686788f2197b93c4/allennlp/data/tokenizers/word_splitter.py#L129-L153

You could imagine raising a warning if the returned list becomes empty, though that warning could be annoying if you're already handling this in your code (which I think is the right thing to do).

But for the original problem, you'd only get this error if _none_ of the instances in your batch had any tokens in it, right?  Because we already handle the case where there's some padding, and it's fine.  This is a problem because none of the `TextFields` had `num_token_characters`, so it doesn't show up in the `padding_lengths` that get passed to the `TokenIndexer`, and things crash.

Would it be enough to give a better error message than a `KeyError` here?  Basically, catch the `KeyError` and log a fatal error saying that you provided a batch that looks like it's all padding, and there's probably a data processing error in your code?

**Comment by schmmd** [comment]
We're blocked on addressing this until we have a minimal test case.  We can't remember who exactly promised us one. @nelson-liu ?

**Comment by nelson-liu** [comment]
Hmm I don't have code to reproduce this (I was helping maarten with it)? @alephic also ran into this a bit back, and I think we concluded that in his case the entire batch was indeed not empty (maybe I'm misremembering, could you remind me Kaj)?

**Comment by alephic** [comment]
Yes, I had this happen to me with a batch where a single instance had an empty textfield

**Comment by nihiluis** [comment]
I'm having the same issue. how do I check if i have empty textfields?

I do

 `t = list(filter(lambda x: "".join(x2.text_with_ws for x2 in x).isspace(), [x["phrase"].tokens for x in train_dataset]))`

or

`t = list(filter(lambda x: not "".join(x2.text_with_ws for x2 in x), [x["phrase"].tokens for x in train_dataset]))`

and both times the resulting lists are empty.  i checked the dataset as well and didnt find any empty inputs. is that how I can do it or do I have to do it differently (to check if my input is correct).

**Comment by matt-gardner** [comment]
We're still not sure what the underlying cause of the issue is, as we don't have a minimal failing test case.  If you want to help us diagnose it, the most helpful thing you can do is find the particular batch that it's failing on, and make it into a minimal test case.  You could do this by, e.g., putting a try/catch block in the training loop and printing out the batch when you run into this error, and then making a test of out it.
