### ISSUE TITLE
make `allennlp predict` work without a predictor (if you use a dataset reader)

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1675]
We now have a `--use-dataset-reader` flag.  It seems like this is pretty much always what someone would want to use if they are running things from the command line.  If you look at the code, using `--use-dataset-reader` means you go to `Predictor.predict_instances`, which has a default implementation in the base class (the only subclass implementations add stuff that's specific to the demo).  We don't need a `Predictor` at all to handle this use case.

#1674 implements a `Predictor` for the sole purpose of making JSON predictions with `allennlp predict`, but the code just re-implements dataset reader logic, and it would almost certainly be used with a `--use-dataset-reader` flag anyway.  So why do we require a `Predictor` for running `allennlp predict`?  It seems like we only really need it for demos.

**Comment by joelgrus** [comment]
I think the use case we originally imagined was something like "I want to run the pretrained NER model on my own sentences (which are e.g. not in the conll2003 format), or I want to play with some other model at the command line (e.g. all the "predict" examples at https://allennlp.org/models) but I agree that in many circumstances it's unnecessary.

**Comment by joelgrus** [comment]
part of the challenge is that logically there's not a 1:1 relationship between DatasetReaders and Models (even though in practice there might be), so like the trained NER model used the `conll2003` dataset reader, but if you have your own dataset you might want to use `sequence_tagging` instead.

it's possible you could have `predict` take a `--dataset-reader` input (instead of a `--use-dataset-reader`) and then shove JSON blobs into text_to_instance in the most natural way (in this case e.g. assuming pre-tokenized), but that would involve some amount of "magic"

**Comment by DeNeutoy** [comment]
This assumes that there is a 1:1 mapping between `Instances` you train on and "instances" you care about - e.g in the SRL model case, we need to run the model forward once for each verb and aggregate for the "instance" i.e the sentence that we actually care about.

However, it is true that the current `predict` command should be able to use as a default since now we can `evaluate` on data in the original format, a predictor which just spews everything out into json. So I think the right answer is to have a default option which is overridable.

**Comment by brendan-ai2** [comment]
Somebody got hit by this again: https://github.com/allenai/allennlp/issues/2849

**Comment by brendan-ai2** [comment]
Hey @ZhaofengWu, this should be a decent starter issue to help you get familiar with developing on the codebase. No particular rush -- the tutorials are more important. But do let me know if you have any questions!
