### ISSUE TITLE
How to find char offsets? 

### ISSUE THREAD

**Issue by danyaljj** [allenai/allennlp#1676]
Hello there, 

TLDR:  I am processing an input with AllenNLP, and I get output labels for a bunch of spans. 
How can I get the char offsets for each returned span?  

**Details:** 
I processed an input with SRL: 
```python 
predictor = load_srl_model()
inputs = {
    "sentence": "this       is       the      best        sentence. "
}
result = predictor.predict_json(inputs)
```

The output would like this: 
```json
{
  "verbs": [
    {
      "verb": "is",
      "description": "[ARG1: this] [V: is] [ARG2: the best sentence] .",
      "tags": [
        "B-ARG1",
        "B-V",
        "B-ARG2",
        "I-ARG2",
        "I-ARG2",
        "O"
      ]
    }
  ],
  "words": [
    "this",
    "is",
    "the",
    "best",
    "sentence",
    "."
  ]
}
```
I need to "locate" each argument span in the text (and do something with that), and for that I need *char offsets*. Note that just having a mapping from labels to tokens (or token indices) is not enough, since the output often eliminates extra white spaces.

**Comment by matt-gardner** [comment]
Basically, you need to add some metadata about the tokens that keeps track of this information.  If you're using spacy as your tokenizer, spacy keeps track of this, and we use it when [making `Instances` for reading comprehension](https://github.com/allenai/allennlp/blob/cbeef924a448cb9f8dfb7b5832d5d5f98d8262fc/allennlp/data/dataset_readers/reading_comprehension/util.py#L186-L192).

For adding this to an SRL model, you have to change some code.  You need the `Instances` to have the character offsets that you want (you could add this to the [dataset reader](https://github.com/allenai/allennlp/blob/cbeef924a448cb9f8dfb7b5832d5d5f98d8262fc/allennlp/data/dataset_readers/semantic_role_labeling.py#L109-L110), or by [hacking the `Instances` in the predictor](https://github.com/allenai/allennlp/blob/cbeef924a448cb9f8dfb7b5832d5d5f98d8262fc/allennlp/predictors/semantic_role_labeler.py#L101-L102)), you need the model to [pass through the metadata field in `forward`](https://github.com/allenai/allennlp/blob/cbeef924a448cb9f8dfb7b5832d5d5f98d8262fc/allennlp/models/semantic_role_labeler.py#L153-L155), and you need the predictor to format the information how you want it in [`predict_json`](https://github.com/allenai/allennlp/blob/cbeef924a448cb9f8dfb7b5832d5d5f98d8262fc/allennlp/predictors/semantic_role_labeler.py#L207-L211).

This is a bit of an annoying process just to get some additional metadata into some JSON output.  We had a different API earlier that would have made this a little bit easier, because you could just add some stuff directly to the predictor, but that way had its own problems.

**Comment by danyaljj** [comment]
Makes sense. Thanks :)

**Comment by matt-gardner** [comment]
Hmm, yeah, looks like you were able to bypass a lot of the headache that I thought you'd have to go through.  Looks nice!
