### ISSUE TITLE
Support BMES tagging set in CrfTagger

### ISSUE THREAD

**Issue by huntzhan** [allenai/allennlp#1685]
**Is your feature request related to a problem? Please describe.**

Yes. I'm trying to use `CrfTagger` to handle the CWS (Chinese Word Segmentation) sequential tagging problem, with the commonly used BMES tagging set. Currently, only `BIO`, `BIOUL`, `IOB1` are supported.

BMES tagging explained: https://arxiv.org/pdf/1712.02856.pdf:
> One commonly used tagging set is T = {B, M, E, S}, representing the begin, middle, end of a word, or single character forming a word.

**Describe the solution you'd like**

1. I wonder if the BMES tagging set could be supported.
2. Moreover, could `CrfTagger` support arbitrary tagging?

I could help submit a PR if you don't have enough bandwidth or this feature is in low priority.

**Describe alternatives you've considered**

Right now I switch to use BIO tagging set as a workaround. I've looked into the code and could not find a workaround to make `CrfTagger` support BMES tagging set (i.e. disable constraint rule). 

**Additional context**

None.

Thanks!

**Comment by matt-gardner** [comment]
You've got a few questions in here:

### Can I use arbitrary tagging with the CRF?

Yes.  You just need to pass in a [set of constraints](https://github.com/allenai/allennlp/blob/82686c10bdca062a7e41825000c39372de354479/allennlp/modules/conditional_random_field.py#L148-L152) that specify what the valid transitions are in your tag set.  This is only for the `ConditionalRandomField` _module_, though; to use the `CrfTagger` _model_ with a different set of constraints, you'd have to resort to some hackery, redefining [the `crf` field](https://github.com/allenai/allennlp/blob/82686c10bdca062a7e41825000c39372de354479/allennlp/models/crf_tagger.py#L83-L92) on the model with a newly-instantiated one with your own constraints.  Instead of doing that, though, it'd probably be easier to just add BMES to our allowed tag set (see below).

### Can I use BMES?

Yes, with a bit of work.  @nelson-liu recently refactored [the code that constructs the constraints above](https://github.com/allenai/allennlp/blob/82686c10bdca062a7e41825000c39372de354479/allennlp/modules/conditional_random_field.py#L96-L132) for certain tag sets, so it should be pretty straightforward to add support for BMES there.  PRs welcome.

That handles getting a set of constraints for viterbi decoding in the CRF, but it doesn't handle actually _reading_ BMES tags.  If you've already got a dataset that's tagged with BMES, and a way to read it in, then that should be all you need.  If you're hoping to add BMES to one of our dataset readers, that will probably take changing some code (e.g., [here](https://github.com/allenai/allennlp/blob/82686c10bdca062a7e41825000c39372de354479/allennlp/data/dataset_readers/conll2003.py#L129-L135), but it depends on what dataset you want to work with).

**Comment by huntzhan** [comment]
@matt-gardner , thanks for your explanation!
I'll submit a PR for adding BMES constrain to `is_transition_allowed`, to enable BMES tagging support in `CrfTagger` *model*.

**Comment by nelson-liu** [comment]
Note that if you don’t care about constrained decoding, #1661 made it possible to use BMES out of the box with CrfTagger

**Comment by huntzhan** [comment]
@nelson-liu 
 Thanks for the clarification. `CrfTagger` doesn't generate `constraints` by default (`constrain_crf_decoding = None` and `label_encoding = None`), so all tags will be supported.
