### ISSUE TITLE
Maintain a list of models with performance, size and download links

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#1704]
We have more available models than are in the demo with various different attributes. We should make it easy for people to discover these, either via the website, download links in the demo or in the github readme (or preferably a combination).

**Comment by schmmd** [comment]
I opened a ticket to add download links in our demo: https://github.com/allenai/allennlp/issues/1704

**Comment by schmmd** [comment]
I worry about becoming the central repository for all models derived from AllenNLP.  While I see the utility, what do we do when models are updated or beak due to a breaking change in AllenNLP?  Already I don't know how to find the models that have been created on AllenNLP.

Maybe we should have a repository people can contribute to (self serve)?

**Comment by matt-gardner** [comment]
I think this is basically just the user gallery.  We should have a single list somewhere in a markdown document (either the README itself, or linked from the README) that has all of the known models, separated by whether they are in the repo or in some other repo, with links to the model archive file and the code.  We should have a similar list for dataset readers.

**Comment by schmmd** [comment]
Well, we have a user gallery at the bottom of https://allenai.github.io/allennlp-docs/.  But it doesn't link out directly to models and it doesn't list performance numbers.

**Comment by DeNeutoy** [comment]
No, I mean _our_ models which we have which aren't in the demo. E.g a lot of our models in the demo have elmo built into them, which makes them very slow, but we have all of the variants without Elmo, but people can't access them. Often people want to download a specific model and have it in a particular location, not just magically in a cache.

**Comment by schmmd** [comment]
@DeNeutoy thanks--that makes a lot of sense ;-)

**Comment by matt-gardner** [comment]
@DeNeutoy, right, and I think wherever that list lives is a natural place to also list all known outside implementations, too.  That way everything's in the same place.

**Comment by schmmd** [comment]
@DeNeutoy do you know of models of our own that are somewhere other than `s3://allennlp/models/`?

I'm scoping this ticket to just organizing our own models for now.

**Comment by DeNeutoy** [comment]
No, they all should be there. When you get around to it I can message you with the extra ones

**Comment by DeNeutoy** [comment]
Right - I meant I will send you the models we have which aren't in the demo.

**Comment by schmmd** [comment]
@DeNeutoy I'm going to start out just aggregating them in a markdown file (MODELS.md) and we can go from there.  I'm disinclined to add them to https://allennlp.org/models because I think we'll move most of the content from that page and into the demo (see https://github.com/allenai/allennlp-demo/issues/68).

Next quarter we'll be able to add more models to the demo, but I think we need to figure out what exactly we want to host there.

**Comment by schmmd** [comment]
@DeNeutoy here's a stab.  Feel free to change anything directly.  I'll add model sizes.

I tried to leave out prose to avoid duplicating it in yet another location.

https://github.com/allenai/allennlp/pull/1802

**Comment by schmmd** [comment]
Fixed by https://github.com/allenai/allennlp/pull/1802
