### ISSUE TITLE
Unable to understand the output "Elmo representations"?

### ISSUE THREAD

**Issue by arsalan993** [allenai/allennlp#1728]
This is code 
`from allennlp.modules.elmo import Elmo, batch_to_ids`
```
options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"`
`elmo = Elmo(options_file, weight_file, 2, dropout=0)
```
```
# use batch_to_ids to convert sentences to character ids
sentences = [['pizza'], ['Food']]
character_ids = batch_to_ids(sentences)
```
```
embeddings = elmo(character_ids)
embeddings['elmo_representations']
```

But i want out like what i get using genism word2vec and fasttext for example "most similar words"

**Comment by DeNeutoy** [comment]
See the tutorial: 
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md

You can compare the vectors by taking their similarity between each other. Similar words are harder to compute for elmo, because they are contextual, which means that the set of embeddings that you compare to are not fixed - they depend on their context.
