### ISSUE TITLE
Is it possible to pip install allennlp on python 3.5.1 ?

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#1788]
The latest allennlp requires python version to be 3.6. 
Is it possible to pip install allennlp on python 3.5.1 ? Because updating python is not an option right now for me.

**Comment by matt-gardner** [comment]
No, we make heavy use of python's type annotations, including inline annotations on variable assignments, which requires python 3.6 (and, because of a bug in 3.6.0, we actually require 3.6.1+).  If the problem is root access to install a new python binary, it's quite easy to install your own python without root access using anaconda.
