### ISSUE TITLE
Feature request: Capability for model parameter renaming on load

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1800]
This is from Oyvind:

> One annoying feature of the framework is that if I clean things up by, say, removing an unused/irrelevant model parameter, or improving a parameter name, it's a pain to reuse already trained models even though they should still be valid. Maybe there should be some sort of migration function where I can load a model while specifying irrelevant (and possibly renamed) parameters, then save it back out again. I might look at that at some point... I imagine that has come up elsewhere?

I've also run into this, as I did some major refactoring of the semantic parsing code.  Changing the parameter names made my old models invalid.

**Comment by joelgrus** [comment]
👍 

I ran into this today when I was I trying to replace the _ElmoCharacterEncoder with the calypso version (and wanted to change the names of things slightly)

**Comment by OyvindTafjord** [comment]
Not sure how common this issue is, but I was imagining a simple migration function which takes in a `model.tar.gz` model and outputs another one, which can keep a trained model valid after doing trivial updates in the code, such as:

  * Rename/remove config parameters  (by updating `config.json`)
  * Rename/remove model params (by updating `weights.th`)

It would be the responsibility of the user to know that these are "safe" transformations that don't materially change the model unintentionally. I think implementation is very straightforward, the trickier part would be defining a syntax for such a function which is general enough without being too obtuse, but simple lists of renames and deletes might be a useful start.

**Comment by HarshTrivedi** [comment]
If issue is just about defining syntax or general enough way, I think it can tie together quite well with `archive-surgery` script. It already allows users to freely update `config.json` easily with editor. We can use the same approach to update `weights.th` module/parameter names with an editor, except this time instead of showing config json, it will show parameter-names json.

For example, [this](https://github.com/allenai/allennlp/blob/44e1f005740e5705e0481f985bb83c1c9c4cacd1/allennlp/tests/fixtures/decomposable_attention/parameters_inspection.json) kind of file from #2466 will open in editor, except tunable/freeze etc information. User can just change the names in that file in-place (eg. change `_compare_feedforward ` to `_comparision_feedforward ` or something) Later, model's modules tree and new-names tree can be traversed to update names.

The updated `archive-surgery` can run in two modes, `config` or `model`, each with `inspect` and `update` subcommands. Inspect would just dump config or model parameter names json and update would open editor to update them freely.

Ping everyone in this conversation (@matt-gardner @joelgrus @schmmd @OyvindTafjord).

**Comment by matt-gardner** [comment]
Yeah, I think some kind of "surgery" script is the right way of thinking about this.  I'm not really sure what that script should look like, though.  You can't really edit the `.th` file in place like you can with the config file.

**Comment by HarshTrivedi** [comment]
Loading weight.th, we get `OrderedDict[str, Tensor]`, with key names like:

```
[u'_first_action_embedding', u'_first_attended_question', u'_question_embedder.token_embedder_tokens.weight', 
 ...]
```
If we have a way of mapping old path names to updated path names, it's easy to `toch.load('weights.th')`, update the ordered-dict keys according to user's change and save it in-place back by `toch.save('weights.th')`. Am I missing something?

Simplest solution could be, that `archive-surgery` in `model` mode will open a file with something like following list
```
[u'_first_action_embedding', u'_first_attended_question', u'_question_embedder.token_embedder_tokens.weight', u'_encoder._module.weight_ih_l0', u'_encoder._module.weight_hh_l0', u'_encoder._module.bias_ih_l0', u'_encoder._module.bias_hh_l0', u'_action_biases.weight', u'_action_embedder.weight', u'_output_action_embedder.weight', u'_entity_type_encoder_embedding.weight', u'_entity_type_decoder_embedding.weight', u'_neighbor_params.weight', u'_neighbor_params.bias', u'_linking_params.weight', u'_linking_params.bias', u'_decoder_step._start_type_predictor.weight', u'_decoder_step._start_type_predictor.bias', u'_decoder_step._input_projection_layer.weight', u'_decoder_step._input_projection_layer.bias', u'_decoder_step._output_projection_layer.weight', u'_decoder_step._output_projection_layer.bias', u'_decoder_step._decoder_cell.weight_ih', u'_decoder_step._decoder_cell.weight_hh', u'_decoder_step._decoder_cell.bias_ih', u'_decoder_step._decoder_cell.bias_hh']
```
which user can edit inplace in a file and since list and dict are ordered, the weights dict (`OrderedDict[str, Tensor]`) can be easily updated.

**However,** editing list of all parameter names can be tedious and also errorsome. Tedious because of module name changes, all sub-parameters need to be updated. Error-some because we don't want to allow changing the tree structure. So I am saying, editing this [this](https://github.com/allenai/allennlp/blob/44e1f005740e5705e0481f985bb83c1c9c4cacd1/allennlp/tests/fixtures/decomposable_attention/parameters_inspection.json) kind of file would be better user experience.

**Comment by HarshTrivedi** [comment]
We could add two modes in archive-surgery script: `model` and `config`, latter being the default. Each mode would allow two options `inspect` and `update`. Eg. `archive-surgery model inspect` would show a file like [this](https://github.com/allenai/allennlp/blob/44e1f005740e5705e0481f985bb83c1c9c4cacd1/allennlp/tests/fixtures/decomposable_attention/parameters_inspection.json) and `archive-surgery model update` would open file like [this](https://github.com/allenai/allennlp/blob/44e1f005740e5705e0481f985bb83c1c9c4cacd1/allennlp/tests/fixtures/decomposable_attention/parameters_inspection.json) in an editor which can be used to update model parameter names. Similarly, for `archive-surgery config inspect`, the config file will be shown a output and `archive-surgery config update` will open `config.json` in editor which can be updated in place.

**Comment by matt-gardner** [comment]
So, this handles renaming, and the way you're suggesting doing it looks fine to me.  It doesn't handle removing old parameters, though that isn't as common, probably.

**Comment by HarshTrivedi** [comment]
I didn't think of that use case. However, I think it should be easy to allow it. Eg. in the nested ordered dict like [this](https://github.com/allenai/allennlp/blob/44e1f005740e5705e0481f985bb83c1c9c4cacd1/allennlp/tests/fixtures/decomposable_attention/parameters_inspection.json), user can simply delete any node (eg. "_aggregate_feedforward") in the text editor by setting "none", and all subsequent module/parameters would be deleted.  

```
    "_aggregate_feedforward":  "none",
    ...
```
Whereas the default value of leaves would be "parameter", instead of "tunable" / "frozen" as in the [file](https://github.com/allenai/allennlp/blob/44e1f005740e5705e0481f985bb83c1c9c4cacd1/allennlp/tests/fixtures/decomposable_attention/parameters_inspection.json).

...

Btw, I am quite tied up for next 2 weeks. So won't be able to take this until then.

**Comment by matt-gardner** [comment]
I'm not sure why you would be tied up... =).  Good luck with ACL submissions.

On this issue, though, how do you distinguish between a bunch of renamings and a deletion?

**Comment by HarshTrivedi** [comment]
Thanks! Best of luck to you and everyone at AI2 as well 👍! 

Since we have ordered dict, I think it should be possible. Eg. If we have order of keys `["A1", "B1", "C1", "D1"]` at some level, and we want to rename them as `"A1"->"A2"`, `"B1"->"B2"`, `"D1"->"D2"` and delete `"C1"`, config can update:

```
{
    "A1": {...},
    "B1": {...},
    "C1": {...},
    "D1": {...}
}
```
to
```
{
    "A2": {...},
    "B2": {...},
    "C1": "none"
    "D2": {...}
}
```

The mapping from OrderedDict loaded from `weight.th` and the editor file can happen from position and not name per se.

Am I missing anything?

**Comment by matt-gardner** [comment]
Yeah, that might work.  The "none" or "remove" key is a bit magical, but this whole thing is a pretty rare use case, anyway, so reading some documentation on how to use the tool for a one-off surgery is probably fine.

**Comment by matt-gardner** [comment]
I think this is pretty easy to solve with a one-off script, and rare enough that it doesn't make sense to have such a script in the library itself.  Closing this issue.
