### ISSUE TITLE
List does not get instantiated correctly by default from_params

### ISSUE THREAD

**Issue by danieldeutsch** [allenai/allennlp#1862]
I have a custom class called `Annotator` which inherits `Registrable` and has a few subclasses that I register. My dataset reader accepts a parameter of type `List[Annotator]`. When my dataset reader is instantiated, the list of annotators is given as `List[Params]`.

There are several ways to get around this, such as by implementing my own `from_params`, but it would be nice if the objects were created by default.

I'm using allennlp version 0.6.1

**Comment by DeNeutoy** [comment]
Thanks, this is a bug (or at least, it is not currently supported but should be, because it's not too difficult).

If you're interested in contributing, the code for parsing the annotations and a params file is here:

https://github.com/allenai/allennlp/blob/master/allennlp/common/from_params.py#L175

You can see that the example for `Dict[any, ClassWhichIsRegisterable]` is already implemented - adding options for the other basic python collections such as `Tuple`, `List` and `Set` should not be too difficult.

You could add a test here too if you did pick this up 😄 
https://github.com/allenai/allennlp/blob/master/allennlp/tests/common/from_params_test.py#L15
