### ISSUE TITLE
NER fails on lower case words

### ISSUE THREAD

**Issue by chankeypathak** [allenai/allennlp#1880]
Example sentence:

allennlp is a pytorch-based natural language processing library.

If you replace allennlp with AllenNLP and pytorch with PyTorch then it works.

**Comment by DeNeutoy** [comment]
Yep - these models certainly use orthographic features such as capitalisation as strong learnt features, because in naturally occurring text, frequently they are very predictive. Hopefully that answers your question? In order to do NER at a deeper level, you do need to integrate some sort of knowledge resource, because otherwise you can essentially only rely on surface forms.

**Comment by chankeypathak** [comment]
How do I create such knowledge resource?

**Comment by chankeypathak** [comment]
How can I create a custom model if I have some labelled data?
