### ISSUE TITLE
allennlp.common.checks.ConfigurationError

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1942]
i create a dataset reader for coqa, and run the command:
allennlp train \
    experiments/enhance_qa.json \
    -s /tmp/coqa_serialization \
    --include-package baseline \

but get this error:
2018-10-24 10:13:38,904 - INFO - allennlp.common.params - dataset_reader.type = coqa
Traceback (most recent call last):
  File "/data1/susht3/local/anaconda3.6/lib/python3.6/site-packages/allennlp/common/params.py", line 259, in pop_choice
    raise ConfigurationError(message)
allennlp.common.checks.ConfigurationError: "coqa not in acceptable choices for dataset_reader.type: ['ccgbank', 'conll2003', 'conll2000', 'ontonotes_ner', 'coref', 'winobias', 'event2mind', 'language_modeling', 'multiprocess', 'ptb_trees', 'squad', 'quac', 'triviaqa', 'srl', 'semantic_dependencies', 'seq2seq', 'sequence_tagging', 'snli', 'universal_dependencies', 'sst_tokens', 'quora_paraphrase', 'atis', 'nlvr', 'wikitables', 'template_text2sql', 'grammar_based_text2sql', 'quarel']"
[INFO/MainProcess] process shutting down

**Comment by matt-gardner** [comment]
You probably aren't importing your dataset reader in the `baseline` package - we don't search packages recursively. Either that or you don't have a `register` decorator on your class. You get that error when your class hasn't been registered.

**Comment by susht3** [comment]
> You probably aren't importing your dataset reader in the `baseline` package - we don't search packages recursively. Either that or you don't have a `register` decorator on your class. You get that error when your class hasn't been registered.

i register the class in my dataset reader:
@DatasetReader.register("coqa")
class CoQAReader(DatasetReader)

and i import the dataset reader in the baseline package by __init.py__:
from baseline.dataset_readers import *

**Comment by zhutixiaojie0120** [comment]
Hi Suting,

I am Jun.
Currently I I now have the same problem,
I don't know how to solve that.

Even I did the two things as you did:
----
in my case:
I did these two too:

(1) 
@DatasetReader.register("medline_bilou")
class MedlineDatasetReader(DatasetReader):

(2) 
from allennlp.data.dataset_readers.medline_bilou import MedlineDatasetReader

And my execute command is:
allennlp train …/config.json --serialization-dir …/serialization-dir/ --include-package allennlp.data.dataset_readers

But it still could not read it and gave me the same type of error:
allennlp.common.checks.ConfigurationError: "medline_bilou not in acceptable choices for dataset_reader.type:…

Do you know where should I modify or where should I update my code?

Best regards,
Jun

**Comment by joelgrus** [comment]
unless you changed `allennlp/data/dataset_readers/__init__.py` to import your custom dataset reader, that include-package won't catch it. most likely you should just change it to

```
--include-package allennlp.data.dataset_readers.medline_bilou
```

**Comment by zhutixiaojie0120** [comment]
Dear Mr. Joel Grus,

Thank you for your quick reply on my issue.

I did these modifications:
(1) creating a new file in "dataset_readers": medline_bilou.py 
In this file, I also did some required modifications:
@DatasetReader.register("medline_bilou")
class MedlineDatasetReader(DatasetReader):
 
(2) In "__init__.py", I added this line:
from allennlp.data.dataset_readers.medline_bilou import MedlineDatasetReader

(3) In my "config.json" file, I did this:

    "dataset_reader": {
        "type": "medline_bilou",
        "tag_label": "ner",
        "coding_scheme": "BIOUL",

(4) While during training, I did this:
allennlp train .../config.json --serialization-dir .../serialization-dir/ --include-package allennlp.data.dataset_readers.medline_bilou

Did I  do anything wrong? 
or am I actually still missing anything which is actually required during customized training?

Best regards,
Jun

**Comment by zhutixiaojie0120** [comment]
Dear Mr Joel Grus,
Thank you for your kind reply.
I solved the problem and now I am writing here to help other people who may have the same problem as me.

I did these modifications:
(1) creating a new file in "dataset_readers": 'allennlp/data/dataset_readers/medline_bilou.py'
In this file, I also did some required modifications:
'@DatasetReader.register("medline_bilou") 
class MedlineDatasetReader(DatasetReader): '

(2) 'allennlp/data/dataset_readers/__init__.py'
I added this line:
'from allennlp.data.dataset_readers.medline_bilou import MedlineDatasetReader'
(3) In my "config.json" file, I did this:
"dataset_reader": {
    "type": "medline_bilou",
    "tag_label": "ner",
    "coding_scheme": "BIOUL",
(4) While during training, I did this:
'allennlp train .../config.json --serialization-dir .../serialization-dir/ --include-package allennlp.data.dataset_readers.medline_bilou'

But it still threw me a result like "can not find the module....":
 
Error Analysis:
Because the “.” in “allennlp.data.dataset_readers.medline_bilou” means finding the packages/files “/” (under this folder). If the code can not find the packages or files there, it will throw an error by saying “can not find the module…”

Because when we execute the code "allennlp.data.dataset_readers.medline_bilou",  the dot "." means the directory "/". If we don't execute the code under the right directory, it will throw the error "can not find the module..."

**Comment by gohjiayi** [comment]
This might also be helpful for individuals not looking to edit the allennlp package directly.

The following is instructions from allenai/allennlp-template-config-files/my_project/__init\__.py seen [here](https://github.com/allenai/allennlp-template-config-files/blob/master/my_project/__init__.py). One can follow the repository structure to import your custom models and dataset instead. 

```
# These imports are important for making the configuration files find the classes that you wrote.
# If you don't have these, you'll get errors about allennlp not being able to find
# "simple_classifier", or whatever name you registered your model with.  These imports and the
# contents of .allennlp_plugins makes it so you can just use `allennlp train`, and we will find your
# classes and use them.  If you change the name of `my_project`, you'll also need to change it in
# the same way in the .allennlp_plugins file.
```
