### ISSUE TITLE
Is it possible to get word+char embeddings and word embeddings individually with a single TextFieldEmbedder

### ISSUE THREAD

**Issue by feralvam** [allenai/allennlp#2077]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System:**
 - OS: OSX
 - Python version: 3.6.6
 - AllenNLP version: I installed from master
 - PyTorch version: 0.4.1

**Question**
In a model that I am implementing I require, for a given text_field, to obtain word+char embeddings and also just the word embeddings, separately to be used in two different computations. I'm using pre-trained word embeddings. What would be the best way to accomplish this?

In the configuration file, I can specify the text_field_embedder to use both token_embedders and token_characters. After that, in the code, I can just use: 

`text_embeddings = self._text_field_embedder(text))`

and I get the word+char embeddings. However, I couldn't find a way to specify to the embedder to just return the word embeddings. 

One possibility would be to configure a different text_field_embedder in the configuration file for just token_embedders. But that would cause, as far as I can understand, that each text_field_embedder loads the pre-trained word embeddings individually, which wouldn't make any sense.

Any suggestions? Thank you in advance for the help.

**Comment by joelgrus** [comment]
if you look at how the text_field embedder works, it's just concatenating the two embeddings:

https://github.com/allenai/allennlp/blob/master/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L90

so it should be easy to recover one of them (and then use it separately) just by slicing the result appropriately

**Comment by matt-gardner** [comment]
@joelgrus's solution would work, but you have to be careful about the ordering of the result, because we [re-order the keys](https://github.com/allenai/allennlp/blob/193bb04ddae7d89ee63005b898a01641447d6074/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L73).

You can also just take `Embedder` and `TokenCharactersEmbedder` as input to your model, instead of `TextFieldEmbedder`, and apply them to whatever pieces of the input dictionary that you want.  This is one of the cases where our built-in abstractions don't serve you incredibly well, so you don't have to use them, and that's ok.

**Comment by schmmd** [comment]
Let us know if you have further problems!
