### ISSUE TITLE
Remove BasicIterator and make the `padding_keys` argument to `BucketIterator` optional

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#2079]
These do the same thing and it's a bit of a trap for new users because using a basic iterator can really make your training go 10x slower but it's reasonable to assume the BasicIterator is a good starting place. At least if the `padding_keys` arg was present people might find out about it.

**Comment by joelgrus** [comment]
as part of this we should follow up on the TODO about better documenting how the sorting_keys work

**Comment by matt-gardner** [comment]
#3603 makes this even easier. We now guess sorting keys when none are given.  The only thing that needs to be done is make it possible to not sort, which we could maybe do if you explicitly pass `[]` as the sorting keys, so we don't need to add another parameter (i.e., we'd check for `is None` in the right place, instead of `not self._sorting_keys`).  And then the bucket iterator completely subsumes the basic iterator, while being dramatically more efficient in the average case.

**Comment by matt-gardner** [comment]
I'm closing this, as #3079 covers what's in here.  #3700 should resolve both #3079 and this.
