### ISSUE TITLE
Pass additional arguments when constructing Predictors

### ISSUE THREAD

**Issue by sai-prasanna** [allenai/allennlp#2082]
While prediction, I find myself needing some parameters to be passed to the predictor. 

e.g., A Threshold value for filtering output, beam size etc

These can vary for the same model, so putting it in config.json is not an option.
Currently, the way to do it will be to create a new command.

**Possible solution**

In `allennlp predict` command, send values of extra unused arguments or a dictionary argument `inference_params`  to `Predictor.from_archive/from_path`, so any Predictor can override them to inject inference parameters.

**Comment by DeNeutoy** [comment]
Hey! Unfortunately we probably won't do this, because I'm not sure it's a super common use case. However, you can see the `predictor` command here: 
https://github.com/allenai/allennlp/blob/master/allennlp/commands/predict.py

It should be very easy to write a python script `predict_with_args.py` which you can run separately to the allennlp command. If you try this and you find it hard, it would be great if you could let us know what was hard about it, because it's something we are trying to encourage (e.g using allennlp as a library as well as a command line tool to run configs).

**Comment by sai-prasanna** [comment]
@DeNeutoy Yeah, I can write a command for it, thanks to the well thought out API. And we are using allennlp as a library (adding new models and tokenizers ) and stuff. 

I thought it might be a common case wherein you need runtime parameters to benchmark a model with different inference time settings (beam width, etc). 

And it wouldn't add any breaking change to the existing command or the API, since only people overriding the static methods can do the injecting. 

If you are convinced by this, I can contribute, If not will close the issue.

**Comment by matt-gardner** [comment]
For something that's a major addition like this, we like to see more people asking for it before committing to making the API more complex, especially because it should be pretty easy to write your own script to accomplish what you want.

The issue is that it's not really clear how to pass these arguments from a command line, or what the right way is to modify `Predictor.from_archive`. It would need some careful thought to make sure we're handling all of the use cases right, and for that we really would like to see more than one use case. So, if anyone else has a good use case for this, speak up.

**Comment by matt-gardner** [comment]
And your use case is interesting and helpful - if you do write your own script or whatever to do this, leave us a link on this issue, so we have a well-documented use case to look at if this comes up again, and we can think of a good way to add in something general to the API.

**Comment by sai-prasanna** [comment]
@matt-gardner Thanks will do that. We can close this issue if necessary.

**Comment by rangwani-harsh** [comment]
Hi team, I faced a similar issue here where I need to pass my test_data as a list as it has the path of both the pretraining data along with the actual text dataset path #2034. So while using the evaluate command I could not pass them as one filename. 

As we have the option of making overrides by using a JSON file can't we use that JSON to express any other arguments that we may need rather than making optional arguments to the bash command. In this way, we would always be using JSON to specify the parameters (i.e. dataset path etc.).

**Comment by matt-gardner** [comment]
@rangwani-harsh, this seems like a very different use case.  In Sai's case, you want to change how the `Predictor` behaves based on some parameters.  In your case, you want to change how the `predict` or `evaluate` _command_ interprets its arguments.  It's not at all clear to me that these two should have the same solution.

You are right, though, that you could imagine passing in a JSON file to these commands to try to fix these problems.  I'm just not sure at this point that we need that additional complexity.

**Comment by david-waterworth** [comment]
I have a similar requirement. I don't see any way of training a tagger using a different language, and then constructing an appropriate SentanceTaggerPredictor for it. In particular the SentanceTaggerPredictor takes a language parameter which defaults to "en_core_web_sm" (https://github.com/allenai/allennlp/blob/39c40fe38cd2fd36b3465b0b3c031f54ec824160/allennlp/predictors/sentence_tagger.py#L26).

If I train my model using a different language, I want to construct my predictor using the same value of language, not the default. And this really should be included in the config.

As far as I can see there's no way to either pass in additional parameters or even store them in the config.json for the model? Looking at the code for `Predictor.from_path()` you can modify the config.json by passing `overides`, however `Predictor.from_path()` always calls `Predictor.from_archive()` with extra_args=None so the config has no impact on construction of the predictor other than indirectly via the model and data_reader passed as the 1st and 2nd arguments.

It seems that the tokenizer in this case should be moved the data_reader since it's possible to specify that in the config.json?
