### ISSUE TITLE
Elmo not using character cnn

### ISSUE THREAD

**Issue by limuyu0110** [allenai/allennlp#2132]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.5
 - AllenNLP version:  from master
 - PyTorch version: 0.4.1

**Question**

Hi Team, I am a newbie to allennlp. Thank you for your great work!
I am trying to use elmo representations in my own model in allennlp. I used the bilm-tf package to train a new model on my own Chinese corpus and dumped the weight file in hdf5 format. During training, I omitted the 'char_cnn' configuration so that my model would only consider simple word-embedding (during training, there wasn't any error). Then I followed the tutorial "Using ELMo with existing allennlp models" and included my own pretrained Chinese elmo in my model. However, something wrong happened.

<img width="650" alt="issue" src="https://user-images.githubusercontent.com/31646545/49420865-75ff8500-f7c8-11e8-94d6-7b5f1cd4c9e4.png">

Is there any good way to solve this problem ?

**Comment by matt-peters** [comment]
There isn't an easy way to solve it as we don't support models trained without the character CNN now. It requires some code changes to (1) load the embedding matrix instead of the character CNN parameters (2) do the embedding lookup instead of running the CNN layers.  We have some of the functionality for (2) already implemented with the `vocab_to_cache` functionality (e.g. look up from embeddings instead of run the character CNN), so you could re-use some of that.  PRs welcome.

**Comment by matt-peters** [comment]
Also, this may also requires some small changes in bilm-tf to write out the word embeddings to the hdf5 file.

**Comment by schmmd** [comment]
This isn't something we're going to support presently, but please re-open if you have more questions.

**Comment by Wanjun0511** [comment]
@limuyu0110 Did you find some way to solve this problem?  I have the same problem now.

**Comment by michael92ht** [comment]
@schmmd Unfortunately, when using ELMO to perform Chinese NLP tasks, we usually do not use CNN characters.
