### ISSUE TITLE
Label Counter to automatically generate label weights

### ISSUE THREAD

**Issue by YuxianMeng** [allenai/allennlp#2155]
**Is your feature request related to a problem? Please describe.**
When training a model with unbalanced labels, I would like to use weights in loss function, which is not very friendly in AllenNLP.

**Describe the solution you'd like**
By adding label counts in vocabulary, thus users could use this sttributes to build label weights automatically in any model.

**Comment by matt-gardner** [comment]
I think #1809 would fix this - you don't necessarily need to do this in the vocabulary, you could have the dataset reader keep track of how many of each instance there this.  This would be a better place to solve this, as the vocabulary could be read from files instead of created from the data.  And the vocabulary creation will by default look at the dev set, too, which you might not want for your loss.

As a short-term workaround, though, you could just create a vocabulary subclass that keeps track of these counts, and use that instead of the default vocabulary class.

**Comment by schmmd** [comment]
Closing--#1809 tracks the longer-term issue.
