### ISSUE TITLE
Adding Sequential Variational autoencoder

### ISSUE THREAD

**Issue by mataney** [allenai/allennlp#2164]
Hi, thinking of adding VAE as suggesting in https://arxiv.org/abs/1511.06349
Do you think creating a pull request of this model will interest people?

WDYT?

**Comment by schmmd** [comment]
@mataney if you have the model in a separate codebase we can add it to our user gallery (https://allennlp.org/models) now and then you can add it to the library if there's sufficient interest.

**Comment by matt-gardner** [comment]
I'd say, yes, we should definitely add it to our user gallery.  And @mataney, if you're willing to make sure your code meets our high bar for code quality, we'd also be happy to accept it as a contribution.  We need to keep this bar high, because every model or feature that we add to the library comes with a commitment for us to maintain it.

A VAE would be nice to have, particularly if there's a trained model to go with it that does well on some known task.  I know that @kernelmachine has been working on VAEs also, though I'm not sure what state his code is in or what exactly it does.

**Comment by kernelmachine** [comment]
Yep, I have this model implemented in a separate research repository, as part of a larger project of exploring representation learning with VAEs. It is designed to be flexible and generic, so I can experiment with VAEs with different priors, encoder/decoder architectures, and datasets. The project is built to merge into AllenNLP soon, but for now it is its own thing. 

@mataney,  if you're still interested in getting the Gaussian NV-RNN (from Bowman et al) into AllenNLP, I would be happy to share a PR with an implementation (running on PTB) as a starting point.

**Comment by mataney** [comment]
Hi guys, thanks for your comments!

@kernelmachine, this will be awesome. Started writing but comparing my code to yours will be really helpful.
lmk where can I find it?

**Comment by schmmd** [comment]
@mataney @kernelmachine do either of you have an implementation we can host in our model gallery?

**Comment by schmmd** [comment]
@kernelmachine sorry I didn't realize you were Suchin ;-)

**Comment by mataney** [comment]
Hi, I added a PR.
Would appreciate your comments.
https://github.com/allenai/allennlp/pull/2484

**Comment by mataney** [comment]
@kernelmachine Care to have a look?

**Comment by wjn922** [comment]
@mataney Hi, if I want to resume training, whether the loss weights states will be loaded?

**Comment by matt-gardner** [comment]
We are moving all models out of this repo, into sub-repos that focus on particular tasks / groups of tasks.  This model will only have the core abstractions and building blocks, not the models themselves.  If you have a VAE repo that uses the library, we'd love to put it in our list of third-party repos, but we won't be adding new models here.
