### ISSUE TITLE
stablity problems about dialog_qa

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2173]
hi, for dialog qa tasks, when we answer ith question, we can not use information after ith question such as i+1, but i failed the sanity checks for coqa dataset, 

i do these experiments:
1) compute the 1-5 turn question answering f1
2) drop all questions to 10 turns, and then compute the 1-5 turn question answering f1
these 2 results should be the same, but i get different results with small difference.

**Comment by matt-gardner** [comment]
How big is the difference? And is this for training or prediction? There is significant training variance in training these large neural models, so it doesn't surprise me that you see a small difference at training time, if that's what you're describing. Try changing the random seed a few times - that will give small differences too.

**Comment by susht3** [comment]
> How big is the difference? And is this for training or prediction? 

hi, i find that it maybe the problem of elmo, because when i set elmo as 0 at testing, they get the same score. my elmo config is：
"token_indexers": {
      "elmo": {
                "type": "elmo_characters"
            }
}
"elmo_embedder": {
            "allow_unmatched_keys": true,
            "elmo": {
                "type": "elmo_token_embedder",
                "do_layer_norm": false,
                "dropout": 0.3,
                "options_file": "../data/elmo/elmo_2x4096_512_2048cnn_2xhighway_options.json",
                "weight_file": "../data/elmo/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"
            }
        },

**Comment by matt-gardner** [comment]
Interesting, that's a bit surprising to hear - @matt-peters, FYI on the difference between warm vs. cold ELMo.  I guess if the questions are processed by ELMo sequentially I could see this making a bigger difference, but I don't think they are.

Also cc @eunsol - if ELMo breaks your sanity checks, are your sanity checks too restrictive?  Did your own version with ELMo pass your sanity checks?

**Comment by my89** [comment]
Seems like this isn't actually Eunsol's sanity checks but something on CoQA eval server...

**Comment by matt-gardner** [comment]
Apologies, I misread the original post, thinking this was QuAC!

**Comment by matt-gardner** [comment]
@sivareddyg, it was you I should have pinged!

**Comment by sivareddyg** [comment]
howdy everybody! thanks @matt-gardner and @my89 for the heads up.

I don't think this is AllenNLP's problem because the latest submission (Dec 10 2018) of BiDAF++ passed sanity checks. 

@susht3 has multiple models submitted to CoQA. If this is related to [the latest submission](https://worksheets.codalab.org/worksheets/0xe3c8552088c844b1b7d433f3fb167ede/), I provide some diagnostics below:

Sanity checks are to make sure the model doesn't use rationales, current question's answer and future context, during test time, in order to answer a given question. So we have two small splits, one that masks things that should not be used, and the other without any masks.

@susht3 model answers the same questions differently for these two setups. On 500 specific questions, with masks, the model gets 16.6 F1, and without masks it gets 83.2 F1. This is clearly not due to some randomization.

Some outputs of his system in two different settings:

A1 is with mask, A2 is without mask. Hope this helps.

```
3hfnh7hemhei4jimtkd1pojg4ddgq6 4
Q: Does Bob like his neighbors?
A1: no
A2: no
Gold: no

3auqqel7u5tdyn3i1hi8ajv8eju0vy 3
Q: what do they like to play?
A1: no
A2: baseball
Gold: baseball

3wakvudhuwgr3je2hqtctc3c8ld7us 4
Q: who has three children?
A1: no
A2: my brother
Gold: my brother

3aapld8ucch9wv5puupeft644hvhtl 4
Q: Did Andy want to go to bed that night?
A1: no
A2: no
Gold: no

3ymtujh0dsgfkjhufn5vl4x0y7f4th 3
Q: What were they doing?
A1: no
A2: time
Gold: sitting

33nf62tlxj26kiasole7qfznyw9jkn 4
Q: how far was she from shore when this incident happened?
A1: no
A2: 60 metres
Gold: 60 metres

36wlnqg78zaxgzk647qnuw356sfbeh 6
Q: When?
A1: no
A2: 1639
Gold: 1639

36v4q8r5zk0iwte84nbw2t3d1xrmqj 3
Q: Did someone hurt him?
A1: no
A2: yes
Gold: yes

336yqze83vet37vakvnt4i8m434m59 2
Q: Joey didn't like to what?
A1: no
A2: brush his teeth
Gold: brush his teeth

3ob0cao74hp5dh4j40cdnayjjsghyv 5
Q: What party does he belong to?
A1: Republican
A2: Republican
Gold: Republican

3lpw2n6lkt2cgf0jtxefvspgis25um 6
Q: With which department?
A1: no
A2: Las Vegas Metropolitan Police Department
Gold: Las Vegas Metropolitan Police Department

3qapzx2qn4d41w5gd7yx8eyxhjr20e 3
Q: who else stayed there?
A1: no
A2: Arthur
Gold: Arthur

39u1bhvtdlru2nyqf90cbz5ukfdt3v 3
Q: What does it look like?
A1: no
A2: little white mittens
Gold: black with a white spot

3a9aa95atwmzoasncbfllm2h90e5p7 4
Q: Where was he when he called?
A1: no
A2: in the car
Gold: in the car

3dpnqgw4llf9il6ijax2au5mf4764m 6
Q: What else had he done
A1: no
A2: written for television
Gold: he had also written for television.

3x87c8jfv6bluordok7ie22jto0qsu 6
Q: What is Durex?
A1: no
A2: the world's biggest player
Gold: the world's biggest player

3azhrg4cu4ktme1zh7c2ro3po9a30y 6
Q: how long before?
A1: no
A2: some weeks
Gold: some weeks

3nql1cs15r8aviz39pth2bpsr4zvy1 4
Q: What does that also refer to?
A1: no
A2: Twenty20 International matches
Gold: Twenty20 International matches

3efvcay5l39mph8rfwh40aqw343j88 4
Q: what was his profession?
A1: no
A2: Grand Avenue mucker
Gold: Grand Avenue mucker
```

About @susht3 personal experiment described in the opening of this thread, I don't have any idea why the results differ in two settings. As long as the difference is with +1/-1 in our sanity checks, we accept the system.

@susht3 If you have any more questions regarding sanity checks, I would suggest using https://groups.google.com/forum/#!forum/coqa. That will also be useful to others working on CoQA. Some of them may answer too.

**Comment by matt-gardner** [comment]
Thanks @sivareddyg, that's super helpful!  @susht3, I'm closing this issue, pointing you instead to the google group that Siva mentioned.
