### ISSUE TITLE
allennlp (0.7.2) depends on cffi (1.11.2), gevent (1.3.6) is incompatible wi   th allennlp (0.7.2).

### ISSUE THREAD

**Issue by phiresky** [allenai/allennlp#2195]
this issue still happens (or happens again) with allennlp v0.7.2

```
[SolverProblemError]                                                  
Because gevent (1.3.6) depends on cffi (>=1.11.5)                                  
 and allennlp (0.7.2) depends on cffi (1.11.2), gevent (1.3.6) is incompatible wi  
th allennlp (0.7.2).                                                               
And because allennlp (0.7.2) depends on gevent (1.3.6), allennlp is forbidden.     
So, because no versions of allennlp match >0.7.2,<0.8.0                            
 and code depends on allennlp (^0.7.2), version solving failed.
```

_Originally posted by @phiresky in https://github.com/allenai/allennlp/issues/1824#issuecomment-445872785_

**Comment by schmmd** [comment]
@phiresky I'm unfamiliar with poetry.  Can you explain to me how I can repeat the error you are seeing on my own laptop?

**Comment by phiresky** [comment]
Sorry, I don't have a computer right now but this should work:

pip install poetry
mkdir x && cd x
poetry init -n
poetry add allennlp

(Might have to change the min py version in pyproject.toml to ^3.6.1)

**Comment by sodre** [comment]
We experienced the same problem when building the AllenNLP package for conda-forge/staged-recipes#7324. Our solution to that problem was to relax the pinning on `cffi` to `1.11.*`.

This brings me to a slightly larger question of whether the pinnings in AllenNLP are too strict. This issue came up during the peer-review process that every new conda-forge package goes through.  Please see comments [1](https://github.com/conda-forge/staged-recipes/pull/7324#discussion_r243732357) and [2](https://github.com/conda-forge/staged-recipes/pull/7324#discussion_r243732383).


cc: @bgruening

**Comment by schmmd** [comment]
Closing, since we have a new issue with 0.8.0 (#771).

**Comment by sodre** [comment]
Sorry, but how is this issue related to #771? 771 is about codecov and this one is about package pinning.

**Comment by schmmd** [comment]
Sorry @sodre--I got confused when I followed the link to https://github.com/sdispater/poetry/issues/771.  It seems like this is still a problem for AllenNLP 0.8.0 and we should relax our bounds on cffi.  I'm confused however on how relaxing our bounds on cffi fixes the issue since @phiresky reports that `gevent (1.3.6)` requires `cffi (>=1.11.5)` and AllenNLP directly depends on `gevent==1.3.6`.

**Comment by sodre** [comment]
No problem.

By relaxing allennlp's requirement on cffi to 0.11.* instead of 0.11.2 while keeping gevent at 1.3.6 allows the solver to pick cffi 0.11.5 to solve the package dependency graph.

**Comment by sodre** [comment]
@schmmd, The original issue was for AllenNLP 0.7.2, which had it pinned at 0.11.2.
https://github.com/allenai/allennlp/blob/bf04f1dae80eba09ac7f260873ff3ab277698370/setup.py#L112

As far as a suggestion, here is what gevent [uses](https://github.com/gevent/gevent/blob/340a3625b1e8edd96c0ad83c3b8ce09730893892/setup.py#L213-L218).

```python
# The exception is on Windows, where we want the libuv backend we distribute
# to be the default, and that requires cffi; but don't try to install it
# on PyPy or it messes up the build
cffi_requires = [
    "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'",
]
```

I have not tried to do a build against 0.8.0 yet in conda forge. So I am not sure if the error would still happen with your latest setup.py, even without #2271. My gut tells me it should work just fine.

**Comment by schmmd** [comment]
Since we're not even sure this is a problem with the latest release (0.8.0) I'm going to close this issue in favor of the one I just opened (https://github.com/allenai/allennlp/issues/2280) about creating a continuous integration check for dependency conflicts.  I'd love suggestions about what tool we could use to do such a check.
