### ISSUE TITLE
Multiple documents for Machine comprehension

### ISSUE THREAD

**Issue by sandtemp01** [allenai/allennlp#2198]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux] Linux
 - Python version: [e.g. 3.6.1] 3.6.2
 - AllenNLP version: [e.g. v0.7.2, or "I installed from master"] I installed from master
 - PyTorch version: (if you installed it yourself) Using google cloud ML VM

**Question**
I have multiple documents . Right now I am combining all documents text as single passage and sending to AllenNLP along with question. I believe this slows down the process. Is there any alternative in the library?

Referring to : [https://allennlp.org/models](https://allennlp.org/models)

code:
```
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")
predictor.predict(
  passage="The Matrix is a 1999 science fiction action film written and directed by The Wachowskis, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano.",
  question="Who stars in The Matrix?"
)
```

**Comment by matt-gardner** [comment]
See [this paper](https://www.semanticscholar.org/paper/Simple-and-Effective-Multi-Paragraph-Reading-Clark-Gardner/3c78c6df5eb1695b6a399e346dde880af27d1016), implemented [here](https://github.com/allenai/document-qa).  We worked on re-implementing this in allennlp (see [here](https://github.com/allenai/allennlp/pull/804)), but that work stalled due to some training complexities.

There may also be some more recent work that does better than the paper that I mentioned - look for papers citing that one, if you're interested.
