### ISSUE TITLE
Check for existing vocabulary before creating a new one.

### ISSUE THREAD

**Issue by nikhilweee** [allenai/allennlp#2240]
**Is your feature request related to a problem? Please describe.**
Every time I recover from an incomplete training session using the `--recover` flag, allennlp creates a fresh vocabulary. This is redundant and time consuming.

**Describe the solution you'd like**
Since the `train` command already saves the vocabulary to disk ([`allennlp/commands/train.py`](https://github.com/allenai/allennlp/blob/1938a5af6d1ea3a2d8dccbb831f82990800fa3e1/allennlp/commands/train.py#L306)), I think it would be a great addition to first check for an existing vocabulary before creating a new one.

**Describe alternatives you've considered**
Nothing really. This seems to be a pretty straightforward solution.

**Additional context**
https://github.com/allenai/allennlp/blob/1938a5af6d1ea3a2d8dccbb831f82990800fa3e1/allennlp/commands/train.py#L296-L301
My suggestion is to rephrase the section above in the following manner. 
```python
    if os.path.exists(os.path.join(serialization_dir, "vocabulary")):
        vocab = Vocabulary.from_files(os.path.join(serialization_dir, "vocabulary"))
    else:
        vocab = Vocabulary.from_params(
                params.pop("vocabulary", {}),
                (instance for key, dataset in all_datasets.items()
                for instance in dataset
                if key in datasets_for_vocab_creation)
        )
```

**Comment by matt-gardner** [comment]
This seems like a reasonable thing to do if we're given the `--recover` flag.  PRs welcome.  Though, it sounds like you might be developing your model on full datasets instead of using test fixtures.  I have never had reason to use `--recover`, because I test my models on test fixtures, so they generally work when giving them the full data.  Using very small test fixtures and developing your model using `pytest` to check that things are working is a _much_ more efficient mode of development.

**Comment by nikhilweee** [comment]
Thanks for your suggestion Matt! As you rightly guessed, perhaps I haven't been developing the way it's supposed to be done. I usually make some quick changes and re-run the training script again and again on the entire dataset until all possible errors have been addressed. That explaines the need to user the `--recover` flag and my frustration with wait times. I wish I was aware of the test fixtures before.
