### ISSUE TITLE
config_explorer can't start service

### ISSUE THREAD

**Issue by Whu-wxy** [allenai/allennlp#2267]
window7.
When I input 'python -m allennlp.service.config_explorer' in cmd, it returns "[]".

So is there anything I didn't configure ?

**Comment by matt-gardner** [comment]
Sorry, we don't support windows.

**Comment by jinlukang1** [comment]
mac.
When I input 'python -m allennlp.service.config_explorer' in cmd, nothing returns.

So is there anything I didn't configure ?
Thanks.

**Comment by matt-gardner** [comment]
What version of allennlp are you using?  We recently moved the simple server and the config explorer to [allennlp-server](https://github.com/allenai/allennlp-server).  In general, we're going to need more detail in an issue in order to help you.  Please open a new issue (it's easier to track that way), with more detail, if you still are having trouble.
