### ISSUE TITLE
Possible problem in BERT tokenizer.

### ISSUE THREAD

**Issue by hohoCode** [allenai/allennlp#2372]
I do not understand this line in BertTokenizer:
from pytorch_pretrained_bert.tokenization import BasicTokenizer as BertTokenizer

This only does basic tokenization instead of Bert's WorldPiece/BPE tokenization.

Shouldn't this just be?
from pytorch_pretrained_bert.tokenization import BertTokenizer

**Comment by matt-gardner** [comment]
For BERT, we split tokenization into two steps: splitting sentences into words, then splitting words into wordpieces.  We do this because it matches the rest of our API better.  You can see the code for doing the wordpiece tokenization in [this class](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/wordpiece_indexer.py).
