### ISSUE TITLE
Config Wizard incorrectly infers type of Vocabulary min_count

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2402]
It looks like `Vocabulary`'s `min_count` expects a `Dict[str, int]`. But when running the config wizard, the web UI says it expects an `int` (not the right type).

cc: @joelgrus

**Comment by joelgrus** [comment]
there is one-off logic for handling vocabulary, and it seems like it's become wrong:

https://github.com/allenai/allennlp/blob/master/allennlp/common/configuration.py#L471

I need to try to remember why Vocabulary needs one-off logic and either fix it or get rid of it

**Comment by matt-gardner** [comment]
It's one-off logic because any class that has a custom `from_params` could take parameters that aren't inferable from the constructor, and this is true for `Vocabulary`.  Looks like you just accidentally got the type wrong on `min_count` when you made that one-off logic.

This, and the documentation / discoverability issue, and talking with @nelson-liu about new users' experience with `from_params` makes me want even more to figure out a way to remove all of the places that we use a custom `from_params`.  That's a separate issue, though...

**Comment by matt-gardner** [comment]
@joelgrus ping.
