### ISSUE TITLE
Add ability to generate BERT embeddings using a sliding window instead of truncating the input

### ISSUE THREAD

**Issue by Hyperparticle** [allenai/allennlp#2493]
**Is your feature request related to a problem? Please describe.**
The BERT wordpiece indexer will [truncate any sentences that have more than 512 wordpieces](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/wordpiece_indexer.py#L160), which can be problematic for models that assume that the output length is fixed to the length of the input tensor representing word tokens when using `offsets`.

**Describe the solution you'd like**
Ideally, the BERT embedding length should always be equal to the length of the word token embeddings when using `offsets`. A trick [I've seen elsewhere](https://github.com/google-research/bert/issues/66#issuecomment-436378461) would be to break up sentences into smaller chunks of up to 512 wordpieces using a sliding window with a certain stride (e.g., 256).

Assuming a sliding window of length 4 and stride of length 2, a sentence like

```
I went to the store to buy some milk
```

can be broken up into

```
I went to the
to the store to
store to buy some
to buy some milk
```

These token sequences can then be embedded into BERT and recombined by either truncating overlapping sequences or averaging them. Because of possible OOM issues, it might be a good idea to make a backward-compatible change allowing truncation to be an option and sliding window to be another.

To make the change, I'm thinking of modifying the [wordpiece indexer `tokens_to_indices`](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/wordpiece_indexer.py) to return a list of tensors for both `wordpiece_ids` and `offsets`. Then the [BERT token embedder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py) would then call `self.bert_model` on each tensor in the list and recombine them.

**Describe alternatives you've considered**
I have tried to break up long sentences manually in my datasets, but identifying them is a pain. The process also complicates the code, as the sentences need to be recombined after prediction.

@joelgrus Any thoughts on this idea? Additional concerns? I'd be willing to make the PR.

**Comment by joelgrus** [comment]
in that issue you link it looks like for each word they take the embedding from the window in which it's most in the middle?

anyway, I think this is a reasonable idea, my questions would be

(1) is it important to keep the current behavior in the truncate case (token indexer generates a list of wordpiece ids) or is it ok to change it (token indexer generates a list of lists of wordpiece ids, but in the truncate case it's just a single list)

(2) what is the right abstraction to do this in general? the linked issue suggests cherry-picking the best embedding for each word, you also suggest averaging. indeed, the linked issue says:

```
We will probably not release a feature extractor do this specifically because there are too many use cases and details to get this right in every case (e.g., SQuAD is different from other scenarios because it needs to include the question. But others might not need to.)
```

So it's possible that the right thing to do is to modify the WordpieceIndexer so that it can generate sliding windows like you say but then just rely on people to implement their own specific embedders that behave however they like. Because it's not clear to me that anything we do will have the right level of generality.

Thoughts?

**Comment by Hyperparticle** [comment]
(1) I'm of the opinion that wrapping the truncate case in a list would be simplest, as no special logic is necessary to process it any differently in the embedder. Another option could be to just create separate classes for both the indexer and the embedder. This would duplicate code somewhat, but it also allows one to explicitly specify the type of indexer/embedder instead of relying on default behavior. Maybe composing/inheriting a base class would be a good compromise.

(2) There's no right answer to this. I suggest to just pick an embedding strategy that works reasonably well (e.g., cherry-picking), implement a new embedder for it, and let the users override that behavior with their own custom classes if they need to. That way they also have an example of how it should work.

**Comment by joelgrus** [comment]
I think this seems reasonable. My main concern for #1 was breaking people's code, but I'd have to imagine that if they're using our token indexer they're also using our embedder, so it should be transparent to them, so it's probably not a big deal.
