### ISSUE TITLE
[Suggestion] Is it a better idea to put scripts in `allennlp/allennlp/scripts` instead of `allennlp/scripts`?

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2575]
**Is your feature request related to a problem? Please describe.**
When I want to use `archive_surgery.py`, I have to change directory to `allennlp`.
Instead, it may be more convenient for users to call this script like `python -m allennlp.scripts.archive_surgery --help`, which is also easily implemented for us.

**Describe the solution you'd like**
I have gone through the directory `allennlp/scripts`.
There are three kinds of scripts:
 - about building or testing, such as: `check_docs.py, verify.py, mypy.sh`, etc.
 - for data processing, such as: `convert_openie_to_conll.py, regenerate_archived_models.py, examine_sql_coverage.py`, etc.
 - other useful utilities, such as: `archive_surgery.py, build_demo.py, inspect_cache.py`, etc.

As far as I am concerned, it is reasonable to put *data processing scripts* and *other utilities* in `allennlp/allennlp/scripts` instead of `allennlp/scripts`, because they are useful for common users.

What do you think?
 
**Describe alternatives you've considered**
None.

**Additional context**
I am willing to create PR for it.

**Comment by matt-gardner** [comment]
I generally agree with this, though note that we have `tools/` already, and I might use that instead of creating a new `scripts/` module.  One problem is that it might be a bunch of work to get these moved over, as I don't think they are currently bound to follow pylint or mypy.

I would probably also just start with a few files that are most likely to be useful when distributed with the library.  One-off kinds of things probably don't need to be moved.
