### ISSUE TITLE
Allen nlp is using all the cpu  threads on machine.

### ISSUE THREAD

**Issue by samuelharden** [allenai/allennlp#2577]
**System (please complete the following information):**
 - OS: Linux
 - Python version: Python 3.6.6 |Anaconda, Inc.
 - AllenNLP version: 0.8.2
 - PyTorch version: 1.0.1.post2 via anaconda

**Question**
I am training the tutorial model from the website with and without jsonnet.

When I am using it without jsonnet, I am able to set `set_num_threads` and restrict the number of threads and CPU being used on the machine.

If I run with `allennlp` command, it starts using all the available threads on the machine.

```
allennlp train config/sst_initial.json -s set -f --include-package models
```
How can I restrict the number of CPU used by `allennlp` while using jsonnet?

Moreover, In general how can I run any time of setup code using jsonnet?

**Comment by joelgrus** [comment]
I don't think jsonnet allows you to specify that.

The one workaround I can think of is to

1. uninstall jsonnet, and
2. don't use any non-json features in your config file

because we have an alternative code path that falls back to `json.loads` if jsonnet is not installed:

https://github.com/allenai/allennlp/blob/master/allennlp/common/params.py#L17

**Comment by joelgrus** [comment]
closing, feel free to re-open if this doesn't solve your problem
