### ISSUE TITLE
[Suggestion] Option to use raw strings instead of Token objects in TextField

### ISSUE THREAD

**Issue by keitakurita** [allenai/allennlp#2602]
**Is your feature request related to a problem? Please describe.**
I've recently experienced major memory issues using allennlp. The problem stemmed from the fact that each token had to be stored in a `Token` object that incurred massive overhead. Removing the `Token` object reduced memory consumption to less than 1/3 of the original memory usage.

**Describe the solution you'd like**
I think users should also be allowed to simply pass a sequence of strings as input to the text field instead of a list of `Tokens`. I have tried this approach on my own fork of allennlp and did not encounter any major problems: it was relatively simple to make the processing of the TextField agnostic to whether the input was a `Token` or a string, since most of the processing (if not all) extracted the text from the token anyway.

**Describe alternatives you've considered**
I don't think this will reduce the scope of what users can do, so it seems like the least restrictive option for the memory issue.

**Additional context**
I may be missing some of the significance of using the `Token` object. If so, I would love to learn more about this design decision!

Thanks!

**Comment by matt-gardner** [comment]
We use `Token` objects because most of our models use spacy to do pre-processing, and that's what spacy returns. If you don't need the extra fields on a `Token` object, then you're right that it's pure overhead.  Seems reasonable to me to support plain strings in addition to token objects.  PR welcome!

**Comment by matt-gardner** [comment]
The thing to be careful of is that you get informative error messages in failure cases.  E.g., if you pass in plain strings to the passage field in a reading comprehension dataset reader, you're going to crash, because we require the character offsets for those datasets.  So there should be a test that makes sure the error message in that case is reasonable (and possibly the same for other similar cases).

**Comment by joelgrus** [comment]
We've talked before about giving the spacy word splitter an option to return plain allennlp Tokens, which should be more lightweight (and if we changed them to NamedTuples could be even more lightweight), I wonder if that would be good enough from a performance perspective (it's certainly simpler than having the code have to check everywhere whether it has a string or a token).

**Comment by matt-gardner** [comment]
I guess that depends on the application - @keitakurita, are you using spacy at all, or is your text already tokenized?

**Comment by keitakurita** [comment]
Thanks for the feedback!

I am actually using spacy, and also tried using NamedTuples to prevent the necessity for code modification, but ended up using raw strings from a performance perspective (though the overhead of NamedTuples is very small, accumulated across every single token in the dataset, the effect starts to become non-negligible). 
I think checking for whether the input is a string can be done fairly cleanly by changing all instances of accesses to `token.text` to a function `get_token_text` which will extract the text from `Tokens` and return the raw string on other instances.

In terms of error messages, sorry that I'm not very well-versed in the various applications of allennlp, but is whether the actual `Token` objects are needed something that is specific to the dataset? In that case, is it okay to remove the check for inputs being `Token` objects from the `TextField` and move the message to the specific datasets that actually need this functionality?

Thanks!

**Comment by matt-gardner** [comment]
Do you need the multiple-indexing functionality that the `TextField` provides?  Another option is to just use a `ListField[LabelField]`, which will just use strings underneath.  This is pretty ugly, though, and makes it so you can't configure things nicely later...

We've also had issues with excessive time and memory overhead when creating `Tokens` for every character in a document.  This is problematic for models where data processing is the biggest bottleneck (e.g., language modeling, where the model itself is relatively small and fast, as opposed to our big reading comprehension models, where the data is a small part of total processing).  It would be nice to figure out a way to make bare strings work here.

But we have a ton of code that assumes a `TextField` has a `List[Token]`.  We could make this instead have type `Union[List[Token], List[str]]`, and just state that if you pass in a list of strings, it's your own fault if things break later...  It seems too hard to design this such that the accesses are all type safe without a union type.  E.g., we could try to make `text_field.tokens` into a property, but I don't think that solves anything, because the code that accesses the internal stuff in each `Token` is in the calling class, not internal to `TextField`.  In order to make this safe, we'd have to pull in all access of `Token` internals to methods on the `TextField`, which is really ugly and breaks a lot of code.  It looks like the only way forward, if we want to support this, is to make `text_field.tokens` a union type.  Is there any other solution?

**Comment by matt-gardner** [comment]
Ack, if you want to really handle the character tokenization problem, you need this to be a `Union[List[Token], List[str], List[int]]`, because of how `Token.text_id` works...

**Comment by joelgrus** [comment]
yeah, this is why I'm still inclined to see if just making our `Token` class more minimal would be enough

**Comment by matt-gardner** [comment]
Well, our existing `Token` class is "enough" as it is for a large number of workloads.  For other workloads, _any_ class creation at all will be "too much".  It'd be nice to have a story for these other workloads, so they aren't pushed to some other library, or to crazy hacks.

**Comment by joelgrus** [comment]
in theory namedtuples shouldn't add much overhead. possibly this is the wrong test, but if I do

```
from typing import NamedTuple
from memory_profiler import profile

class Token(NamedTuple):
    text: str
    field1: str = None
    field2: str = None
    field3: str = None
    field4: str = None
    field5: str = None

class Token2(NamedTuple):
    text: str

class Token3:
    def __init__(self, text: str) -> None:
        self.text = text
        self.field1 = None
        self.field2 = None
        self.field3 = None
        self.field4 = None
        self.field5 = None

@profile
def get_tokens_raw():
    with open('/usr/share/dict/words') as f:
        tokens = [line.strip() for _ in range(10) for line in f]
    return tokens

@profile
def get_tokens_namedtuple():
    with open('/usr/share/dict/words') as f:
        tokens = [Token(line.strip()) for _ in range(10) for line in f]
    return tokens

@profile
def get_tokens_namedtuple2():
    with open('/usr/share/dict/words') as f:
        tokens = [Token2(line.strip()) for _ in range(10) for line in f]
    return tokens

@profile
def get_tokens_class():
    with open('/usr/share/dict/words') as f:
        tokens = [Token3(line.strip()) for _ in range(10) for line in f]
    return tokens


get_tokens_raw()
get_tokens_namedtuple()
get_tokens_namedtuple2()
get_tokens_class()
```

I see 
46MB for the raw strings
57MB for the many-field namedtuples
52MB for the minimal namedtuples
67MB for the classes

so yes that's some overhead, but it's not *that much* overhead.

**Comment by joelgrus** [comment]
one more data point:

```
Line #    Mem usage    Increment   Line Contents
================================================
    87    267.5 MiB    267.5 MiB   @profile
    88                             def do_it():
    89    273.3 MiB      5.8 MiB       t1 = get_tokens_raw()
    90    273.3 MiB      0.0 MiB       print(len(t1))
    91                             
    92    825.5 MiB    552.2 MiB       t2 = get_tokens_spacy()
    93    825.5 MiB      0.0 MiB       print(len(t2))
    94                             
    95    847.6 MiB     22.1 MiB       t4 = get_tokens_spacy3()
    96    847.6 MiB      0.0 MiB       print(len(t4))
```

the first is generating the tokens as strings, the second is using our spacy_word_splitter and keeping the spacy token objects, the third is using the spacy_word_splitter but then using a NamedTuple for the tokens. it certainly suggests that most of the benefit is from not using spacy tokens, and very little incremental benefit is from using plain strings

**Comment by joelgrus** [comment]
why would accessing the fields of a namedtuple cause extra memory usage?

**Comment by matt-gardner** [comment]
My comment above about accessing fields was talking about runtime.  Memory usage is a concern, definitely, but runtime is also a concern (especially for character-level tokenization).  It'd be nice to see a profile that goes all the way from tokenization to tensor creation, comparing runtime of bare strings vs. the other options you've shown.

So, from what you've already done, I'm strongly in favor of (1) making our `Token` class a `NamedTuple`, and (2) converting from spacy tokens to this named tuple by default.  I agree that there's not a strong memory argument to go further than that, all the way to bare strings, which muddies a whole lot of stuff, as discussed above.  I still don't know if there's a strong runtime argument for going all the way to bare strings or not.

**Comment by keitakurita** [comment]
judging from the above discussion, I agree with @matt-gardner , there would seem to be a fair amount of overhead for supporting bare strings across the entire library. Using a `NamedTuple` would bring some quick and easy memory benefits at a low cost.

That being said, I think it would still be nice to have the option of bare strings in some limited settings. Since my current application is largely memory constrained, every bit of memory overhead counts. Since a large number of applications just use raw strings anyway, having some separate `Field` or `TokenIndexer` handle raw strings explicitly would be a welcome addition in my opinion. But if it seems like too marginal a benefit to support in allennlp, I guess this could be something delegated to each user.

**Comment by matt-gardner** [comment]
In performance-critical use cases, where you're sure you don't want the full functionality of a `TextField`, a `ListField[LabelField]` gives you bare strings, as I said above.  So there already are separate `Fields` that you can use for this, if that's what you really want.

**Comment by joelgrus** [comment]
let me put together a PR for this, it shouldn't take too long

**Comment by keitakurita** [comment]
right, sorry I forgot about that! thanks!
