### ISSUE TITLE
[BUG] Wrong target namespace in SimpleSeq2Seq._forward_loop()

### ISSUE THREAD

**Issue by plroit** [allenai/allennlp#2678]
Similar to #973

https://github.com/allenai/allennlp/blob/0f4175034f5d79f9415e47d915603cbba6af01a6/allennlp/models/encoder_decoders/simple_seq2seq.py#L310

Also on line: 
https://github.com/allenai/allennlp/blob/0f4175034f5d79f9415e47d915603cbba6af01a6/allennlp/models/encoder_decoders/simple_seq2seq.py#L231

When working with SimpleSeq2Seq to produce a target sequence from a different set of tokens with a different namespace, I get a KeyError since the hardcoded value "tokens" is not part of the indexed text field: target_tokens. I specified a different than the default namespace for target_namespace.

**To Reproduce**
Steps to reproduce the behavior
Try to call forward on SimpleSeq2Seq with a different namespace for target tokens. 

**Expected behavior**
This value should **not** be hardcoded, but specified in config.  Replaced with self._target_namespace

**Comment by kernelmachine** [comment]
@matt-gardner can you take a look?

**Comment by matt-gardner** [comment]
I'm out this week, so someone else would be better.

**Comment by joelgrus** [comment]
I can take it

**Comment by joelgrus** [comment]
So I don't think this is a bug; at least, it's not the bug you think it is. Here `target_tokens` is a dict representing the indexed text field, with an entry for each TokenIndexer. So when you see

```
targets = target_tokens["tokens"] 
```

the `"tokens"` is not the vocabulary namespace, it's the key representing the token indexer in

```
{ "tokens": SingleIdTokenIndexer() }
```

So if you're getting an error, it's likely because you specified a different key for that TokenIndexer? Can you just specify "tokens" instead?

**Comment by joelgrus** [comment]
closing, please comment if you still have issues
