### ISSUE TITLE
About the forward inputs of Class ELMo when using "vocab_to_cache" option

### ISSUE THREAD

**Issue by ShengeBelmendo** [allenai/allennlp#2688]
**System:**
 - OS: ubuntu18.04
 - Python version: 3.6.1
 - AllenNLP version: 0.8.2
 - PyTorch version: 1.0.1

**Question**

If I instantiated the ELMo class with vocab_to_cache passed, it seems that I can only pass the word_inputs of shape (batch_size, timesteps) to ELMo during forwarding and don't need to pass the inputs of character ids representing the current batch, but the code keeps inputs always required. I don't understand why is it? It's a design flaw or my misunderstanding?

**Comment by DeNeutoy** [comment]
The code is designed to "back off" to re-computing the cached word vectors (from the char-cnn) if the words are not found in the `vocab to cache` vocabulary. In order to preserve this functionality, we need to pass the character ids to forward as well. The thinking at the time was that if you have the word ids, it's not really much extra work to compute the character ids anyway, so it wasn't particularly relevant performance wise, and allowed us to have this nice feature of gracefully backing off if OOV words are discovered. Hopefully that answers your question, reopen if you have more Qs!

**Comment by ShengeBelmendo** [comment]
Thanks for your response!
