### ISSUE TITLE
ELMoTokenCharactersIndexer does the padding value get masked?

### ISSUE THREAD

**Issue by apmoore1** [allenai/allennlp#2707]
System:
 - OS: Ubuntu
 - Python version: 3.6.7
 - AllenNLP version: v0.8.3

Using the [ELMoTokenCharactersIndexer](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/elmo_indexer.py#L88-L149) does the padding value get masked later on when using a [TokenCharacterEncoder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/token_characters_encoder.py)?

When using the [ELMoTokenCharactersIndexer](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/elmo_indexer.py#L88-L149) from what I gather it creates a vector of 50 dimension for each word where the majority of the values are the padding value which is 260 and then becomes 261 as 1 is added to ensure the 0 value is not used as this is normally the value assigned for masking. I was wondering do these padding values get masked as the [TokenCharacterEncoder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/token_characters_encoder.py) only masks values that are 0 and as the padding values from the [ELMoTokenCharactersIndexer](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/elmo_indexer.py#L88-L149) are 261 does this mean they do not get masked or does something happen in the code base that I have missed that turns the padding values to 0 or does it not matter? Sorry if I have missed something obvious, I am currently playing around with the Transformer ELMo model.

**Comment by kl2806** [comment]
Your understanding of the `ElmoTokenCharactersIndexer` is correct but it is not actually used with the `TokenCharacterEncoder` as Elmo uses its own `_ElmoCharacterEncoder` character encoder (https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo.py#L259).

It doesn't matter what the padding character is in this case, since each word has a fixed length of 50. So the 261 padding character is just part of the representation of that word that is fed to the the Elmo computation. You can find an example of the expected output tokens here (https://github.com/allenai/allennlp/blob/master/allennlp/tests/data/token_indexers/elmo_indexer_test.py#L41).

**Comment by apmoore1** [comment]
Thanks for explaining this, it has been very helpful!
