### ISSUE TITLE
how to access to the whole embedding matrix?

### ISSUE THREAD

**Issue by junkyul** [allenai/allennlp#2719]
**System (please complete the following information):**
 - OS: [Ubuntu 16.04 Linux]
 - Python version: [e.g. 3.6.8]
 - AllenNLP version: [e.g. v0.8.2]
 - PyTorch version: 1.0.0

**Question**
* How can I access the tensor of (sparse) embedding matrix?

* I'm working on an entity linking task that trains entity embedding (with 0.6 million known entities) and input sentence encoder. At the prediction time for doing entity linking, I want to find the most probable entity from the entity embedding by comparing the score of all entity representations (inner product between entity representation and output of input sentence encoder). normally, a small number of candidates are provided as side information and finding the most probable entity becomes choosing the best one among 10~30 candidates; But I want to try comparing all entities when candidates are not available.

```
# currently, in reader class a list of candidates are in TextFields for sparsity
candidates_field = TextField(candidates_tokenized, self.wid_indexers)

# in forward(), only candidate submatrix is returned by
candidates_embedded = self.entity_embedder(candidates_field)

# is there any way like self.entity_embedder.get_weights() without passing candidates_field?
```

Thanks!

**Comment by matt-gardner** [comment]
You need to grab the `Embedder` out of the `BasicTextFieldEmbedder` that I assume you're using, then get the `weight` key from there.  So, something like this:

```python
self.entity_embedder: TextFieldEmbedder = ... 
entity_text_embedder = self.entity_embedder._token_embedders["entities"]  # or whatever key you used
entity_embedding_matrix = entity_embedding.weight
```

Note that if you actually have tokenized text for your candidates, this won't necessarily do what you've described.  E.g., if I have "Barack Obama" as an entity, this would get turned into two tokens, "Barack" and "Obama", which would each get their own embedding, and don't actually correspond to entities as you're expecting.  If instead you have exactly one unique token per candidate entity, as I believe you do from our conversation last week, then a `ListField[LabelField]` would be a better fit here on the input side.  Then you would just use an `Embedding` (instead of a `TextFieldEmbedder`) in your model, which would match better what you're doing, and just be simpler.  From there, you would recover the embedding matrix just with the last line of code I showed above.

**Comment by junkyul** [comment]
Thanks very much!
The entity id is the numeric id of the Wikipedia webpage (https://en.wikipedia.org/?curid=#id).
Indeed, ListField[LabelField] looks better fit in this use case; 

p.s. some of the minor bugs that I mentioned last week (like make-vocab loads all instance as a list) are fixed in the most recent version (I was using one of two release behind).
