### ISSUE TITLE
implement BERT as a module

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2758]
right now we only have BERT implemented as a TokenEmbedder, but it's far from obvious to me that that's how most people would want to use it. Like maybe I want to take the pretrained model and stick a classifier head on top of it. I don't think there's an easy way to do this right now in AllenNLP.

Or maybe I want to use the fully pretrained next-sentence-predictor. Right now I can't do that at all, except manually I guess.

this is basically #2233, which we closed but possibly shouldn't have.

**Comment by matt-gardner** [comment]
How do you use it as a module?  What are your inputs?  If you want to take the pretrained model and stick a classifier head on top of it, you can do exactly that with using it as a `TokenEmbedder`.  I'm not really sure what you're proposing.

**Comment by DeNeutoy** [comment]
I think this is really a discovery problem - e.g see how easy it is in huggingface to get either the representations attach a language model head. It's less than 50 lines of code.

https://github.com/huggingface/pytorch-pretrained-BERT#bert

The BERT `TokenEmbedder` is confusing because it obfuscates the process of converting to wordpieces and back, which is unintuitive. It's also difficult to add to a config file, because it requires adding unusual (and normally not required) items to the `text_field_embedder`, like the `indexer_to_embedder_map` etc.

**Comment by joelgrus** [comment]
maybe it is just a discovery problem. (to add a classification head on top of BERT you wouldn't need those other pieces, since you just want the last hidden state), or maybe we just need to implement a `BertClassifier` that has all the relevant pieces and just works out of the box.

**Comment by yucoian** [comment]
> How do you use it as a module? What are your inputs? If you want to take the pretrained model and stick a classifier head on top of it, you can do exactly that with using it as a `TokenEmbedder`. I'm not really sure what you're proposing.

As far as I know, No official docs for BertTokenEmbedder. Looking forward to it! Thanks.

**Comment by maxdel** [comment]
Fixed by #2787

**Comment by matt-gardner** [comment]
Yep, thanks.
