### ISSUE TITLE
supporting spacy's new tokenization

### ISSUE THREAD

**Issue by TalSchuster** [allenai/allennlp#2759]
> https://github.com/allenai/allennlp/blob/282f12aeef84771c046a34d039e1567cc137f01a/requirements.txt#L25

see https://github.com/explosion/spaCy/issues/3636.
I think that right now models that are using the default word splitter and were trained with spacy 2.0.18 and tested in a new environment with the recent version of spacy might tokenize the input differently.  
For example, the Constituency Parsing model.

**Comment by matt-gardner** [comment]
Hmm, yeah, I can see that that could be an issue.  Have you found any broken examples because of this?

**Comment by TalSchuster** [comment]
I haven't noticed any sentence that fails to parse because of that (though I haven't searched for one).

I experienced it locally when I used the parser to preprocessed some sentences and then wanted to use the results as inputs to another model. Unfortunately, it happened that for the later model I was working under a more up-to-date environment and experienced this inconsistency (noticed it because of the length of the input...).

Maybe it's nothing to be too worried about but worth noticing.

**Comment by DeNeutoy** [comment]
In all of our currently trained models, we actually use pre-tokenized input, so in some sense this only effects prediction time for _our_ currently trained models, which is less of a problem, as the tokenisation provided by Spacy may not have been canonical with respect to the trained model anyway. Unfortunately this is something I think you might have to manage independently, because it is disruptive to downstream users if we constantly have hard pins for all of our dependencies. Sorry about that!
