### ISSUE TITLE
Embed padded LabelFields

### ISSUE THREAD

**Issue by vin-ivar** [allenai/allennlp#2788]
**System:**
 - OS: OSX
 - Python version: 3.6.8
 - AllenNLP version: v0.8.3
 - PyTorch version: v1.0.0

**Question**
I know this isn't the most common use-case, but I was wondering if this was even possible without manually indexing the label vocabulary. The issue right now is that potential padding tokens are indexed as -1 for ```LabelField```s. Using a generic ```Embedding``` module makes embedding this very hacky, because -1 throws an ```IndexError```. 

The ideal scenario would be to allow unknown/pad labels to be indexed as a positive integer, and combine that with perhaps ```padding_index``` during embedding, so they'd be embedded as a vector of zeroes.

Is there an obvious way to do this that I'm just missing? Cheers.

**Comment by matt-gardner** [comment]
This is a detail we try to hide from users, because it's complicated.  But, you can get padding and UNK tokens for a LabelField by either changing the vocabulary namespace to something that doesn't end in "labels" or "tags", or by specifying [`non_padded_namespaces`](https://github.com/allenai/allennlp/blob/648a36f77db7e45784c047176074f98534c76636/allennlp/data/vocabulary.py#L170) in your vocabulary parameters (giving something that _doesn't_ include the namespace you're using for those labels).

**Comment by vin-ivar** [comment]
That works, thanks. It still doesn't appear to automatically index padded labels to 0, and a quick glance at the code seems to indicate that the -1 is hardcoded into ```empty_field``` - so I suppose you'd still need to manually flip -1s in the tensors to 0s?

**Comment by matt-gardner** [comment]
Ah, yeah, I think you're right, I forgot about that.  A simple `clamp` would do that for you.  It might be worth making the padding index configurable in `LabelField`.
