### ISSUE TITLE
Custom pretrained word2vec in seq2seq model 

### ISSUE THREAD

**Issue by YashSinha1996** [allenai/allennlp#2811]
**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.7.2
 - AllenNLP version: v0.8.3"
 - PyTorch version: 1.0.1.post2

**Question**
Newbie at AllenNLP. 

I have a custom pretrained word2vec model, which I trained using gensim. How can I initialise the vocabulary/embedding layer using it? I would like to use allennlp's data module too, if possible.

I saved the embeddings in text file and tried:
```
v = Vocabulary(pretrained_files={'tokens':'embedding/trained/orignal_c.text'}, only_include_pretrained_words=True)
```
But didn't work, gave me the same index for every word.
Also tried:
```
from allennlp.modules.token_embedders import Embedding
e = Embedding(271811, 200, pretrained_file='embedding/trained/orignal_c')
```
Any help regarding this will be appreciated. Thanks a lot!

**Comment by brendan-ai2** [comment]
I think the issue is that we're only adding tokens from `pretrained_files` when their namespace is already in the `counter`. See https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L536. This is likely a bug, but for now you can should be able to work around this by passing a `counter` with the namespace `tokens`. See here https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L153. @DeNeutoy, does this sound like a bug to you or am I misunderstanding the intention behind `Vocabulary`'s `pretrained_files` option?

**Comment by YashSinha1996** [comment]
Hi @brendan-ai2 , I had read docs and came to the same conclusion, but wasn't sure if I was missing something. 

I tried the workaround you mentioned but... :
```
v = Vocabulary(counter={"tokens":{}}, min_count={"tokens": 0},
               pretrained_files={'tokens':'embedding/trained/orignal_c'}, only_include_pretrained_words=True)

v.get_token_index('and') == v.get_token_index('is')
```
Gives "True". However, I did see the tqdm progressbar which read the file with the correct number of tokens. I tried both with `min_count` and without it, got the same result.

**Comment by brendan-ai2** [comment]
@matt-gardner, thanks for pointing that out! I think there's still an issue, however. Only [if the namespace is already in `counter`](https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L536) do we even check the `pretrained_files`. `min_pretrained_embeddings` doesn't come into play until after that. Compare:

```In [1]: from allennlp.data.vocabulary import Vocabulary
Deprecated cache directory found (/Users/brendanr/.allennlp/datasets).  Please remove this directory from your system to free up space.
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.

In [2]: Vocabulary(pretrained_files={'tokens':'allennlp/tests/fixtures/embeddings/glove.6B.100d.sample.txt.gz'}, only_include_pretrained_words=True, min_pretrained_embeddings={'tokens':10}).get_vocab_size()
Out[2]: 2

In [3]: Vocabulary(counter={'tokens': {'foo': 7}}, pretrained_files={'tokens':'allennlp/tests/fixtures/embeddings/glove.6B.100d.sample.txt.gz'}, only_include_pretrained_words=True, min_pretrained_embeddings={'tokens':10}).get_vocab_size()
100it [00:00, 130015.62it/s]
Out[3]: 12
```

@YashSinha1996, you should be able to use the second example to get unblocked. Sorry for the confusion!

**Comment by matt-gardner** [comment]
Hmm, yep, looks like you're right. Doing this from config files instead of writing your own scripts would be a lot easier, though, and wouldn't have run into these issues. The vocabulary isn't meant to be instantiated without a counter, so I'm still not sure I'd call this a bug. If we want to fix this, it should be by adding a new path to construct a vocabulary, I think, by giving an embedding file and using that as the vocab.

**Comment by YashSinha1996** [comment]
@brendan-ai2 , Thanks, that did the trick. Though, I am unstuck now, I will keep the issue open if you decide to fix this.

**Comment by kl2806** [comment]
@brendan-ai2 any updates?
