### ISSUE TITLE
Using the Biaffine Dependency parsing model with tokenized and tagged input

### ISSUE THREAD

**Issue by allanj** [allenai/allennlp#2863]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.6
 - AllenNLP version: 0.7.1
 - PyTorch version: 0.4.1

**Question**
I saw the way to parse dependency [here](https://allennlp.org/models) is:
```python
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz")
predictor.predict(
  sentence="If I bring 10 dollars tomorrow, can you buy me lunch?"
)
```
What if I want to parse an input sentence that is already tokenized and tagged? 
For example, I have a sentence: `['I', 'am', 'John']`, with POS tag sequence `['NN', 'VBP', 'NN']`. (As the parser in allen nlp will get higher performance with gold pos tag.)
What will be the usage to parse this sentence? seems I didn't find a clean tutorial to such use cases.

**Comment by DeNeutoy** [comment]
If you take a look at the predictor for the dependency parser, you will see that it is separated into two sections, one which creates an `Instance` from Json, and one which runs that `Instance` through the model.

https://github.com/allenai/allennlp/blob/master/allennlp/predictors/biaffine_dependency_parser.py#L102

https://github.com/allenai/allennlp/blob/master/allennlp/predictors/biaffine_dependency_parser.py#L117

So to use pre-specified pos-tags, you would need to do:

```
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz")

instance = predictor._dataset_reader.text_to_instance(tokens, pos_tags)

result = predictor.predict_instance(instance)

```

When you do this make sure that you are using UD style pos tags, not PTB ones, because the model is trained with UD ones. If you use PTB ones it will either break or fail catastrophically :)

**Comment by allanj** [comment]
Thanks a lot. It works.
