### ISSUE TITLE
No module named '_jsonnet'

### ISSUE THREAD

**Issue by justforyou16007** [allenai/allennlp#2886]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.6
 - AllenNLP version: I installed from master
 - PyTorch version:  1.1.0
 -CUDA version: cuda 10

**Question**
I install AllenNLP but I run $ allennlp test-install error occurred (in allennlp\tests\nn\initializers_test.py:9:):
 E   ModuleNotFoundError: No module named '_jsonnet'

**Comment by matt-gardner** [comment]
Sorry, we unfortunately do not support Windows 10 - none of us use it, and we won't be able to help you with this. If anyone using Windows sees this and has some ideas, feel free to chime in.

**Comment by joelgrus** [comment]
despite that test not passing (which it won't, because jsonnet is not available on windows), the main library itself is defensive against the non-presence of jsonnet, so I wouldn't worry about this specific test failure, and I would try to do whatever you want to try to do.

that said, as mattg points out, we don't officially support windows 10, so do that at your own risk.

**Comment by TheresaSchmidt** [comment]
@justforyou16007 
Have you found a solution?
Or is it just like joelgrus said and I can use AllenNLP even without jsonnet?
