### ISSUE TITLE
Question regarding the directionality of attended_arcs in biaffine_dependency_parser.py

### ISSUE THREAD

**Issue by Chung-I** [allenai/allennlp#2908]
**Question**
In biaffine dependency parser, we first compute the head of every word in the sentence, then predict the arc's label according the hypothesized unlabeled arcs.
Softmax is thus applied to the dimension representing heads to get the probability distribution of heads for each child:
![head_child](https://user-images.githubusercontent.com/14158535/58638354-2e952400-8327-11e9-8dd3-32c9115b669a.jpg)

In line 360, `softmax` is applied at the last dimension, which seems to suggest that the last dimension of `attended_arcs` represent heads:
https://github.com/allenai/allennlp/blob/26ac34991cb9139d3b99bd051e89f657e5c27ce4/allennlp/models/biaffine_dependency_parser.py#L360-L361
But the last dimension of  `attended_arcs` seems to represent children, as in line 236,237:
https://github.com/allenai/allennlp/blob/26ac34991cb9139d3b99bd051e89f657e5c27ce4/allennlp/models/biaffine_dependency_parser.py#L236-L237

 Will it make a bit more sense if the `attended_arcs ` were calculated like this, so that the last dimension of `attended_arcs` represents heads, thus compatible with the later applied `softmax` ?
` attended_arcs = self.arc_attention(child_arc_representation, head_arc_representation)`

Though it seems that two different ways of computing `attended_arcs`  doesn't affect the behavior of the final prediction. I'm just confused with the underlying semantic of `attended_arcs`.

Wondering where I got it wrong ><
Thanks a lot!

**Comment by kernelmachine** [comment]
@DeNeutoy can you take a look?

**Comment by DeNeutoy** [comment]
Hi @Chung-I,

This is a good question. The answer basically comes down to the fact that, because we are learning the parameters of the `arc_attention` module, it doesn't matter which way around the `head_arc_representation` and `child_arc_representation` go.

You might find it easier to think of the attended_arcs just as "directed pairwise scores between words". Hopefully it now makes sense that the whether we have the matrix `M` or matrix `M^T` (transposed) doesn't actually matter. I do see what you mean that it might make sense to have the argument the other way around for readability though, but unfortunately we aren't going to be able to change this, because it would break the models people are currently using. 

Hopefully that's a good enough explanation! Let me know if anything is still unclear.

**Comment by Chung-I** [comment]
That was clear ! Thanks for the thorough explanation :-)
