### ISSUE TITLE
AttributeError: 'Params' object has no attribute 'count_vocab_items'

### ISSUE THREAD

**Issue by Safranchik** [allenai/allennlp#2924]
- OSX Mojave
 - Python 3.7.2
 - AllenNLP v0.8.4

**Question**
Hello! I am attempting to merge the output of a generic Dataset reader with some metadata. In order to do this, I created a wrapper class weak_label_reader.py that calls another DatasetReader as a subroutine (with the goal in mind of adding the metadata to the already existing instances).

So far, this wrapper class only calls the read method of the subreader (in this case, a custom reader called CDRDiseaseDatasetReader gets instantiated). However, I am getting AttributeError: 'Params' object has no attribute 'count_vocab_items', which hints at the output of the subreader having a  wrong format. I have tried tracing this bug by looking at differences in the output of the subreader and the wrapper reader, but nothing seems to indicate that they are different.

Here's a screenshot of the entire wrapper class, that simply instantiates and calls the subreader. You may assume that the subreader works perfectly fine, and outputs the correct instances. I have successfully been able to read data from CDRDiseaseDatasetReader using a config file, but this simple wrapper seems to wreak havoc.

![Screen Shot 2019-06-04 at 7 40 10 PM](https://user-images.githubusercontent.com/23159096/58920538-a9cc5080-8700-11e9-8844-16353de14d94.png)

The Stack trace is the following:

![Screen Shot 2019-06-04 at 7 42 25 PM](https://user-images.githubusercontent.com/23159096/58920634-252e0200-8701-11e9-9c1b-2849349ccb76.png)

And the dataset reading component of the configuration file is as follows:

![image](https://user-images.githubusercontent.com/23159096/58921792-404f4080-8706-11e9-8902-a715e37f33a9.png)

Thank you so much for your time!

**Comment by kl2806** [comment]
Could you make a test similar to this: https://github.com/allenai/allennlp/blob/master/allennlp/tests/data/dataset_readers/sequence_tagging_test.py#L10 that tests that the instances for the wrapper reader is what you would expect?

It would be helpful if you post the code for the subreader. If you are setting `lazy=False` always and just return a list of `Instances` in the subreader `read` method then you don't need the `__iter__()` there. If you want it to also have the `lazy=True` option then you would want to use `yield` instead of `return`.

**Comment by Safranchik** [comment]
I changed the subreader to SnliReader, to try to isolate whether this is an issue with my subreader or in general. (the config file is the same)

![image](https://user-images.githubusercontent.com/23159096/58962511-53e7bf00-8779-11e9-9318-c7834b80789f.png)

The new error I'm getting is very similar to the previous one.

![image](https://user-images.githubusercontent.com/23159096/58962590-8ee9f280-8779-11e9-9b40-54689304e5ea.png)

Could it be that I'm wrapping readers the wrong way?

**Comment by kl2806** [comment]
It looks like you are using the `lazy=False`, so you don't need to use `yield` here. I mentioned using that for lazy iterators, sorry if that was unclear. Can you try just doing `return self.subreader.read(file_path)`?

Alternatively, since your `CDRDiseaseDatasetReader` is custom, then you could just add the metadata in that reader? There is a `MetadataField` that you could instantiate inside the `text_to_instance` method.

**Comment by Safranchik** [comment]
I changed the method return as you suggested.  The only difference is that now it throws "AttributeError: 'list' object has no attribute 'count_vocab_items'" again.

![image](https://user-images.githubusercontent.com/23159096/58983937-d8e8cd80-87a5-11e9-8f4e-fe81b29b0455.png)

The reason why I am attempting to use a wrapper class instead of modifying the custom reader is that we want users to leverage any existing Readers by simply passing their reference as a parameter to our 'weak-label' reader. CDRDiseaseDatasetReader is just the reader we are working with right now, but we will also be using others such as the Snli.

Just to be sure I'm not going crazy, the WeakLabelDatasetReader should just be redirecting the read method of the subreader without interference, right? The DatasetReader.read method simply redicrects the internal ._read method.

![image](https://user-images.githubusercontent.com/23159096/58984218-78a65b80-87a6-11e9-999e-a5867c6d2b26.png)


Once again, thank you so much for your help!

**Comment by joelgrus** [comment]
your original problem is likely caused by not using type annotations on your dataset reader.

the code needs the type annotations to understand how to turn your json into actual objects. But you provided no type annotation for `token_indexers`, which means that the allennlp code doesn't know how to turn that JSON into `TokenIndexer` objects, which means that your "token indexers" are actually `Params` objects (this should probably raise an error), which leads to the error you saw.

**Comment by Safranchik** [comment]
That was it! Thank you!

**Comment by ruleGreen** [comment]
Sorry, I am confused by type annotation on dataset reader. I encountered similiar problem which is str object does not have attri count_vocab_item, and after I insert two lines code in vocabulary.py 

`
for instance in Tqdm.tqdm(instances):
            print(instance)
for instance in Tqdm.tqdm(instances):
            instance.count_vocab_items(namespace_token_counts)
`

then the error gone but another appears,

str object has no attri 'index_fields'

**Comment by matt-gardner** [comment]
@ruleGreen it's easier for us to help you if you open a new issue.  We'll need more detail about what exactly you're doing, with code and stack traces.
