### ISSUE TITLE
Semantic parsing on Freebase/Wikidata (e.g. WebQuestions, GraphQuestions, SimpleQuestions)

### ISSUE THREAD

**Issue by nilesh-c** [allenai/allennlp#2936]
Hey all,

I'm writing a weakly supervised semantic parser for knowledge graphs like Freebase/Wikidata/DBpedia, with a focus on complex multi-hop questions with aggregators, logical/arithmetic operations etc. and a LISP-like variable-free grammar (like the one used in the [Dialog-to-Action](https://papers.nips.cc/paper/7558-dialog-to-action-conversational-question-answering-over-a-large-scale-knowledge-base.pdf) paper for conversational QA).

Currently, there doesn't seem to be anything similar in allennlp, so I was wondering if adding this stuff would be interesting for you guys too.

Here's a few things that my project involves:
* A large search/execution space
* A structured decoder along the lines of [Stack-LSTM](https://arxiv.org/abs/1711.05066) - transition functions
* MML based re-ranking (maybe something like a [generative ranker](https://www.aclweb.org/anthology/K18-1035))
* A custom DomainLanguage that parses into something SPARQL-friendly that gets executed on a backend triple store by an executor. Not sure if the parsimonious approach would've worked better; I wrote a somewhat hacky DomainLanguage subclass because my language is LISP-like, but I want off-python DB execution whenever possible (e.g. do not perform joins in python). So the context class is basically a wrapper for a querying API.
* Efficient way to update the grammar from the executor?
* Another idea would be to store the graph in a sparse cupy/scipy matrix and use cupy matrix-ops to execute the logical forms - this could make it possible to execute the search procedures/graph traversals on GPUs.

And thanks so much for this awesome project. :)

Cheers!

**Comment by matt-gardner** [comment]
There is stuff similar to this in allennlp: https://www.aclweb.org/anthology/N19-1273 (the code for that paper was all done in allennlp, and it's in the process of getting merged).  We'd definitely be interested in seeing what you come up with when you have something working.  If you have specific questions as you're doing it, let us know.

As for a "context", you might not need one at all, depending on your application - the `DomainLanguage` can just query the DB when it tries to execute the logical form.  The functions in a `DomainLanguage` are all intended to be single python functions that get executed independently, and we build a grammar on top of them, but you could imagine instead having them recursively build up a SPARQL query that then gets sent to the DB in the main (overridden) call to `execute`.  Does this make sense?

I'm not sure what you mean by an "efficient way to update the grammar from the executor".

If you're able to put all of the query operations on GPUs, then yes, that might help things, except that our execution code is currently not batched at all, so you might not see much benefit from it.

I'm going to close this issue, but feel free to keep commenting, or open a new issue if you have separate questions.

**Comment by nilesh-c** [comment]
Hey @matt-gardner thanks for the quick response! Much appreciated :)

The iterative search paper looks cool, looking forward to the merged code.

Re `DomainLanguage` recursively building SPARQL and overriding `execute` - that's exactly what I'm doing, but wasn't sure if it's supposed to be used like that. Seems like `DomainLanguage` more or less completely replaces the world-executor stuff. Brilliant. :)

I've got a couple questions:

* This might be a silly question, but I'm trying to understand how one would build a grammar from such a `DomainLanguage` instance. In `nlvr_semantic_parser`: https://github.com/allenai/allennlp/blob/c0f44f74ab5b7505bc6a8ca18ce05e9afaf67699/allennlp/models/semantic_parsing/nlvr/nlvr_semantic_parser.py#L173-L175
I can see the initial state for the decoder is created with this function. Then it is passed to a trainer such as the `MaximumMarginalLikelihood` which takes a `TransitionFunction`, and maybe performs a beam search which basically takes the statelet and iterates using it to find logical forms. <br>
My confusion is here: since `GrammarStatelet` does not have access (or a callback etc.) to the `DomainLanguage` instance, how can it be updated without having the whole state-action-graph (so, the entire KG) inside itself?

* Do you typically create one `DomainLanguage` instance per logical form/query instance?

**Comment by matt-gardner** [comment]
1. The key line is here: https://github.com/allenai/allennlp/blob/c0f44f74ab5b7505bc6a8ca18ce05e9afaf67699/allennlp/models/semantic_parsing/nlvr/nlvr_semantic_parser.py#L176
This is how the `GrammarStatelet` interacts with the language; it's given the entire set of valid productions up front.  I can imagine many use cases where this is not ideal, but it has worked for us so far.  If you have a huge set of possible productions, and you only use a small amount of them for any given search through the grammar, then there are likely better ways of representing this.  If you have some more detail about your approach and the problems that you're running into using what you have, I can try to give some suggestions on ways to get around the problems.  (E.g., we have a `LambdaGrammarStatelet` that modifies some aspects of the grammar on the fly, and there are other things you can do at runtime to prune the space.)

2. That depends entirely on the domain.  Almost always we create one `DomainLanguage` object per `Instance`, because we deal with problems where some of the productions in the grammar depend on things inside of the `Instance` (e.g., what terminal productions are allowed), or the execution depends on the `Instance`.  But there are also many cases where you don't need this, and you could get away with a single `DomainLanguage` object for all `Instances`.
