### ISSUE TITLE
Allennlp in production - Exporting the pipeline to torch script

### ISSUE THREAD

**Issue by sai-prasanna** [allenai/allennlp#2937]
@joelgrus  You replied on a thread I was following in hacker news about exploring production features of pytorch 1.0.

> AllenNLP dev here. We're going to do a "PyTorch 1.0" release of AllenNLP next week, and then after that we're planning to investigate how to incorporate the new "production" aspects.
https://news.ycombinator.com/item?id=18683758

Could we change most of the modules in the pipeline to be written in subset of python that torch jit script supports? 

Or do you have anything on your mind on how to do this ?

**Comment by sai-prasanna** [comment]
@joelgrus Any suggestions on this?

**Comment by joelgrus** [comment]
the first time I looked at this, allennlp had a lot of features that were not compatible with torchscript (e.g. models return dicts). since then they've made a bunch of changes. right now I'm working on upgrading allennlp to pytorch 1.2.0, after that it might make sense to revisit this, although it's probably not one of my top priorities.

contributions welcome.

**Comment by sai-prasanna** [comment]
@matt-gardner @brendan-ai2 @DeNeutoy I would like to work on this. I have started studying pytext. It seems they have a jitted version of Vocabulary and token indexer etc. But I'm in intial stages of this.

Any thoughts, suggestions on this?
