### ISSUE TITLE
Make forward_on_instances batched

### ISSUE THREAD

**Issue by codedecde** [allenai/allennlp#2958]
**Is your feature request related to a problem? Please describe.**
Currently forward_on_instances simply treats the entire list of instances as a one batch.
That potentially leads to out of memory issues.

**Describe the solution you'd like**
Currently, the entire list is treated as a batch. 
https://github.com/allenai/allennlp/blob/1b656dd759427b44c82fe180aef8da52659ce87c/allennlp/models/model.py#L147

Instead of that, can potentially 
a) Use a BasicIterator
b) Manually split the instances
The existing behaviour can be default if no batch size is described.

**Comment by matt-gardner** [comment]
I think we don't want to put the complexity of worrying about batch size, etc., into the `Model`.  This seems more appropriate for the caller to worry about somewhere.  If you want to be using an iterator, you can just call `forward`, not `forward_on_instances`.

**Comment by DeNeutoy** [comment]
Yep, this is straightforward to achieve outside the library by making lists of appropriately sized batches.

**Comment by sethah** [comment]
So the consequence here for the `Model` class is the difference between:

```python
instances: List[Instance] = ...
batch_size = 16
grouped_instances = [instances[i:i+batch_size] for i in range(0, len(instances), batch_size)]
grouped_predictions = [model.forward_on_instances(batch) for batch in grouped_instances]
predictions = [item for sublist in grouped_predictions for item in sublist]  # flatten list
```
and (under proposed solution)
```python
instances: List[Instance] = ...
batch_size = 16
predictions = model.forward_on_instances(instances, batch_size=batch_size)
```
correct?

A problem I have is that the `Predictor` class relies on this method. So, if I want to get a batch of predictions I can't just use `predictor.predict_batch_instance(instances)`.

I am sure I don't have all the details, but I'd be interested to hear more on why this should not be included functionality. Compatibility should be fine by making the method default to using the entire list as a single batch. I think the added code above is enough to warrant adding such a functionality on its own, but I also think `predictor.predict_batch_instance` is misleading since it only works for small batch sizes. To me, such a method should accept an arbitrarily long list of instances and return predictions for those. 

@matt-gardner @DeNeutoy Your thoughts would be appreciated, thanks!

**Comment by matt-gardner** [comment]
The high-level thought here is that we really don't want the `Model` or `Predictor` to have to worry about too many things that aren't relevant to the class.  The more we add these convenience methods or push more things into `forward_on_instance`, the closer we get to having an entire training loop inside `Model`, which isn't great.

If you're talking about having an arbitrarily long list of things passed to `predictor.predict_batch_instance`, you really want a `DataIterator` to live inside the predictor, so you can batch things intelligently, and you quickly get out of the scope of a `Predictor` object.  The right solution for this use case is to have a smarter `predict` command that uses the same data pipeline as the trainer uses (see #2576).

**Comment by sethah** [comment]
Ok, that helps, thank you. I definitely understand the separation of concerns, but by even providing a `predict_batch_instance` method you have already implicitly made a decision about how to batch instances (treat them as a single batch) and that decision doesn't work well in _most_ cases. The documentation for `Predictor` says it's for "making predictions in bulk" which, considering the issues here, is somewhat misleading.

The concerns about this getting too involved/complex make a lot of sense. The smarter `predict` command will help, but if I understand correctly directly using the `Predictor` class will still have these issues. If this is a total "won't-fix" then maybe just adding some clarification to the documentation could be helpful. At any rate, thanks for pointing me to #2576 - I'll keep an eye on that one.

**Comment by matt-gardner** [comment]
Yeah, a PR to clarify the documentation would be great, making it clear that it will let you do batched prediction, but that you have to provide your own batching.
