### ISSUE TITLE
How can I use Elmo Embedder with copynet_seq2seq?

### ISSUE THREAD

**Issue by abaheti95** [allenai/allennlp#2976]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.6
 - AllenNLP version: v0.8.4
 - PyTorch version: (if you installed it yourself)

**Question**
How can I use Elmo Embedder with copynet_seq2seq?

I received this configuration error when I tried to use `ELMoTokenCharactersIndexer()` instead of `SingleIdTokenIndexer()` 
```
allennlp.common.checks.ConfigurationError: "CopyNetDatasetReader expects 'source_token_indexers' to contain a 'single_id' token indexer called 'tokens'."
```

Will this provision be added in the future? Is there a way I can tweak the code to add this functionality?

**Comment by DeNeutoy** [comment]
This is a little complicated: 

The copynet model must have a single_id token indexer, because it needs a vocabulary to use when copying tokens.

You should be able to use:

```
  "token_indexers": {
    "tokens": {
      "type": "single_id",
      "lowercase_tokens": true
    },
    "elmo": {
      "type": "elmo_characters"
    }
  }
```

and then in your text_field_embedder, just don't have an embedder for the `tokens` field. To do this, you need to pass the `allow_unmatched_keys=True` flag to the textfield_embedder: https://github.com/allenai/allennlp/blob/459633c9474de1dfca0976629f16beeb92e83d30/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L44


I think that should work - this way, you are using elmo representations to encode your input, but you still have a token level vocabulary to copy from when decoding.

**Comment by abaheti95** [comment]
Could you tell me how can I achieve this in native python code?

**Comment by abaheti95** [comment]
Figured it out. 
```python
    reader = CopyNetDatasetReader(target_namespace='target_tokens',
        source_token_indexers={'tokens': SingleIdTokenIndexer(lowercase_tokens=True), 'elmo': ELMoTokenCharactersIndexer()})
    ...
    source_embedder = BasicTextFieldEmbedder({"elmo": elmo_embedding}, allow_unmatched_keys=True)
```
