### ISSUE TITLE
Does the Pre-trained NER Model Support Different Tokenizations?

### ISSUE THREAD

**Issue by HungChau** [allenai/allennlp#2981]
I am evaluating the ner model's performance. I've experienced an issue with the way the pre-trained ner model tokenizes sentences, which is different with CONLL 2003 format.

For example: "Fischler proposed EU-wide measures after reports from Britain."
- Tokens from the model:
['Fischler',
 'proposed',
 'EU',
 '-',
 'wide',
 'measures',
 'after',
 'reports',
 'from',
 'Britain',
 '.']

- Tokens from CONLL 2003:
Fischler JJR B-NP B-PER
proposed VBN I-NP O
EU-wide NNP I-NP B-MISC
measures VBZ B-VP O
after IN B-PP O
reports NNS B-NP O
from IN B-PP O
Britain NNP B-NP B-LOC
. . O O

Are there any ways to choose different ways to tokenize a sentence or can the model accept a input as a list of tokens instead of a sentence?

Thanks!

**Comment by DeNeutoy** [comment]
Hi,

This is quite easy to do - you need to subclass the predictor:

https://github.com/allenai/allennlp/blob/master/allennlp/predictors/sentence_tagger.py#L27

And just refactor it to have `_json_to_instance` take a list of tokens rather than a string. You can then run `allennlp evaluate --predictor <your-predictor-name> --include-package python.path.to.package` which will hopefully give you the functionality that you are looking for. Can you try that and see if it helps?

**Comment by HungChau** [comment]
I am able to modify it now. 

Thanks very much!
