### ISSUE TITLE
"BbIiOo_~" tagging scheme

### ISSUE THREAD

**Issue by danielhers** [allenai/allennlp#2986]
The current tagging schemes in the CRF decoder are "BIO", "IOB1", "BIOUL", and "BMES": https://github.com/allenai/allennlp/blob/master/allennlp/modules/conditional_random_field.py#L12-L149

For the "BbIiOo_~"  scheme used in [STREUSLE](https://github.com/nert-nlp/streusle) lextags (column 19 in the conllulex format), the constraints would follow the regex `^(O|B(o|b(i[_~])+|I[_~])*(I[_~])+)+$`. I.e.:

- START must be followed by `O` or `B`
- END must follow `O`, `I_`, or `I~`
- `B`, `o` must be followed by `o`, `b`, `I_`, or `I~`
- `b` must be followed by `i_` or `i~`
- `O` must be followed by `O`, `B`, or END
- `I_`, `I~` must NOT be followed by `i_` or `i~`
- `i_`, `i~` must NOT be followed by `O`, `B`, or END

(Also: for STREUSLE, `I_` and `i_` must not have an entity (supersense) type.)

**Comment by DeNeutoy** [comment]
Hi Daniel,

Thanks for the issue (and I've very much enjoyed reading some of your work, particularly UCCA and your dedication to producing software from your research, so thank you). I think this tagging scheme might be quite niche - however, if you integrate it into a model for STREUSLE, we'd love to link out to it or possibly consider integrating it into the library, if it is demonstrated to have some wide appeal. Does that sound reasonable?

If you are asking how to generate the transitions for this scheme, the CRF module takes as input tuples describing the allowed transitions between tags - so you could simply pass this directly.

**Comment by danielhers** [comment]
Thanks, @DeNeutoy!
I'll try implementing it in my own model, and update this thread.

**Comment by nelson-liu** [comment]
I'm looking into building a model for STREUSLE. It's more-or-less a simple CRF tagger that uses constrained decoding with this tagging scheme. Given the perceived reluctance to add the tagging scheme to the library, how should I go about making the model (with an eye toward submitting a PR for it upstream eventually)

I could subclass the CRFTagger and put this tagging scheme in there instead of calling `allowed_transitions` (since BIO and friends will never be an option), but there's probably a better way---thoughts?

@DeNeutoy

**Comment by DeNeutoy** [comment]
Sounds like a good way to me! Or just copy and paste instead of subclassing it.

**Comment by danielhers** [comment]
Implemented in https://github.com/nelson-liu/streusle-tagger/blob/master/streusle_tagger/models/streusle_tagger.py. Thanks, @nelson-liu!
