### ISSUE TITLE
AllenNLP returns blank results for few questions with same format in same document

### ISSUE THREAD

**Issue by UdaykumarAngadi** [allenai/allennlp#2988]
Hi ,

AllenNLP wikitable semantic parser is not able to answer few questions or giving blank answers for generic questions but it is giving answers for other specific answers asked from a table for the same document.

The document,table and text alignment remains same but answers are blank sometimes, Please suggest on how to resolve this type of scenarios.

Regards
Uday

**Comment by DeNeutoy** [comment]
Could you give an example of what you mean? You can link to the allennlp demo predictions (as the links have a permalink id attached to them). At the moment i'm not quite sure on what the problem is.

**Comment by UdaykumarAngadi** [comment]
Hi DeNeutoy,

Thanks for quick reply.
Let me explain issue with an example,

I am using AllenNLP Semantic Parser predictor.

table structure
Answer(text)   Question(text)
Answer1    what is total no of students in location1 (question with specific keywords)
Answer2    what is  total no of students in school Globallly(Generic question)
Answer3    Question3_text
Answer4    Question4_text

Scenario1: 
What is Answer for Question what is total no of students in location1 ? ( this question is more specific)
Answer :  1232323  (Correct answer)

Scenario2:
What is Answer for Question what is  total no of students in school Globallly ? ( this question is more generic )

Answer is blank

No changes in table, document format but some answers are getting answered and some are not.

Please suggest on this issue.

Regards
Uday.

**Comment by matt-gardner** [comment]
A few somewhat unrelated points:

- The parser does not have perfect accuracy; it's not surprising that it gets some questions right and other questions wrong.
- I'd also recommend looking at the logical form that's produced, instead of just the answer, and see if it looks like it's correct.
- From the table structure that you described, it looks like this kind of compositional parser is _way_ more complicated than you need.
- The pretrained model that you're using is also not particularly good; it's more of a proof-of-concept for that style of model.  We have a much better model whose code just got merged (#2764), and @pdasigi is currently re-training it with the new code, so a new model should be available soon.

**Comment by UdaykumarAngadi** [comment]
@matt-gardner 

Thanks for your reply. Your reply answered most of my queries and doubts.

Please share on tentative date for next model release.

Once again, thanks a lot for reply.

**Comment by UdaykumarAngadi** [comment]
Hi ,

For the asked question allennlp returning question itself,

Eg:

What is count of Total students in school from school xyz?

Answer:   count of Total students in school

Please help on how to resolve this problem.


Is it resolved by using lemmatization ?
 
Please suggest.

Regards
Uday.

**Comment by matt-gardner** [comment]
Just giving the question and answer here is not informative at all - in order to provide any help, I need to see the exact table that you're talking about, and the _logical form_ that's produced, not the answer.  But even I saw that, I'm pretty sure the answer will be "the model can only do what it was trained to do", and it wasn't trained to answer the kinds of things you're asking it (or work with the tables you're giving it).
