### ISSUE TITLE
Add option to specify whether to save training states

### ISSUE THREAD

**Issue by abhishek0318** [allenai/allennlp#2992]
**Is your feature request related to a problem? Please describe.**
Currently, Trainer saves optimiser state after each epoch and there is no option to prevent this behaviour. Not saving optimiser state can be useful when there are disk space constraints. 

**Describe the solution you'd like**
An argument `training_states_to_keep` in Trainer can fix this issue. Default value of this can be ['metric_tracker', 'optimizer', 'batch_num_total', 'learning_rate_scheduler', 'momentum_scheduler'].

**Describe alternatives you've considered**
Another alternative can be to have a boolean argument `save_training_state` (default True) in the Trainer class. If `save_training_state` is False, none of the training state is saved.

**Additional context**
Also why is training_state saved every epoch in different file when the default behaviour is to restore only last training state?

**Comment by DeNeutoy** [comment]
Hi,

We won't fix this because you can already limit the number of models (and corresponding training states that you save) and in general not many people will want to save only part of a training state, and it makes it hard to deal with cases in which the training state is not complete when it is re-loaded. 

However, you could write a script which watches a training directory and removes the training states if you don't need them - this would be quite straightforward.

Training state is saved every epoch as it is possible to restore from a previous epoch rather than the last one, although admittedly not many people do this.
