### ISSUE TITLE
Prerequisites for learning allennlp from the beginning

### ISSUE THREAD

**Issue by Bipin8469** [allenai/allennlp#2995]
**Question**
I want to learn complete allennlp so, can you tell me what other subjects I need to study before starting with allennlp.
thank you.

**Comment by matt-gardner** [comment]
This is an incredibly hard question for us to answer, because we have no idea what you already know.  Do you have a computer science background?  An NLP background?  A linguistics background?  Generally, if you want to know what's going on in allennlp, you should:

- Understand python programming.  Best if you understand computer science concepts like polymorphism, dependency injection, many others.
- Ideally, also understand pytorch / auto-differentiation.
- Have a basic understanding of how we do machine learning with text.
- Ideally, be already familiar with common deep learning paradigms for NLP.

We've designed this library to be most useful for someone who already knows how to write good code and who already knows NLP, to help them do research quickly and methodically.  We're currently writing a "course" with a lot more introductory material for someone who doesn't meet the "ideally" conditions above, but I don't have an estimate for when that will be available (we've committed internally to releasing something by the end of September; hopefully an initial version will be available sooner than that).

**Comment by Bipin8469** [comment]
I'm from a computer science background and have knowledge of computer science concepts only.
thank you for your answer
