### ISSUE TITLE
Keep the order of concatenated output in `BasicTextFieldEmbedder`

### ISSUE THREAD

**Issue by guoquan** [allenai/allennlp#3012]
I am trying to retrieve separated representation from different embedders nested in `TextFieldEmbedder`.

Can we keep the order of the concatenated output as the order of the keys, if `token_embedders` is provided as an `OrderedDict`? It would be viable just to remove this [`sorted()`](https://github.com/allenai/allennlp/blob/master/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L96). Then I can split the output by another module.

So what is the purpose of `sorted()` here?

I was also thinking about could we have a `dict` output for TextFieldEmbedder. But it seems the only `dict` structure thing allow here is the `text_field_input`. We always need to return `Tensor` from `forward()` method. Is that the case?

**Comment by matt-gardner** [comment]
If you want separate representations out of different token embedders, you should probably just not use a `TextFieldEmbedder`.  There's no reason that you need to use an abstraction if it doesn't fit your needs.

The `sorted()` is in there because the library was started before all dictionaries in CPython were ordered, so we needed the sort to maintain ordering.  Given that we now require python 3.6, we can probably remove it, but it isn't hurting anything.

There is no way that we would change `TextFieldEmbedder` to have a dictionary return type, because that would break a whole lot of code, and the entire point of the abstraction (which is that it returns to you a single vector per token in your input).

**Comment by guoquan** [comment]
That makes sense. Ordering is necessary here and I believe it would be better to keep `sorted()` since we should not rely on an implementation detail of certain version of CPython.

For me, I just did not know it would be safe *NOT* to use `TextFieldEmbedder`.

Some additional questioning (and complaint):

Should it be using other `Embedder`s with `TextField`? Or needs to replace `TextField` with `SequenceField`?

Is it `TextField` and `TextFieldEmbedder` add values to the `SequenceField` and `Embedder`s only in the way to support the `dict`-like convention? To me, it really destroys the beauty of interface consistency :( , with a lot of additional works there.

**Comment by matt-gardner** [comment]
I don't really understand your question. It's hard to give advice about how exactly you should structure your code without knowing more detail about what you are trying to do. If you can give me information about what your inputs are and how you want to model them, I would be able to help you better.

**Comment by guoquan** [comment]
It is hard to say what exact situation. We are working on a framework, on the top of AllenNLP, and wanted to leave the freedom to the users.
Let's imagine if I want to compare the difference between embeddings from `OpenAITransformaerEmbedder` and `BertEmbedder`. Then it would need the same `TextField`, attached with both embedders. But it would be a problem to really split them in the current setting.

Because I did not review what is implemented in `TextField` over `SequenceField`. I do not know if it would be safe just do the replacement. I appreciate it if you would give some suggestion!

**Comment by matt-gardner** [comment]
If you want to have both GPT embeddings and BERT embeddings in the same code, the easiest way to do that is probably to construct two `TextFields` and two `TextFieldEmbedders`, one for GPT and one for BERT, because the input data will need to be different for each of them, also.  If you want to have both GPT embeddings and BERT embeddings in *different* runs of the same code, this is exactly what `TextFields` and such were designed for, and you don't need to change anything from how the tutorials recommend you set things up.

**Comment by guoquan** [comment]
Still a bad example because of the difference in the input. But you get me a great point. I will need to have a `TextField` for each different encoding for the same reason. Thank you!
Cheers!
