### ISSUE TITLE
Allow Attention class to only pass in matrix & learn vector

### ISSUE THREAD

**Issue by EmilyAlsentzer** [allenai/allennlp#3018]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to perform attention over the hidden states of the encoder without having a specific vector to use in the score function. Typically, attention is performed by calculating the score between an encoder state and decoder state or between a question and passage representation. However, you can also initialize a vector and calculate a score between the initialized vector and the encoder hidden states. The Attention class right now does not easily support that.

**Describe the solution you'd like**
Modify the Attention class to only optionally pass in a vector. If one is not passed in then, it initializes a vector of size hidden state. 

**Describe alternatives you've considered**
Right now I'm initializing the vector outside of the Attention class and passing it as a parameter, but I don't think this is as clean as encapsulating this inside the class.

**Comment by matt-gardner** [comment]
The core idea behind our module abstractions is that they encapsulate a consistent tensor input / output spec.  For `Attention`, it's `vector: (batch_size, embedding_dim), matrix: (batch_size, num_rows, embedding_dim)` --> `attention: (batch_size, num_rows)`.  If you make the inputs optional for only some subclasses of `Attention`, you break the ability to substitute any subclass that implements the same input / output spec, and the whole point of the abstraction falls apart.

I do agree that a module like you describe is a useful thing to have, it's just not what we call an `Attention`.  If you want a single module for it, it'd be pretty easy to write it.

**Comment by EmilyAlsentzer** [comment]
Completely understand the importance of a consistent tenor input/output spec, but I'm suggesting that any subclass of Attention should be able to work like this. For instance, `DotProductAttention`, `BilinearAttention`, etc. would all work the same - the only difference is that there would be a learned vector for calculating the score rather than passing it in as a parameter. I'm a bit confused how this breaks the Attention abstraction. I could definitely write my own module, but I'd like to be able to reuse all of the functionality from the child classes of `Attention`. Is there a better way to do this? Thanks!

**Comment by matt-gardner** [comment]
Consider using this in a model:

```python
def forward(inputs):
    ...
    query_vector = some_encoder(word_embeddings)
    retrieved_sentence_vectors = TimeDistributed(some_encoder)(retrieved_embeddings)
    retrieved_sentence_weights = attention(query_vector, retrieved_sentence_vectors)
```

Conceptually, this is fundamentally different from scoring the retrieved sentences using some arbitrary vector, and if I tried to instantiate a generic "scorer" for the `attention` here, it would break my code.

You're right that the concepts are related, but we try to not have each individual abstraction do too much.  We split out LSTMs into two separate abstractions for their two different uses (whether you just keep the encoding of the final word or every word), because the things you interchange those uses with are different.

The same applies here.  What you describe is a "scorer", that takes a tensor with a final embedding dimension and reduces that dimension to a single score.  You could use an attention-based mechanism for that, or a linear layer, or an MLP, or a bunch of other things.  But the set of substitutions there is very different from the set of substitutions for our `Attention` abstraction.  We don't currently have a `Scorer` abstraction, but if you wanted one it wouldn't be hard to add, or to have an `AttentionScorer` as a concrete instantiation of it:

```python
class AttentionScorer(torch.nn.Module):
    def __init__(self, vector_dim: int, attention: Attention):
        ...
        self.vector = torch.nn.Parameter(...)
        self.attention = attention
    def forward(self, matrix_to_score: torch.Tensor) -> torch.Tensor:
        return self.attention(self.vector, matrix_to_score)
```

**Comment by EmilyAlsentzer** [comment]
Got it, thanks for describing the motivation behind the library design - very helpful.
