### ISSUE TITLE
Train elmo embeddings within pytorch

### ISSUE THREAD

**Issue by aniketSanap** [allenai/allennlp#3136]
- OS: Google colab
 - Python version: 3.6
 - AllenNLP version: 0.8.4

So I am new to allennlp and want to train my elmo embeddings on a custom dataset. I have followed this tutorial:

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md

and got it to work. The problem I am facing is integrating this with pytorch. The base code which I am using is from the official allennlp tutorial (https://allennlp.org/tutorials). But I am not able to figure out how to do this using python or how to use my trained model using python.

The code with `allennlp.modules.token_embedders.ElmoTokenEmbedder` works very well but I can't change the embeddings. I have tried using `allennlp.modules.elmo.Elmo` but can't seem to get it to work.

My code looks like this:

```
class LstmTagger(Model):
    def __init__(self,
                 encoder: Seq2SeqEncoder,
                 vocab: Vocabulary) -> None:
        super().__init__(vocab)
        options_file = "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
        weight_file = "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"
        self.elmo = Elmo(options_file, weight_file, 1, dropout=0)
        self.word_embeddings = BasicTextFieldEmbedder({"tokens": self.elmo})
        self.encoder = encoder
        self.hidden2tag = torch.nn.Linear(in_features=encoder.get_output_dim(),
                                          out_features=vocab.get_vocab_size('labels'))
        self.accuracy = CategoricalAccuracy()
        # self.f1_score = F1Measure(positive_label=1)
        self.sentence_correct = 0
        self.sentence_total = 0
        self.y_preds = None
        self.y_trues = None`

    def forward(self,
                sentence: Dict[str, torch.Tensor],
                labels: torch.Tensor = None) -> Dict[str, torch.Tensor]:
        mask = get_text_field_mask(sentence)
        embeddings = self.word_embeddings(sentence)
        encoder_out = self.encoder(embeddings, mask)
        tag_logits = self.hidden2tag(encoder_out)
        output = {"tag_logits": tag_logits}
        if labels is not None:
            self.accuracy(tag_logits, labels, mask)
            output["loss"] = sequence_cross_entropy_with_logits(tag_logits, labels, mask)
            total = torch.sum(torch.ones(labels.shape)).item()
            y_pred = torch.argmax(tag_logits, dim=-1)
            self.sentence_correct += int(torch.sum(labels == y_pred).item() == total)
            self.sentence_total += 1
            self.y_preds = y_pred.detach().cpu().numpy()
            self.y_trues = labels.cpu().numpy()

        return output
```
Can someone tell me what if my approach is wrong or point me in the right direction? 
Thanks for your help!

**Comment by DeNeutoy** [comment]
You can see here how to use an elmo model trained using the pytorch code:

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md#using-transformer-elmo-with-existing-allennlp-models

Where you have your `BasicTextFieldEmbedder` above, you'll need to substitute that with the configuration in the example and also make sure that the same data generating process (from the DatasetReader) you used for training the language model is being used so that your elmo embedder gets the right input. 

To approach this in steps, I would first try:

1. constructing a TextFieldEmbedder using the example config and getting it to load your weights.

2. Constructing a toy input to the text field embedder so you understand what it expects to receive as tensors.

3. Integrate it into your existing model.

**Comment by DeNeutoy** [comment]
@aniketSanap, did the above work for you?

**Comment by aniketSanap** [comment]
Yes it actually did. Thanks a lot for your time!

**Comment by rahulv1999** [comment]
@DeNeutoy the link you provided above is not valid anymore. Can you please update the link?
