### ISSUE TITLE
What does use_starting_offsets do?

### ISSUE THREAD

**Issue by luckytoilet** [allenai/allennlp#3148]
The `WordpieceIndexer` accepts an argument `use_starting_offsets`, but I cannot understand what it does. From the documentation:

```
use_starting_offsets : bool, optional (default: False)
    By default, the "offsets" created by the token indexer correspond to the
    last wordpiece in each word. If ``use_starting_offsets`` is specified,
    they will instead correspond to the first wordpiece in each word.
```

In practical terms, in what situations should we use starting offsets?

**Comment by joelgrus** [comment]
the wordpiece indexer generates, in addition to the indexed wordpieces, an `offsets` vector indicating for each token the  "corresponding" wordpiece index. by default it gives the index of the *last* wordpiece for each token, but if you set this parameter to true it gives the index of the *first* wordpiece for each token.

the reason for this is that sometimes you might want to "convert" the wordpiece embeddings to token embeddings. one way to do this is to take the last wordpiece embedding for each token; another way is to take the first wordpiece embedding for each token, and having the correct offsets makes this easy. 

if you just want to use the wordpiece embeddings as-is (or if you just want to take the first one, e.g. for doing classification) then it doesn't matter, because in that case you won't use the offsets.
