### ISSUE TITLE
Add a way to configure predictor name in `predict` and `serve` commands

### ISSUE THREAD

**Issue by rilut** [allenai/allennlp#323]
Hi, I created a new predictor and already registered it with `@Predictor.register`, but how do I select the predictor?

CMIIW, I see the `predictor_name` parameter on `Predictor.from_archive` but I think it never gets called from the configuration/argumentparser. I see it only falls back to `DEFAULT_PREDICTORS` if `None`.

Additional info:
- I see my predictor class doesn't have `_model` and `_dataset_reader`.
- I've created my own dataset reader successfully

Also, which is the best channel to ask a question? Thank you very much.

**Comment by matt-gardner** [comment]
For now, asking questions here is fine.  We're thinking of recommending stack overflow or something similar for questions like this in the future, but we aren't set up to monitor those questions yet.

I need a little more context to answer this question, though.  How are you wanting to use the predictor you've written?  Are you running `python -m allennlp.run serve`?

If so, then yes, we're not set up yet to have this be configurable (FYI @joelgrus).  The easiest hacky workaround for now is to modify [this dictionary](https://github.com/allenai/allennlp/blob/e125a490b71b21e914af01e70e9b00b165d64dcd/allennlp/service/predictors/predictor.py#L8-L13) in a script, then call the serve command yourself in a script.

**Comment by joelgrus** [comment]
this might answer your question: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/configuration.md

Because a class doesn't get registered until it's loaded, any code that uses
`BaseClass.by_name('subclass_name')` must have already imported the code for `Subclass`.
In particular, this means that once you start creating your own named models and helper classes,
the included `allennlp.run` command will not be aware of them. However, `allennlp.run` is simply
a wrapper around the `allennlp.commands.main` function,
which means you just need to create your own script
that imports all of your custom classes and then calls `allennlp.commands.main()`.

**Comment by matt-gardner** [comment]
@joelgrus, the issue is that even if you do import it correctly, you still can't use our server code, because specifying the predictor name doesn't actually happen anywhere in our code path: 

https://github.com/allenai/allennlp/blob/e125a490b71b21e914af01e70e9b00b165d64dcd/allennlp/service/server_sanic.py#L34

https://github.com/allenai/allennlp/blob/e125a490b71b21e914af01e70e9b00b165d64dcd/allennlp/service/predictors/predictor.py#L51

We need a way to get the predictor you want to use into the server, which currently has to be done by hacking `DEFAULT_PREDICTORS`, I think.

**Comment by joelgrus** [comment]
oh, I see. yes, you're right, I think there's an easy way to do this, let me noodle on it for a little bit

**Comment by rilut** [comment]
I did, I installed allennlp via pip, and I have my own allennlp project directory, let's name it `myallen`

In `myallen` directory, I have a directory structure similar to allennlp like and have a `run.py` copied from allennlp.

```$ tree -d .
.
├── run.py
├── datasets/
├── experiment_config/
└── myallen/
    ├── data/
    │   └── dataset_readers/
    └── service/
        └── predictors/
```

There I created my own dataset reader in `dataset_readers/` and registered it with your dependency injection and added its import on my own `run.py` and it works like a charm. I can train and evaluate.

I did the same with the predictor, but there just isn't way to specify where to select the predictor for:
     $ python3 run.py predict /tmp/my_model_folder/model.tar.gz my_input.txt

**Comment by matt-gardner** [comment]
Ok, great, thanks for the additional context.  It does indeed look hacking the `DEFAULT_PREDICTORS` should work for you, at least until we have a better fix in place.  You can also just use the `evaluate` command, which will give you metrics from a model without needing a `Predictor`.

**Comment by rilut** [comment]
You're welcome. Yeah the evaluation and metrics work great for me, I'm just curious to see the output 😄. Thanks for the information.

**Comment by joelgrus** [comment]
ok, I merged the changes in 

https://github.com/allenai/allennlp/pull/329

now when you call `main()` you can provide overrides for the "model -> predictor" mapping used by `predict` (and likewise for the trained models used by `serve`), which I think should address this use case.

let me know if it doesn't, and I'll re-open.
