### ISSUE TITLE
Will updates to wikitables be released?

### ISSUE THREAD

**Issue by ghost** [allenai/allennlp#3242]
We are using an old (java based) version of wikitables. And latest version does not include java.  
However, the models page  [https://allennlp.org/models](https://allennlp.org/models)  does not list wikitables or sematic parsing.     

So either we have to stop that project, or wait for an update or write our own version of wikitables parsing.    

Can you please suggest - if you plan to release wikitables parsing further? If yes, any dates planned?

**Comment by SandeepBhutani** [comment]
Hi @pdasigi : Thanks for latest model . Can you please share sample code how to load it.   
From old code reference I am not able to load it. 
New code uses `WikiTablesSemanticParser   `which needs some parameters.
Also, following also give some error

```
predictor=Predictor.by_name('wikitables-parser')
predictor()

TypeError: __init__() missing 2 required positional arguments: 'model' and 'dataset_reader'
```

Can some sample code be available please, so that latest model can be used (Same way as other samples are listed in [https://allennlp.org/models ](https://allennlp.org/models )  )
