### ISSUE TITLE
AllenNLP Semantic Parser Wikitables response 

### ISSUE THREAD

**Issue by nebhandari** [allenai/allennlp#3337]
I am using allennlp semantic parser , I am able to get the correct response of the question as well.
eg: If i ask the question "Who got the highest marks in Subject1?" 
I get the name of the person who scored the highest marks in the table.

My requirement is that in such cases rather than just getting the name of the person i want the entire row corresponding to the answer.
Basically something like a "select * " for the filtered row.

In case the answer is an aggregate then only the aggregate answer is sufficient.

Is is possible in the current implementation of semantic parsing?

**Comment by matt-gardner** [comment]
This is not easy with our code.  You could either do some post-processing on what you get back, trying to recover the rows that you want, or you need to modify the parser and train it yourself on some data.

**Comment by nebhandari** [comment]
Thanks for the prompt reply @matt-gardner . 
I will try to do post processing on the data. 
Can you share any documentation available for modifying the parser and then training it.

**Comment by matt-gardner** [comment]
Modifying the parser means modifying the [domain language](https://github.com/allenai/allennlp/blob/fa78ab5769541e552c592f0c196a4d6dc402c02a/allennlp/semparse/domain_languages/wikitables_language.py) that we parse into, to allow for returning rows.  If you do this, you also need to figure out a way to train the parser to produce these programs, which is challenging, because you'll need to create your own training data.  This is largely a research problem that we don't have the bandwidth to help you with, unfortunately.

The semantic parsing code that we have is intended for research purposes, and while we're happy to give pointers on how to use the code for research, we don't think these parsers are good enough at this point to actually use in any kind of product, and we can't support that kind of use.

**Comment by nebhandari** [comment]
In that case i will work on post processing on the output.
Thanks a lot @matt-gardner
