### ISSUE TITLE
IndexField not using sequence_field at all

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3339]
In the definition of [IndexField](https://github.com/entslscheia/allennlp/blob/master/allennlp/data/fields/index_field.py), it seems like the second parameter `sequence_field `to create an IndexField object is not used. What I expected was that it should have used this parameter to check whether the given id is legal or not, just as what SpanField did. But it turned out there is no suck sanity check inside IndexField, which makes the second parameter almost useless. I think we should add a sanity check to` __init__` to make sure the given id is non-negative and doesn't exceed the length of the input `sequence_field`. Does it make sense?

**Comment by matt-gardner** [comment]
It actually _is_ used when checking fields for equality, which happens in a few places in the code.  But you're right that we don't do any sanity checks on the index.  Did you run into a bug that would have been caught by such a check?

**Comment by entslscheia** [comment]
Actually, I didn't run into any bug. It was just that I didn't know what `sequence_field` was used for. But now I see it since you said that you are using it when checking for equality, which seems to me is not such a common use case, because when using IndexField most of the time I just want to use it to record an id.

**Comment by matt-gardner** [comment]
Yeah, we put it there because semantically an `IndexField` is a pointer to something, and so for readability and understandability, it made sense for the index field to actually have that pointer, even if we didn't actually use it.  It turns out that later we used it and it's important, and we could still add a sanity check, we just haven't found a need for the check at this point.
