### ISSUE TITLE
Allennlp Semantic Parsing Wikitables response

### ISSUE THREAD

**Issue by nebhandari** [allenai/allennlp#3342]
I am getting expected response for a question like "Who got the highest marks in Subject1? "
but getting incorrect answer for question such as "What is the name of the female who has age above 20?  "
Is there a way i can get the correct response for the second type of question where multiple conditions needs to be checked?

**Comment by matt-gardner** [comment]
Unfortunately, no. What that means is that the parser is seeing questions that it either didn't see at training time or didn't learn well enough at training time, and you need to train a better parser.  We can't fix problems like "the model isn't working well enough" - that's a research problem, not a code problem.

If you have a SQL database instead of a wikipedia table, you might be better off using a text-2-sql parser instead of our wikitables parser.  See, e.g., [this code](https://github.com/benbogin/spider-schema-gnn).  Though, again, that's also a research project, so don't set your expectations too high.

**Comment by nebhandari** [comment]
Thanks @matt-gardner  , i will check what best i can get using text-2-sql parser
