### ISSUE TITLE
Test on ATIS dataset

### ISSUE THREAD

**Issue by PLechner1337** [allenai/allennlp#3383]
Hi folks,

basically I want to do a test for a semantic parser on the ATIS dataset to compare it with another parser for my bachelor thesis. I already have the results for the other parser but I'm struggling to run the second. 
I installed allennlp on my virtual Linux Mint machine but when I want to run the training task:
`allennlp train training_config/atis_train.jsonnet -s experiments/atistest` I get an error message saying:
`allennlp.common.checks.ConfigurationError: 'atis not in acceptable choices for dataset_reader.type: ` and a list of _valid?_ reader types.

I'm new to the whole semantic parsing task and not really familiar with Linux/Ubuntu. 
I want to use [this](https://github.com/allenai/allennlp/blob/master/training_config/atis_train.jsonnet) training task and I cloned [this](https://github.com/lil-lab/atis) repo to the allennlp path.

I just need the accuracy for the parser on the ATIS dataset by running it on my machine.
Can someone walk me through this?

Kind regards,
Philipp

**Comment by isaacmg** [comment]
I'm having the same issue as well. I think the structure of the allennlp repository was changed recently.

**Comment by brendan-ai2** [comment]
Sorry for the trouble! We are indeed moving the semantic parsing code to a new repository in order to decrease the cognitive load of having so many models in the main repo as well as having so many dependencies. For now, I'd suggest using one of our published releases which shouldn't have this problem. For instance, https://github.com/allenai/allennlp/tree/v0.9.0. We're going to try to get this cleaned up by our 1.0 release.

@PLechner1337, if you still have problems with a published release and the tutorial that @isaacmg linked, please let me know.

**Comment by brendan-ai2** [comment]
@matt-gardner , this is probably already on your radar, but the [Semantic Parsing tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/semantic_parsing.md) needs some updating to account for the sub-repo move. Thanks.

**Comment by matt-gardner** [comment]
I'm going to close this issue and open a new one for tracking tutorial updates.
