### ISSUE TITLE
AutoRegressiveSeqDecoder ignores target_namespace 

### ISSUE THREAD

**Issue by dasguptar** [allenai/allennlp#3412]
The `AutoRegressiveSeqDecoder` class takes in a `target_namespace` argument with a default value of `"tokens"`.
However, it seems to be ignoring that value in a few places:

- [Line 156](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L156)
- [Line 425](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L425)
- [Line 433](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L433)

I think these instances should be changed to `target_tokens[self._target_namespace]`. I can raise a PR for the same if it looks OK.

**Comment by schmmd** [comment]
@dasguptar that makes sense to me, but it's probably best if we get a third (and more informed) opinion.  @brendan-ai2 what do you think about this suggestion?

**Comment by schmmd** [comment]
@dasguptar after talking with @brendan-ai2 we both think this would be a great change--thanks!  PR very much welcome.

**Comment by sai-prasanna** [comment]
@dasguptar Thanks for looking into this! This has to be fixed in addition to adding tests for the AutoRegressiveDecoder.

On a side note, The `ComposedSeq2Seq` commit took a long time with me modifying the structures made by another contributor and I think I ended up missing few stuff out.

My team is currently looking into the training speed differences between `fairseq` and this abstraction (in addition to @scarecrow1123 's ddp inprogress commit). Hope to get something robust out and possibly replace fairseq. If you wish to collaborate on this module further, don't hesitate to ping me!
