### ISSUE TITLE
How can use `DataIterator` and `Predictor` together?

### ISSUE THREAD

**Issue by skurzhanskyi** [allenai/allennlp#3413]
How can we use `DataIterator` and `Predictor` together?

I would like to use `DataIterator` to compute batches officially, but `DataIterator` returns `TensorDict` while the most proper `Predictor` method I found - `predict_batch_instance` take `List[Instance]` for prediction.

**Comment by schmmd** [comment]
I see the problem you're hitting and it's a bit annoying.  It sounds like you want to batch with a `DataIterator` and for each batch compute predictions over the same instances, but you can't because `DataIterator` has already converted the `Instance`s to tensor dicts.

I'll discuss more tomorrow with the team.  What subclass of `DataIterator` are you using?

**Comment by schmmd** [comment]
Take a look at `forward_on_instances`, in particular this line: https://github.com/allenai/allennlp/blob/master/allennlp/models/model.py#L150

You can call forward and decode directly, which will get you the output you're looking for.  The additional code is pretty straightforward and does things like detaching from the GPU and cleaning up the resulting text for JSON serialization.

**Comment by skurzhanskyi** [comment]
Sorry for late response.
Thank a lot for your answer
