### ISSUE TITLE
Specify different iterator when using evaluate command

### ISSUE THREAD

**Issue by sayaendo** [allenai/allennlp#3422]
**Is your feature request related to a problem? Please describe.**
I need to be able to use a different iterator when evaluating my model on different datasets than the ones seen during training/validation. This should be a fairly useful yet easy to implement feature - as we progress more towards transfer learning and other alternative training and evaluation regimes, it hurts to be stuck with the same iterator used during training/validation.

**Describe the solution you'd like**
The evaluate command should allow an "override" json parameter that allows to change the validation_iterator parameter, which will be used during the evaluation.

**Describe alternatives you've considered**
I've tried changing the config.json file manually in the model output folder, but for some reason that didn't work (the evaluate command kept using the old iterator). If there's any other hacky way of doing this, besides compiling AllenNLP from source, I would love to know.

**Comment by kernelmachine** [comment]
This seems like a pretty useful feature, but may require some back and forth after the EMNLP conference.

**Comment by matt-gardner** [comment]
Two existing solutions:

1. Use the [`--overrides`](https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/commands/evaluate.py#L97-L103) command line flag to the `evaluate` command.  Getting the syntax of the JSON there right is annoying, and I'm not sure what it is off the top of my head, but there might be examples that you can search for.
2. I'm guessing that hacking the `config.json` didn't work because you're using a `model.tar.gz` file, and that tar file has its own `config.json` inside of it.  If you un-tar that, modify the config, and re-tar it, it should work.

As option 1 is actually the requested feature, and it already exists, I'm closing this issue.  Let us know if you have additional questions.
