### ISSUE TITLE
Resolve relative path in config.json

### ISSUE THREAD

**Issue by tamuhey** [allenai/allennlp#3425]
I sometimes want to save some file path in config.json.
However, relative paths don't work and the mobility is reduced.  
So I want a function to resolve relative paths from config.json in the archive directory.

**Comment by kernelmachine** [comment]
I think this feature request will require more detail. Can you explain more the use case you're looking for, and why you need relative paths?

**Comment by tamuhey** [comment]
I want to use [transformers](https://github.com/huggingface/transformers) as a `TextEmbedder`, and the models take `model_path` in instantiation. 
This `model_path` is a relative path, and I want to pack it into `archive` directory.
In restoring, `model_path` in `config.json` is resolved from runtime path, and the resolving fails.

Although I know I rewrite the transformers model so that `config.json` doesn't need have relative path, I don't want to do that in terms of maintainability.

**Comment by matt-gardner** [comment]
Yes, using paths like that is problematic.  A couple of possible solutions: (1) use a model name instead of a model path.  If you're just using a standard pretrained model, this is the preferred solution (you get caching from huggingface, less potential for error, more readable configs, etc.).  (2) If you have pretrained your own transformer (or want to use your own fine-tuned version for this, etc.), and you want it to be portable this way, upload your pretrained transformer to somewhere that is accessible from the web, and put a link your config.  The link will be portable, and will have caching.

**Comment by matt-gardner** [comment]
It would probably be a bit of a mess to try to detect and resolve relative filenames (where does the check live?  how does it work?).  If someone has a clean solution, we'd probably accept a contribution here, but with available workarounds, we are unlikely to work on this ourselves.

**Comment by kernelmachine** [comment]
Since we support jsonnet, you can use `std.extVar("PWD")` to get the current working directory and construct a relative path from that.

**Comment by tshu-w** [comment]
For those who wish to use the relative paths of the jsonnet files, here's a roundabout solution:
```jsonnet
local current_directory = std.split(std.thisFile, "/")[0] + "/";
{
  "data_path": current_directory + "../data/path",
}
```
