### ISSUE TITLE
Migrate mistmatched BertTokenIndexer / Embedder to use new transformers repo

### ISSUE THREAD

**Issue by maksym-del** [allenai/allennlp#3450]
We have already upgraded from v1 to v2 in https://github.com/allenai/allennlp/pull/3449. However, some code also depends on v0.6.0 (pytorch_pretrained_bert).

The migration requires changes to the bert_optimizer, modeling code, and existing bert_src config.

The guide is available [here](https://github.com/huggingface/transformers#migrating-from-pytorch-pretrained-bert-to-transformers).

**Comment by matt-gardner** [comment]
Specifically, what needs to be done here is make a mismatched tokenizer / token indexer for the case where you want to tokenize with words, but do modeling with wordpieces / some pretrained transformer.  We originally did this just for BERT (because that's all that was available), but we should do it generally for all pretrained transformers.

**Comment by matt-gardner** [comment]
This was done in #3634.  Closing this.  There are still a couple of small issues, but we can track those in #3305.
