### ISSUE TITLE
AttributeError: 'list' object has no attribute 'count_vocab_items'

### ISSUE THREAD

**Issue by yyHaker** [allenai/allennlp#3471]
**Describe the bug**
Hi, I want to load SQuAD data for Bert to train, my SQuAD dataset reader is as follows, [squad_bert.py](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/data_loader/squad_bert.py), and I use based Bert model as [bert_for_span_qa.py](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/models/bert_for_span_qa.py). However, when I test DatasetReader, just run [test_data_loader.py](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/test_data_loader.py), it can works. But when I try to use the bert mdoel to train, just run [train.py](https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/train.py), it gets following errors:
![image](https://user-images.githubusercontent.com/18585628/69205570-45555e80-0b85-11ea-8468-40cdf2d90f18.png). What's wrong with it?

**System (please complete the following information):**
 - OS: [Linux]
 - Python version: [v3.6.5]
 - AllenNLP version: [v0.9.0]
 - PyTorch version: (v1.2.0)

**Comment by DeNeutoy** [comment]
This line is appending the tokens and not the allennlp `Field` class: 
https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/data_loader/squad_bert.py#L251

Instances must contain only a dictionary of allennlp `Fields`, which is why this won't index correctly. That line just needs to be changed to:
```
fileds["context"] = context_filed
```

The reason why your example script worked is because you are not calling `instance.count_vocab_items` or `instance.index_fields()`. If you had called one of these, it would also break.

**Comment by yyHaker** [comment]
> This line is appending the tokens and not the allennlp `Field` class:
> https://github.com/yyHaker/AllenNLPNeedsMoreLove/blob/master/src/data_loader/squad_bert.py#L251
> 
> Instances must contain only a dictionary of allennlp `Fields`, which is why this won't index correctly. That line just needs to be changed to:
> 
> ```
> fileds["context"] = context_filed
> ```
> 
> The reason why your example script worked is because you are not calling `instance.count_vocab_items` or `instance.index_fields()`. If you had called one of these, it would also break.

@DeNeutoy Thank you very much, it's the problem!
