### ISSUE TITLE
 PretrainedBertIndexer and PretrainedBertEmbedder not properly archived

### ISSUE THREAD

**Issue by qiuwei** [allenai/allennlp#3498]
**Describe the bug**
I have a model that uses the PretrainedBertIndexer and PretrainedBertEmbedder in the embedding layer.
The pretrained_model parameter for the PretrainedBertEmbedder is specified as a path to a homebrewed bert model.

The training and evaluation went smoothly. However, I can not use the model on a second machine. 
When loading the model using  simple_server, I got the following error:
```
'datasets/lm/bert.tar.gz' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'datasets/lm/bert.tar.gz' was a path or url but couldn't find any file associated to this path or url.
```
Apparently the bert model was not found on the second machine.
I am wondering whether the bert model itself should be archived in the model.tar.gz as well.

**To Reproduce**
Steps to reproduce the behavior
1.  Develop some other model using bert model as a feature extractor.
2.  deploy the model to a different machine than the model was trained on.
3. load the model using simple_server.

**Expected behavior**
I expect the model to be a standalone binary which can be loaded and run without any other dependencies.

**System (please complete the following information):**
 - OS: [Linux]
 - Python version: [3.6.1]
 - AllenNLP version: [e.g. v0.9.0]
 - PyTorch version: (1.2.0)

**Additional context**

**Comment by DeNeutoy** [comment]
https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo.py#L227

The problem is that you are passing a relative path which cannot be found on the new machine. We fix this in quite a gross way in the URL above, by preserving some kind of mapping inside the archive file, and telling from params that it needs to copy a particular file into the archive. However, the easiest way to do this is to just use a remote URL for the model, so that it can be downloaded and cached anywhere.

**Comment by qiuwei** [comment]
Thanks a lot for clarifying it.
