### ISSUE TITLE
Does HotFlip work with sequantial tagging tasks such as NER and POS?

### ISSUE THREAD

**Issue by c4n** [allenai/allennlp#3507]
Does HotFlip work with sequantial tagging tasks such as NER and POS?
I want to test the robustness of sequential taggers. Is it possible to use HotFlip?

**Comment by matt-gardner** [comment]
Yes, it is!  We did this for NER, as described in the AllenNLP Interpret paper.  The key thing is to take each decision independently and try to flip it; you need to decide how you want to break up the tag sequence into individual decisions (for NER, we did this for each predicted span).  @Eric-Wallace, do we have a tutorial that covers how to use the NER stuff we did?

Also, the last time I looked at the NER results in the demo, it looked off.  We did some major refactoring in between running the experiments for the paper and merging it in here, and it's possible I broke something for NER when doing that.  If you have a hard time getting reasonable results, let me know.

**Comment by c4n** [comment]
@matt-gardner  Thank you for your reply! I will try it out. If there's a tutorial for that, it would be amazing!

**Comment by c4n** [comment]
For NER task, It seems to work for most cases. I notice that it wouldn't work, if there's no named-entity in the input sentence. (what if, I want to the model to predict that the "O" tag is a named-entity). 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/4990317/70562706-827aa280-1bbf-11ea-9c0f-b927a253e365.png">

**Comment by matt-gardner** [comment]
Yes, that is expected.  You'd have to modify code in order to make it behave that way.  The thing you would have to modify is [`predictions_to_labeled_instances`](https://github.com/allenai/allennlp/blob/master/allennlp/predictors/sentence_tagger.py) in the `Predictor`.  It currently returns one `Instance` per predicted entity; you would want to change it to something else.  I'm not sure what exactly I'd change it to if there are no entity tags, but I'm interested to hear what you come up with!

**Comment by Eric-Wallace** [comment]
@c4n Let us know if you have other questions, happy to help. I am going to close this issue for now in the meantime.
