### ISSUE TITLE
Getting error for a column name "Title"

### ISSUE THREAD

**Issue by nebhandari** [allenai/allennlp#3544]
Hi Team,

When the table structure has one of the column name as "Title" and the question is framed on the column name "Title" i am getting error.
Is this a know issue for column name "Title"?

Regards,
Neha

**Comment by matt-gardner** [comment]
Can you be more specific?  What kind of error?  If it's a python exception, please provide some more detail so that we can figure out the problem.  If it's an incorrect prediction, there is nothing that we can do to fix that - the model we provide does not have perfect accuracy, and improving its accuracy is a research problem, not a maintenance issue.

Also, the code for this model now lives in `allennlp-semparse`; I'm going to transfer this issue there, if you have an actual code bug, instead of a modeling issue.
