### ISSUE TITLE
Use of invariant vs. covariant types in function/method signature annotations

### ISSUE THREAD

**Issue by willfrey** [allenai/allennlp#3562]
**System (please complete the following information):**
 - OS: macOS Catalina Version 10.15.2
 - Python version: 3.7.5
 - AllenNLP version: v0.9.1-unreleased (master)
 - PyTorch version: 1.3.1

**Question**
I've encountered function/method signature annotations in the codebase that are invariant but could easily be relaxed to be a covariant equivalent. For example the (signature of block_orthogonal)[https://github.com/allenai/allennlp/blob/master/allennlp/nn/initializers.py#L101] could be changed from

```python
def block_orthogonal(tensor: torch.Tensor, split_sizes: List[int], gain: float=1.0) -> None:
    ...
```

to

```python
def block_orthogonal(tensor: torch.Tensor, split_sizes: Sequence[int], gain: float=1.0) -> None:
    ...
```

Would it be helpful if I changed these annotations as I encounter them and submit PRs?

I wanted to ask before instead of just diving into it because there may be some underlying reason you have invariant argument annotations that I'm not aware of, perhaps something to do with the `FromParams` mixin.

Thanks!

**Comment by matt-gardner** [comment]
Is there an actual problem that you encounter with those type annotations?  E.g., a mypy failure, or something?

Our reasoning initially was that the type annotations exist almost entirely for readability.  And for the average reader, seeing `List` instead of `Sequence` (and similar for other types, like `Dict` vs. `Mapping`) is more familiar.  So while `Sequence` would be more technically "correct", for our purposes we just went with the simpler ones.

We now also actively inspect the type annotations, and so there might also be some logic in `FromParams` or other places that depends on those particular types, but I *think* it's already handled correctly, and failing tests should tell us if it doesn't.

My vote is to stick with the simpler types, unless there's a compelling reason, like something actually broken, to switch them.

**Comment by willfrey** [comment]
I've found myself using `types.MappingProxyType` from time to time to provide immutable views for some sort of default mapping of objects such as a default mapping of token indexers. `mypy` will yell at me for this.

Additionally, annotating with `Dict` gives me no information about whether or not that dictionary is going to be mutated by the method. If it was annotated with `Mapping`, then I know it shouldn't mutate my dictionary, whereas `MutableMapping` tells me it could mutate.

`mypy` will also give you warning notes recommending that you use `Mapping` instead of `Dict` or `Sequence` instead of `List`.

**Comment by matt-gardner** [comment]
Hmm, yeah, I get the concern.  I'm just worried that we're already pretty extreme in our python code style.  Pushing farther, going all the way to `Mapping` / `MutableMapping`, probably crosses a line for most readers of the code, making the type annotations confusing instead of helpful.  For instance: I've written python code for well over a decade, but I couldn't have told you that `Mapping` was immutable until you just said so.  I'd have had to look it up.  And at that point, for most users, the annotations are no longer helpful.

I'm open to changing my mind if a bunch of people disagree, but I don't yet see a compelling enough reason to switch the type annotations.  It's unfortunate for a few users, but you can just tell mypy to ignore a particular line if it bothers you.

**Comment by willfrey** [comment]
I don't think it's extreme ☺️ I think it'd be more correct!

The `Mapping`/`MutableMapping` difference, for example, isn't really anything new. Those are just generic versions of their counterparts in `collections.abc`, which has been around for a while. I think it'd be similar to your use of annotating variables with the abstract base classes, such as `TokenEmbedder`, instead of a specific implementation such as `Embedding`.

I'd be happy to make some exemplary annotation changes in a fork if you think it'd be worth looking at. I don't know exactly how we'd measure the helpfulness of annotations, but my first bet would be it's some combination of: 1) type checkers catching bugs that a compiler would normally take care of; 2) IDE-like tools that make use of annotations; 3) aiding the readability of the code.

Otherwise, feel free to close this issue. Since type annotations don't actually impact Python at runtime, this is arguably somewhat cosmetic and I can just tell `mypy` to shut its trap 😀

**Comment by DeNeutoy** [comment]
I'm strongly opposed to this - type hints are already foreign to a lot of intermediate python users and covariant types makes them even harder.

**Comment by willfrey** [comment]
That’s totally fair. I’ll close this.

**Comment by DeNeutoy** [comment]
Thanks for understanding!

**Comment by willfrey** [comment]
For what it's worth, I've run into one situation with dataset readers where the annotation matters for construction using `from_params(...)`.

```python
from typing import Dict, Mapping

from allennlp.data import DatasetReader, Tokenizer, TokenIndexer

# This will work just fine.
@DatasetReader.register("working")
class WorkingDatasetReader(DatasetReader):
    def __init__(
        self,
        tokenizer: Tokenizer,
        token_indexers: Dict[str, TokenIndexer],
        lazy: bool = False,
    ):
        super().__init__(lazy=lazy)
        self._tokenizer = tokenizer
        self._token_indexers = token_indexers

# This will give you errors later because the token_indexers don't get processed correctly.
@DatasetReader.register("broken")
class BrokenDatasetReader(DatasetReader):
    def __init__(
        self,
        tokenizer: Tokenizer,
        token_indexers: Mapping[str, TokenIndexer],
        lazy: bool = False,
    ):
        super().__init__(lazy=lazy)
        self._tokenizer = tokenizer
        self._token_indexers = token_indexers
```

Just posting this here to confirm one of my original suspicions that `FromParams` might rely on the invariant annotations!

Thanks again for all your work on this framework!

**Comment by matt-gardner** [comment]
Yeah, I thought that might happen.  This is one I'm happy to accept a PR for; it should be a simple one-line change in the relevant part of `FromParams`.  It doesn't hurt us at all to accept that annotation, we just don't want to use it ourselves.

**Comment by willfrey** [comment]
Great! I'll start working on a PR to fix this once I wrap up some work that's already on my plate.

For what it's worth, I tried to naively change [this line](https://github.com/allenai/allennlp/blob/master/allennlp/common/from_params.py#L263) to accept `Mapping` in addition to `dict` and `Dict` but it didn't fix the problem.

I'll give that block a more careful read to figure out how it's getting the class constructor and see if that gets it the rest of the way there.

I think it's entirely reasonable that if the annotation is `Mapping` or `MutableMapping` then a `dict` is the least-surprising thing to use internally. Likewise one could use `list` for `MutableSequence` or `Sequence` and a `set` for `Collection`. But I'll see to fixing the `Mapping` issue first before I making changes to handle additional scenarios.

**Comment by matt-gardner** [comment]
Hmm, I would have thought that would work. Not sure without digging into it more why it wouldn't.

**Comment by willfrey** [comment]
No worries. I'm happy to take a look at it!
