### ISSUE TITLE
The number of loaded instances is not 1000, when using bucket iterator with lazy datasets.

### ISSUE THREAD

**Issue by YongfeiYan** [allenai/allennlp#3572]
**Describe the bug**
The documentation says that [loading 1000 instances by default](https://github.com/allenai/allennlp/blob/ec441a3efbb0bd7c98af7202ca1e4c4086747ba2/allennlp/data/iterators/data_iterator.py#L204), but the [code](https://github.com/allenai/allennlp/blob/ec441a3efbb0bd7c98af7202ca1e4c4086747ba2/allennlp/data/iterators/data_iterator.py#L216) actually loads batch_size instances. 
This makes the default bucket iterator fails to bucket instances with similar lengths.

**Comment by schmmd** [comment]
I see that the documentation mismatches what's done in the code, but why does this prevent the bucket iterator from bucketing instances with similar lengths?

**Comment by matt-gardner** [comment]
Because if you only have `batch_size` instances, there isn't really anything to bucket - the whole point of bucketing is to group the instances into similar sized batches.  I need to have way more than one batch worth of instances, then group them by size into smaller batches.

@YongfeiYan, I think this is working as intended.  The documentation you pointed to isn't given as the default for loading instances into memory, it's an example in a private method docstring.  The code that you pointed to is only run if (1) you've chosen to use a lazy iterator (which makes bucketing hard in general), and (2) failed to pass `max_instances_in_memory` (which makes bucketing impossible).  The default for `max_instances_in_memory` is `None`, because the default for `lazy` is `False`.  You just need to pass a value for that parameter if you want bucketing and laziness at the same time.
