### ISSUE TITLE
Is there an inverse version of "allennlp.nn.util.batch_tensor_dicts" ?

### ISSUE THREAD

**Issue by c4n** [allenai/allennlp#3576]
Instead of taking a list of tensor dictionaries, where each dictionary is assumed to have matching keys, and returns a single dictionary with all tensors with the same key batched together. Can we take a single dictionary with all tensors  and split it into list of tensor dictionaries ?

**Comment by schmmd** [comment]
This is hard to do this in general.  Can you explain why you want to do this?  Perhaps there's a better approach.

**Comment by c4n** [comment]
probably not the best practice, I was thinking about using a function that only works for an instance not a batch for some of  the selected batches while training.  Perhaps, it's easier to make that function works on a batch instead of an instance.

**Comment by matt-gardner** [comment]
It's pretty hard to have such a splitting function be general across all data types, and it's not generally useful, so we don't want to try to add one to the library.  If you can make assumptions about the data type, though, it's quite easy.  Once you have the tensors in your model, especially after the text has been embedded, you can just iterate over the batch dimension for whatever tensor(s) you want to expand:

```python
question_embeddings = self.embedder(question)
for question_embedding in question_embeddings:
    self.my_instance_level_function(question_embedding)
```

And you can `zip()` tensors together if you need more than one.  In most cases it would be significantly more performant to figure out how to batch `my_instance_level_function` instead of unrolling it like this, but you can always do this if you need to.

I think this answers your question, so I'm going to close the issue, but feel free to keep commenting if you have more questions.

**Comment by c4n** [comment]
thank you! @matt-gardner
