### ISSUE TITLE
Shape mismatch for stacked self attention model (possible bug?)

### ISSUE THREAD

**Issue by RikVN** [allenai/allennlp#3598]
I want to train a Transformer model (using StackedSelfAttentionEncoder) + BERT with batch_size 48 and 4 attention heads. I got the following error:

```
File "/home/user/anaconda3/envs/allen/lib/python3.7/site-packages/allennlp/modules/seq2seq_encoders/multi_head_self_attention.py", line 134, in forward
    mask.repeat(1, num_heads).view(batch_size * num_heads, timesteps),
RuntimeError: shape '[192, 50]' is invalid for input of size 6144
```

I did a bit of debugging, it should be that in this line of code:

```
attention = masked_softmax(scaled_similarities, mask.repeat(1, num_heads).view(batch_size * num_heads, timesteps), memory_efficient=True)
```

timesteps should be the same size as the mask of source_tokens. This can be traced to _encode of ComposedSeq2seq:

```
# shape: (batch_size, max_input_sequence_length, encoder_input_dim)
embedded_input = self._source_text_embedder(source_tokens)
# shape: (batch_size, max_input_sequence_length)
source_mask = util.get_text_field_mask(source_tokens)
```

So the shape should be max_input_sequence_length for both, but it isn't for the source_mask, which has a smaller length. This causes the mismatch later on.

The shape of [batch_size * num_heads, timesteps] seems to be correct, but the mask has 32 instead of 50 as max_sequence_length: 4 heads * batch_size 48 * 32 = 6144

In util.get_text_field_mask, there is this code:

```
if "mask" in text_field_tensors:
       return text_field_tensors["mask"]
```

In the function description there is this comment about this:

If the input ''text_field_tensors'' contains the "mask" key, this is returned instead of inferring the mask. 
TODO(joelgrus): can we change this?

If I comment that code out, the model seems to run fine. So perhaps a wrong mask gets saved in source_tokens at some point? I'm not sure, this is as far as my debugging skills went. Also since I'm not entirely sure what's going on then I'm hesitant to use it.

Could very well be that it's my own mistake, surely. In that case any help is also appreciated. The config file I used is here:

http://www.let.rug.nl/rikvannoord/config/transformer.json

**Comment by DeNeutoy** [comment]
@RikVN This is a good point to raise, as it's not clear in our docs why this wouldn't work.

https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py#L46

The problem here is that we are indexing using wordpieces, meaning we get a mask and token_offsets which correspond to the wordpiece length of the sentence. However, the `BertEmbedder` collapses these indices back down to the word level for you, by just selecting out the wordpiece indices which correspond to the start or end offsets of the word boundaries, depending on the `use_starting_offsets` flag that you pass in the `TokenIndexer`. So this means using the mask from the wordpieces will be the wrong shape by the time you have already passed your textfield through the embedder. Hopefully that makes sense? If you wanted to add this documentation to the `BertPretrainedEmbedder` that would be great, but it's a little hard to fix the mask thing generally and it is still technically getting the correct mask from the text field. 

Hopefully that's helpful, LMK if you have any questions!

**Comment by RikVN** [comment]
Thanks, that helped me a lot! Turns out that In general I was confused how BERT worked in combination with the tokenizer and token indexer, but I think I get it now. Indeed the mask is saved based on the offsets, and not on the wordpieces, which I use later. But that's easily fixable in the code.

**Comment by DeNeutoy** [comment]
Yes sorry, it's not very clear at the moment. It is something we are working on making substantially 1) clearer and 2) easier for the 1.0 release, e.g #2270 . I'll close this as there are other issues which track that work, and I think you're unblocked for now!
