### ISSUE TITLE
JustSpacesWordSplitter() not compatible with OIE pretrainied model

### ISSUE THREAD

**Issue by 132lilinwei** [allenai/allennlp#3672]
**Describe the bug**
If I change the OIE pertained model's tokeniser to JustSpacesWordSplitter(), the predictor gives empty output on any text.
However, when not changing the tokeniser, the result is good.

**To Reproduce**
```
oie = Predictor.from_path("https://allennlp.s3.amazonaws.com/models/openie-model.2018-08-20.tar.gz")
oie._tokenizer = JustSpacesWordSplitter()  # only run this line once
arg.predict("Mental health experts point out that the vast majority of people with mental illness are never violent.")
```

The result is
```
{'verbs': [], 'words': ['Mental', 'health', 'experts', 'point', 'out', 'that', 'the', 'vast', 'majority', 'of', 'people', 'with', 'mental', 'illness', 'are', 'never', 'violent.']}
```

**Expected behavior**
Normal classification result.

**System (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Python version: 3.7.3
 - AllenNLP version: I installed from master
 - PyTorch version: 1.3.0

**Comment by DeNeutoy** [comment]
The Open IE model predictor needs a way to identify verbs, which is why we need a tokenizer which also provides POS tags, see this line:

https://github.com/allenai/allennlp/blob/master/allennlp/predictors/open_information_extraction.py#L191

and here, where the pos tags are used:

https://github.com/allenai/allennlp/blob/master/allennlp/predictors/open_information_extraction.py#L226

If you already know the verbs in advance, you could override the `predict_json` method to construct the instances in a different way. Is that helpful?

**Comment by DeNeutoy** [comment]
Closing, this issue is resolved
