### ISSUE TITLE
How to train ELMo embeddings with my own corpus?

### ISSUE THREAD

**Issue by TharinduDR** [allenai/allennlp#3698]
I am working on a task to create my own ELMo embeddings. Even though there are many questions regarding that all of the questions redirect to https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md which doesn't exist now. 

Is there a new tutorial available?

**Comment by DeNeutoy** [comment]
Hi, sorry we shifted around the location of our docs, it now lives here:

https://allenai.github.io/allennlp-docs/tutorials/how_to/training_transformer_elmo/


FYI, language modeling has moved on substantially since we worked on ELMo. You may be better off using BERT, or another more modern pretrained representation.

**Comment by gohjiayi** [comment]
Hi, @DeNeutoy. The link is no longer available, are you able to share the updated link? Thank you!
