### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tamuhey** [allenai/allennlp#3712]
It's been four months since the last release, are you planning to release a new version?

**Comment by bratao** [comment]
I think they are planning a big refactoring towards 1.0, and still have many open issues with the 1.0 tag

**Comment by matt-gardner** [comment]
Thanks @bratao. Yes, we have been batching together a whole lot of breaking changes to clean things up and refresh our models. It's taking us a while to release a new version because things are currently in a half-broken state while we do this cleanup. I think we're getting close, but you can track progress by following the issues tagged with 1.0, as @bratao said.

Some major goals of the 1.0 release:
- make sure everything works well with the `transformers` repo
- replace our batching code (data iterators) with something native to pytorch that is a lot faster
- make everything easier to use if you want to write your own training script instead of using ours
- update most of our models to be at our very close to SOTA. We are basically done with this for reading comprehension models, close for coref, and others are coming soon
- split apart the library into a core repo with the abstractions, and separate repos for each task. This is so the main repo is more lightweight to install and use, and so that each task has its own example repo that you can copy for your project

**Comment by schmmd** [comment]
@tamuhey we plan to release 1.0 next quarter.  I'm not sure we plan to release before then, but we may have a release candidate if we have sufficient justification to.  If this would help you specifically in some way, please let us know!

**Comment by tamuhey** [comment]
@schmmd Thanks. I've submitted PR (#3432) fixes the version of PR before, and I would like to use it as a release. (Now I clone allennlp from master and use it)

**Comment by schmmd** [comment]
@tamuhey would it work for you to install from a specific commit with `pip install "git+git://github.com/allenai/allennlp.git@$SOURCE_COMMIT`?  That might be a convenient workaround until we have a 1.0 release.  It's pretty seamless to pip install from a particular GitHub SHA.

**Comment by tamuhey** [comment]
@schmmd Thanks, I'm installing `allennlp` like that.

**Comment by tamuhey** [comment]
@schmmd I want to publish my package on pypi, but [pypi doesn't allow direct link dependency](https://github.com/pypa/pip/issues/6301). 
Thus I want new allennlp on pypi.

**Comment by tamuhey** [comment]
spaCy releases nightly package: https://pypi.org/project/spacy-nightly/
I think it's good if allennlp releases nightly.

**Comment by schmmd** [comment]
@tamuhey thanks--that's a great motivating use case.  I'm reopening this issue.

**Comment by schmmd** [comment]
@tamuhey we're not going to do a release presently as too much is changing presently.  We don't recommend releasing pip packages that depend on a nightly state of AllenNLP.

However we do plan to have automated nightly releases for 1.0, see https://github.com/allenai/allennlp/issues/3758.
