### ISSUE TITLE
Parameters in docs aren't rendering properly

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3715]
This is for the CONLL 2000 dataset reader:
<img width="1174" alt="Screen Shot 2020-02-03 at 10 32 14 AM" src="https://user-images.githubusercontent.com/3291951/73680177-a8c53780-4670-11ea-84a6-33feac7c9e2e.png">

I haven't looked at the code to know what's causing it to render like this, but it should be fixed.

**Comment by epwalsh** [comment]
I believe pydocmarkdown doesn't support the `:class:ClassName` reference syntax, and in general everything after a colon is meant to be treated as the parameter description. So when the description contains something like `:class:TokenIndexer` it breaks because pydocmarkdown thinks you are defining a new parameter there.

So I think we'd just need to remove all `:class:` and other references of that form.

**Comment by matt-gardner** [comment]
I'm giving this a "week" label, because it's a ton of small changes that have to be done manually all over the docs.  Some related issues / PRs on docs stuff: #3972, #3973, #3974, #3975.

**Comment by matt-gardner** [comment]
Also: #3978.

**Comment by epwalsh** [comment]
A couple updates on this:

## Cross-referencing

It seems like `mathy_pydoc` doesn't handle automatic cross-referencing yet (see https://github.com/justindujardin/mathy/blob/master/libraries/mathy_pydoc/mathy_pydoc/preprocessor.py#L73), so in order to cross-reference we'd have to replace all `:class:Foo` type things with an actual markdown link like `[Foo](./foo.md)`. This would be annoying.

However [pydoc-markdown](https://github.com/NiklasRosenstein/pydoc-markdown) (which `mathy_pydoc` is based on) does do cross-referencing automatically. So we if we switch to `pydoc-markdown` we could replace `:class:Foo` with `#Foo`.

Is there any reason why we went with `mathy_pydoc` instead of `pydoc-markdown`? @DeNeutoy 

## Parameter descriptions that contain colons

Both `mathy_pydoc` and `pydoc-markdown` have trouble when a parameter description contains a colon. For example:

```python
def hello(name: str) -> str:
    """
    Says hello to the person specified with `name`.

    This link will render fine [some_link](https://example.com).

    # Parameters

    name : `str`
        The name to say hello to. This link will break
        this example [some_link](https://example.com).

    """
    return f"Hello, {name}!"
```

Will render as
<details><summary>Expand to see the generated Markdown</summary>

# a

## hello
```python
hello(name: str) -> str
```

Says hello to the person specified with `name`.

This link will render fine [some_link](https://example.com).

__Parameters__


- __name __: `str`
    The name to say hello to. This link will break
- __this example [some_link](https__://example.com).
</details>

If we decide definitively we want to stick with `mathy_pydoc` or switch to `pydoc-markdown` then I can try to make a PR with them to fix this.

**Comment by epwalsh** [comment]
So with `pydoc-markdown` we can actually just write our own little [`Processor`](https://github.com/NiklasRosenstein/pydoc-markdown/blob/2ffaeecb895019e4b5f1a4394826080cf9109b20/src/pydoc_markdown/interfaces.py#L57)
 that transforms the docstring into Markdown based on the exact syntax we use. Everything else is handled by the [`PydocMarkdown`](https://github.com/NiklasRosenstein/pydoc-markdown/blob/2ffaeecb895019e4b5f1a4394826080cf9109b20/src/pydoc_markdown/__init__.py#L47) class so this shouldn't be too hard.
