### ISSUE TITLE
Docker container create temporary files each time starting a container

### ISSUE THREAD

**Issue by AlbinDavid** [allenai/allennlp#3858]
**Describe the bug**
Each time the archival file is unzipped and stored in a temporary file created using hashing.This takes more memory each time I start container.

**To Reproduce**
Steps to reproduce the behavior
1. docker build -f Dockerfile.pip --tag allennlp/allennlp:latest .
2. sudo docker run -p 8700:8000 --runtime=nvidia --name=test_container --entrypoint="" -v $HOME/.allennlp:/root/.allennlp allennlp/allennlp:latest python -m allennlp.service.server_simple --archive-path https://storage.googleapis.com/allennlp-public-models/bidaf-elmo-model-2018.11.30-charpad.tar.gz --predictor machine-comprehension --field-name passage --field-name question --cuda-device 0

**Expected behavior**
The temporary file creation should be stopped which takes our memory

**System (please complete the following information):**
 - OS:  Linux
 - Python version: 3.6.1
 - AllenNLP version: I installed from master

**Comment by ZhaofengWu** [comment]
Where is this file getting created?

**Comment by AlbinDavid** [comment]
**Inside docker container**
361M    /tmp/tmpz9_jd3kg/weights.th
361M    /tmp/tmpy4gcqz0j/weights.th
361M    /tmp/tmpu83i6yrz/weights.th
361M    /tmp/tmpt6cqz0tx/weights.th
361M    /tmp/tmpox6j1oe1/weights.th
361M    /tmp/tmphbu9gtob/weights.th
361M    /tmp/tmpd1acqub5/weights.th
361M    /tmp/tmpc01j7gzt/weights.th
361M    /tmp/tmpalz62ifb/weights.th
361M    /tmp/tmpa1k9vyqc/weights.th
361M    /tmp/tmp3qqhvjx5/weights.th
361M    /tmp/tmp3kuji09c/weights.th
358M    /tmp/tmpz9_jd3kg/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpy4gcqz0j/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpu83i6yrz/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpt6cqz0tx/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpox6j1oe1/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmphbu9gtob/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpd1acqub5/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpc01j7gzt/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpalz62ifb/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmpa1k9vyqc/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmp3qqhvjx5/fta/model.text_field_embedder.elmo.weight_file
358M    /tmp/tmp3kuji09c/fta/model.text_field_embedder.elmo.weight_file

**Comment by DeNeutoy** [comment]
This doesn't seem to be a problem with allennlp, as it should be fine to assume that the `/tmp` directory is independently cleaned up. The problem seems to be more that you are mounting `/tmp/` inside your container (or that it is somehow stateful). Different linux distros do this cleanup differently, e.g https://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up/857154#857154

**Comment by theashworld** [comment]
For people stumbling on this, we faced the same issue and it seems that this happens because each new Predictor creates a copy of the model in the `/tmp` folder. This by itself is not a problem, but we regularly start and stop our container and each time a new Predictor object is created. This blows up the `/tmp`

The solution we have is to launch the docker with `--tmpfs /tmp` and before creating the Predictor object, remove all dirs from the /tmp folder,     `[shutil.rmtree("/tmp/" + d) for d in os.listdir("/tmp")]`

Hope this helps, and if there are better ways to do this, please let me know.

**Comment by epwalsh** [comment]
@theashworld this shouldn't be an issue anymore with 1.2. See https://github.com/allenai/allennlp/pull/4643.
