### ISSUE TITLE
`RandomSampler` creation by name fails

### ISSUE THREAD

**Issue by bryant1410** [allenai/allennlp#3864]
**Describe the bug**

Creating a `RandomSampler` in a config file by just the name fails.

**To Reproduce**

Define a config file having:

```jsonnet
{
  // ...
  data_loader: {
      sampler: 'random',
  },
  // ...
}
```

When trying to train, it'll fail to create the object.

The error seems to be in:

https://github.com/allenai/allennlp/blob/94d2f1511e0d46191e4f230615da3d5882474a41/allennlp/common/from_params.py#L338

**Expected behavior**

The config creation should happen successfully.

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux] Linux
 - Python version: [if it's not 3.6.1 or later, that's probably your problem] 3.7.6
 - AllenNLP version: [e.g. v0.9.0, or "I installed from master"] I installed from master
 - PyTorch version: (if you installed it yourself) 1.4.0

**Comment by bryant1410** [comment]
(the problem is the missing `data_source` mandatory arg)

**Comment by matt-gardner** [comment]
I thought this would just work; looking at it more closely, the problem is the mismatch in argument names between the data loader and the sampler.  The sampler *is* getting passed something called `dataset` in the `from_params` logic, it's just expecting it to be called `data_source`.  Can we make these names match, one way or the other?  That would solve this problem.

**Comment by DeNeutoy** [comment]
Huh, this line should give it the data_source:

https://github.com/allenai/allennlp/blob/master/allennlp/data/dataloader.py#L95

does it work if you explicitly specify the `"type": "random"`?

can you post the full stack trace too please

**Comment by matt-gardner** [comment]
Oh, sorry, I totally misunderstood the issue and commented too soon.  Yes, @bryant1410 has the right line number.  We can probably change that to recurse into `from_params` instead of directly calling the constructor, which would probably solve this issue.  But, yeah, specifying the type should also work.

**Comment by bryant1410** [comment]
> does it work if you explicitly specify the `"type": "random"`?

Yes! Forgot to mention that, sorry.

**Comment by bryant1410** [comment]
> We can probably change that to recurse into `from_params` instead of directly calling the constructor, which would probably solve this issue. But, yeah, specifying the type should also work

So when would `by_name` be used?

**Comment by matt-gardner** [comment]
When would `by_name` be used inside of the `from_params` logic?  No idea, without digging into it.  There's no a priori reason that it should be, though.
