### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by zhangatao** [allenai/allennlp#3880]
**Describe the bug**
Hello, my version of allennlp is 0.9.0, when I am pretrained_transformer_embedder_test.py under the tests folder, I get the following error
![image](https://user-images.githubusercontent.com/28706321/75627512-d370c480-5c0b-11ea-8a0d-55d2751a4f8f.png)
At the same time I found that there are many similar problems.

**Comment by zhangatao** [comment]
![image](https://user-images.githubusercontent.com/28706321/75660371-a1607080-5ca6-11ea-88be-d7406fbe0dc4.png)
![image](https://user-images.githubusercontent.com/28706321/75660792-29467a80-5ca7-11ea-8f1a-9b1ccb1d2092.png)

My allennlp is successfully installed. My python version is 3.6 and allennlp version is 0.9.0. Why does import.data.batch fail?

**Comment by DeNeutoy** [comment]
@zhangatao Are you copying the `pretrained_transformer_embedder_test.py` from the master branch? Because that will likely not work, as we are making backward incompatible changes for the 1.0 release. You should be able to refactor the imports to make it work though, possibly. 

I suspect you are doing that, because https://github.com/allenai/allennlp/blob/v0.9.0/allennlp/tests/modules/token_embedders/pretrained_transformer_embedder_test.py does not import `Batch`.
