### ISSUE TITLE
Question about PretrainedBertEmbedder under requires_grad=True and top_layer_only=True

### ISSUE THREAD

**Issue by izuna385** [allenai/allennlp#3900]
Question about the title.

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: 0.9
 - PyTorch version: 

**Question**
1. When PretrainedBertEmbedder is used with requires_grad=True and top_layer_only=True, which layer is fine-tuned? 12 layers all or only top?

2. For stop fine-tuning, I usually run evaluation under
```
model.eval()
with torch.no_grad():
   # evaluation with model
```
Is this sufficient for stopping fine-tuning? Or, another setting is needed?

I searched about PretrainedBertEmbedder, but couldn't find the answer.
If you'd know and write about this, I'd appreciate it.
Thanks.

**Comment by dirkgr** [comment]
* `model.eval()` puts the model into "evaluation mode". As far as I know, that just turns off dropout.
 * `torch.no_grad()` turns off gradient tracking. In a way, that's an optimization, because you don't need gradients during evaluation. You might also run out of memory if you keep it on and you evaluate a lot.

Neither of these two things causes the model parameters to change in any way. That doesn't happen until you run an optimizer step. That happens in the trainer.

**Comment by dirkgr** [comment]
`top_layer_only` is just about what the model returns. It does not affect which weights get fine-tuned. It always fine-tunes the weights from all the layers.

**Comment by izuna385** [comment]
Thanks for clarification!
