### ISSUE TITLE
Which is the NER model for current master ?

### ISSUE THREAD

**Issue by Hacker-VP** [allenai/allennlp#3998]
I'm using the latest master and for coref I downloaded a 1.3GB bert model that works with outstanding performance.

I'm also in need of a NER model , but all the models I tried have some kind of configuration errors. I think those models are not compatible with the current master. So could you please tell me which NER model works best with the current master ?

**Comment by datix-vishu** [comment]
I tried this model **fine-grained-ner-model-elmo-2020.02.10.tar** with the current master and I got Runtime Error

**Comment by dirkgr** [comment]
Like I said in the other issue, the current model URLs are in https://github.com/allenai/allennlp-demo/blob/55b05b36bcd1dd234011760e1597e2410b4a6f09/models.json. The NER model in that list works. I tried it 5 minutes ago. In the next few days I'll make some changes to put these URLs into a more discoverable place.

Also, I'll move and re-train both of the NER models into the `allennlp-models` repository before we release version 1.0. Sorry for all the churn right now, but we're trying to get it done to have a stable API once 1.0 ships.

**Comment by dirkgr** [comment]
> is there any method for NER using which I can get the named entities as a list or in a simpler way other than the standard predict method ?

I don't know the answer to that. I'm not that familiar with the NER predictors. Is it difficult to go from that output to a list?

**Comment by datix-vishu** [comment]
@dirkgr  Thanks for your help :-)

**Comment by datix-vishu** [comment]
@dirkgr which version of AllenNLP supports this model "**fine-grained-ner-model-elmo-2018.12.21.tar.gz**".

And do you know why NER is not working for the following text ?

**_Text :_** 
`arrett Allen has learned Jarrett Allen's lesson.  As Jarrett Allen has gained more attention for Jarrett Allen's powerful blocks on dunk attempts by All-Stars like Blake Griffin, LeBron James and most recently Giannis Antetokounmpo on Saturday night, Jarrett Allen did Jarrett Allen a favor.  “Jarrett Allen was smart, Jarrett Allen turned off Jarrett Allen's notifications [on Jarrett Allen's phone],” Jarrett Allen said with a grin Monday after practice. “But if Jarrett Allen check, it’s all over. Jarrett Allen see it everywhere.”  For good reason.  Unafraid to be on the wrong end of a poster, Jarrett Allen has been trying to assert Jarrett Allen around the rim in Jarrett Allen's second year as a pro. Jarrett Allen has 50 blocks through 36 games — tied for 17th in the league — but may have more highlight-reel stuffs against top competition than anyone else.  “Jarrett Allen’m not going to go up super late for one, but you’ve got to contest,” Jarrett Allen said. “Jarrett Allen’m not afraid of getting dunked on. Jarrett Allen’ll go up and try to contest and go for it.”  After blocking LeBron James two weeks ago in a win over the Lakers, most of the national conversation centered around LeBron James getting older and not the defender that actually got in the way of another of LeBron James's emphatic slams. But Jarrett Allen feels Jarrett Allen's respect is coming.  “Jarrett Allen think Jarrett Allen’m starting to get more of the recognition of Jarrett Allen’m blocking people,” Jarrett Allen said. “Obviously people’re really big names so people are starting to recognize that Jarrett Allen’m a rim protector.”  Coach Kenny Atkinson would like to see that aggressiveness every night out of Jarrett Allen. Coach Kenny Atkinson thought Jarrett Allen recently had a “little dip” in Jarrett Allen's rim protection, but was reminded of Jarrett Allen's potential impact with Jarrett Allen's block of Giannis Antetokounmpo on Saturday night.  “Coach Kenny Atkinson think we’ve challenged Jarrett Allen a little bit lately,” Coach Kenny Atkinson said. “Especially with the post-up stuff and the individual [play].  “Jarrett Allen is really good when Jarrett Allen’s aggressive. If Jarrett Allen comes with a passive or even a neutral attitude, a passive or even a neutral attitude’s not good enough. Coach Kenny Atkinson know Jarrett Allen still needs to get stronger, but it’s really that aggressiveness, that aggressiveness’s kind of the barometer whether Jarrett Allen’s really helping we or not.”  There’s another big test — in the form of 6-10 stud Anthony Davis — waiting for Jarrett Allen on Wednesday when we play host to the Pelicans at Barclays Center. 6-10 stud Anthony Davis is averaging 28.5 points and 13 rebounds per game and has established 6-10 stud Anthony Davis as one of the dominant players in the NBA.  Jarrett Allen agreed with Coach Kenny Atkinson on needing to play aggressively, especially against an opponent like 6-10 stud Anthony Davis.  “Jarrett Allen like the challenge,” Jarrett Allen said. “6-10 stud Anthony Davis’s not really a bruiser. 6-10 stud Anthony Davis’s really a skilled player. So Jarrett Allen’m looking forward to just testing Jarrett Allen's defense against 6-10 stud Anthony Davis.”  By Jarrett Allen's own admission, Jarrett Allen is not a “hype person.” Jarrett Allen won’t be watching Jarrett Allen's past blocks or dunks to get ready for big games, but pointed to a more focused mindset Jarrett Allen has been working on to get Jarrett Allen prepared each night.  Based on Jarrett Allen's recent list of big blocks, it has been paying off.  “Early on 6-10 stud Anthony Davis saw that Jarrett Allen wasn’t afraid to get dunked on,” 6-10 stud Anthony Davis said. “Jarrett Allen’s going to challenge at the rim. 6-10 stud Anthony Davis really don’t feed into, ‘Oh Jarrett Allen blocked LeBron or Jarrett Allen blocked Giannis Antetokounmpo or Jarrett Allen blocked Blake Griffin.’ 6-10 stud Anthony Davis just like that Jarrett Allen’s challenging whoever goes through Jarrett Allen. 6-10 stud Anthony Davis just think when it’s the big-name guys it gets more publicity and it’s on TV and hang posters up and stuff like that. Jarrett Allen’s never been timid since 6-10 stud Anthony Davis’ve been here.”`
