### ISSUE TITLE
What is "test_data_path" option used for during training?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#4001]
I found that besides `train_data_path` and `validation_data_path`, there is also an option for `test_data_path`. Based on my understanding, the training procedure is only related to train data and validation data, while for the test data, we use a separate command `evaluate` in AllenNLP. What is this used for for training? When I run `allennlp train` command, I didn't really see any behavior related to the test data during training, so I checked the source code and found the only place test data plays a role in is in TrainerPiece, which specify the source data for constructing the vocabulary for different fields.

**Comment by dirkgr** [comment]
1. It's used to construct the vocabulary before training. This isn't relevant if you are using wordpiece tokenization, because then the vocabulary is fixed, but it matters when you discover the vocabulary from the data.
2. If `evaluate_on_test` is `True`, it will evaluate on the test set after training has completed. We don't recommend you do this too much because it will contaminate your test set, but sometimes this is useful.
