### ISSUE TITLE
Improved release process

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4096]
Releasing the 1.0 release candidate was a little messy. We should clean it up before the big 1.0 release. Here are some requirements in no particular order:
 * We need to coordinate releases between [allennlp](https://github.com/allenai/allennlp) and [allennlp-models](https://github.com/allenai/allennlp-models) so they are released in quick succession.
 * We need to release both on pypi and make a GitHub release.
 * We want to have release notes in GitHub.
 * `allennlp-models==1.0.0` needs to depend on `allennlp==1.0.0`.
 * These versions have to have been tested together. There is a possibility that `-models` fails and the fix is in the core library, so we need to test before we push out any releases.
 * We need to release an updated docker image at the same time, so that the instructions in the README and at https://pypi.org/project/allennlp/1.0.0rc1/ work.
 * We need to update the demo to use the latest version. That means we need to run the demo with that version and smoke test it before the release.
 * We need to upload new docs to a directory that matches the version we just released.
 * Nightly release management: The nightly release version should always be `{latest released version + 0.0.1}.dev{date}`.

**Comment by epwalsh** [comment]
Now that I think about, we could release models and core at the same time from within the same CI build. It could go like this:

*Release build on core is triggered from a GitHub release:*
- Pulls master branch of models into separate directory, runs all tests
- If all tests pass, a GitHub release of models is pushed and then both models and core are built and pushed to PyPI

**Comment by schmmd** [comment]
I'd remove "We need to update the demo to use the latest version. That means we need to run the demo with that version and smoke test it before the release." as a requirement.  The demo has almost always been on a particular SHA, but it's nice to have it on a release.

**Comment by dirkgr** [comment]
> The demo has almost always been on a particular SHA, but it's nice to have it on a release.

At the very least we should indicate what version of the library is running on the demo. It's a common use case to try something in the demo, and then expect it to happen the same way in your code.

**Comment by epwalsh** [comment]
So my tentative plan for this is to add one more GitHub Actions workflow called "PyPI". This will look a lot like the current [nightly core release workflow](https://github.com/allenai/allennlp/blob/master/.github/workflows/nightly.yml) and the [models release workflow](https://github.com/allenai/allennlp-models/blob/master/.github/workflows/release.yml). Both of those workflows will be removed and absorbed into this workflow so that the core and models libraries are released together.

This workflow will only run when a GitHub release is published (and also nightly) and will include a few improvements over the existing release workflows mentioned above.

In particular, instead of being laid out in a single job it will be laid out in 3 sequential jobs:

**`build`**: The build job will run in the usual environment (with cached dependencies). It will build the package distribution files store them as an [artifact](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts).

**`test`**: The test job will run in a clean virtual environment (no cached dependencies). It will install the core and models packages from the artifact files and run `allennlp test-install`.

**`publish`**: The publish job will run in the same environment as `build`. It will just upload the package distribution files in the artifact to PyPI for both core and models.

**Comment by dirkgr** [comment]
That sounds good. `test-install` builds a Docker image as a side-effect?

**Comment by epwalsh** [comment]
That’s probably a better way to do it than it’s done now (building the Docker image in a separate workflow by installing from PyPI after the release is published). And we might as well move the docs workflow into this as well.

So then the “publish” job could also push the docs and Docker image.

**Comment by dirkgr** [comment]
That covers everything except the demo then? That's awesome!

What happens when a step fails?

**Comment by epwalsh** [comment]
The PyPI publish will be the very last step since that is irreversible. So if the workflow fails at any point before the PyPI publish, we'll just have to delete the GitHub release/tag and redo it after we have a fix, which will trigger the release workflow again.
