### ISSUE TITLE
Require new docs for new modules/classes/functions

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#415]
This might be possible with the [sphinx coverage extension](http://www.sphinx-doc.org/en/stable/ext/coverage.html).  Not sure exactly how this works, though.

**Comment by joelgrus** [comment]
it's hacky, but it shouldn't be hard to write a script that does something like this and add it to the "build docs" step

**Comment by joelgrus** [comment]
so it looks like sphinx coverage is a bad fit for two reasons

* it only checks the modules *for which you have .rst files*, which means that if you add a totally new module (but no docs) it doesn't complain
* if you include `:undoc_members:` as part of your .rst files, then it doesn't complain about functions or classes with no documentation, since it assumes they're ok. 

the second is acceptable (we could just delete all those directives) but the first is killer. let me think some more about this

**Comment by joelgrus** [comment]
this is partially solved by https://github.com/allenai/allennlp/pull/440 which fails the build if there are *modules* with no docs. it doesn't do anything with `sphinx coverage` though, that's a next step

**Comment by matt-gardner** [comment]
I _think_ that what you did in #440 basically solves the issue that I was talking about.  What else is there to do?  Is `sphinx coverage` even useful on top of your `check_docs` script?

**Comment by joelgrus** [comment]
what I did finds modules that are missing from the docs altogether

it doesn't find e.g. functions that should have docstrings but don't, etc... 

in theory sphinx-coverage gives you that, but not if your .rst files include `:undoc-members:` directives, which most of ours do (but maybe they shouldn't)
