### ISSUE TITLE
Predicate Disambiguation SrlBert

### ISSUE THREAD

**Issue by Riccorl** [allenai/allennlp#4160]
The [SrlBert model](https://github.com/allenai/allennlp-models/blob/master/allennlp_models/syntax/srl/srl_bert_model.py) in the allennlp-models package is an implementation of [this work](https://arxiv.org/abs/1904.05255). The task there is predicate disambiguation  and arguments identification/disambiguation. From the demo (and the code) it seems that it doesn't disambiguate the predicate. 

Is there the possibility to add also the predicate disambiguation task? Do you have some advice if I want to add this feature to the model?

Thank you

**Comment by matt-gardner** [comment]
There are two main ways to handle this: (1) in a model pipeline (like we have now), or (2) make both predictions in the same call to `.forward()` in some model.  Some basic pointers for both approaches:

1. If you go this route, you end up in basically the same place that the current demo works.  Our SRL demo uses a pipeline, it just uses the spacy pos tagger for predicate disambiguation.  You could imagine training a tagging model specifically on the predicate disambiguation task, and using that trained model in the SRL predictor instead of spacy's pos tagger.  Assuming you can train the tagger, doing this should not be hard.

2. If you want to have a single `forward()` that takes a sentence as input and produces multiple predicates and their arguments as output, things get a bit trickier.  The main way that I would recommend doing this would involve doing some argmax decoding step partway through the `forward()` method, computing an initial loss for that part of the network, then doing a loop over the predicted predicates and computing another loss.  Mathematically, this is identical to what was suggested in (1) above, it's just harder to implement because batching gets messy, and you have to deal with this intermediate loss computation.  Much easier to just do two separate models, which are pipelined in the same way that we currently do it.  There are other ways of training this kind of model, using REINFORCE, or SPIGOT, or other things, but they are more complicated.
