### ISSUE TITLE
Publish a Docker image with allennlp and allennlp-models

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#4222]
I think we should publish such a Docker image.  I have use for it and there's also clear community demand (see https://github.com/allenai/allennlp/issues/4217).

**Comment by epwalsh** [comment]
I agree, and would be easy to add to the GitHub Actions workflow in the models repo. What should we name the images? `allennlp/models`? Do you think we need an image for each commit, or just releases?

Personally I think just releases is fine. Having one per commit could be confusing because it's not clear which version of allennlp would be on those images and how they correspond to the `allennlp/commit` images.

**Comment by schmmd** [comment]
That might be enough...  I use releases when I can, but sometimes I can't wait until the next release and something is just fixed so I use a commit one.

**Comment by epwalsh** [comment]
That's understandable, but it would be pretty easy to install a specific commit of `allennlp-models` on top of any compatible commit of `allennlp`. We could add some instructions on how to do that in the models repo, and also include a Dockerfile to make it easy. The Dockerfile could take two build args: allennlp commit SHA and allennlp-models commit SHA.

**Comment by schmmd** [comment]
@epwalsh makes sense, we can iterate if needed.  I'm bumping this up in priority because I would use this frequently in the coming days and for the 1.0 release.
