### ISSUE TITLE
memory usage increases

### ISSUE THREAD

**Issue by icefluo** [allenai/allennlp#4231]
When i tested COREF model it is using 9GB for a lengthy article .
For normal article it use only 1GB or less

Using 1.0.rc3 model

**Comment by icefluo** [comment]
Is there any way to limit COREF memory usage and prevent container from crashing?

Is it because of the article length ?

**Comment by ZhaofengWu** [comment]
The coref model keeps in memory the embedding of all tokens in a document because there might be distant links. You may specify a maximum number of sentences to consider. See
 https://github.com/allenai/allennlp-models/blob/3c764c9a64e565a10f954707f843979bfc525c71/allennlp_models/coref/conll_reader.py#L61

**Comment by ZhaofengWu** [comment]
And if you don't want to truncate your document you might have to do some smart sliding window which might not be trivial to implement.

**Comment by schmmd** [comment]
Thanks @ZhaofengWu!  @icefluo please open a new issue if you have further questions.
