### ISSUE TITLE
Upper limit on dependencies versions

### ISSUE THREAD

**Issue by jankrepl** [allenai/allennlp#4324]
Similar issues:

- #2650

I was wondering why do you quite often limit the upper version of your dependencies. See below a list of all examples from the current `setup.py`

- `"torch>=1.5.0,<1.6.0"`
- `"spacy>=2.1.0,<2.3"`
- `"transformers>=2.9,<2.12"`
- `"filelock>=3.0,<3.1"`

Are you just afraid that the future versions of these packages are going to break `allennlp`? Or you already somehow know they will be incompatible?

In my case, I am encountering a lot of issues because of this strategy. I want to use an older version `allennlp==0.9.0` however there you assert `'spacy>=2.1.0,<2.2'`. My other dependencies, however, require more recent `spacy>2.2`.

Thanks for your response!

**Comment by matt-gardner** [comment]
We do this because newer versions of these libraries have broken our build / made our code crash. We now use a bot to automatically update our dependencies when new versions come out, so we can see if something breaks.  This unfortunately doesn't help you with 0.9, but newer versions have more up-to-date dependencies.
