### ISSUE TITLE
Word embedding in BERT can be the first/last subtoken embedding?

### ISSUE THREAD

**Issue by tomohideshibata** [allenai/allennlp#4363]
In v0.9.0, when we use BERT, the contextualized word embedding is set to be the first (or last) subtoken embedding (in `BertEmbedder`).

However, in v1.0.0, the contextualized word embedding is set to be the average of all the embeddings of the subtokens in a word (in `PretrainedTransformerMismatchedEmbedder`).

The former treatment (v0.9.0) is adopted in the original BERT paper, and so this option will be added again in the future?

Thanks.

**Comment by dirkgr** [comment]
That's pretty easy to do. I'd love to review a pull request adding a flag that does this!

**Comment by prajaktakini-vmware** [comment]
@dirkgr I would like to work on this issue. 
What would you suggest, should we go with flag based approach where based on flag passed in args, returning first subtoken embedding instead of returning an average of all subtoken embeddings?
In v0.9.0, we have followed an offset based approach. I could not understand that pretty well. Would you like to shed some light on it? 
Do we want to follow the same offset approach here too? Or flag based would be better, what do you think?
Also, I think, Returning the first subtoken embedding looks to be the right thing to do instead of returning the last subtoken embedding.
eg. If we consider the token " ALLENNLP", that gets further tokenised as "ALLEN", "##NL", "##P" by word piece tokeniser.
Here "ALLEN" captures more info than the last subtoken i.e "#P". 
Please suggest which one would be better, first or last subtoken embedding?

**Comment by prajaktakini-vmware** [comment]
Sure, thanks. I would go with flag based approach with possible value as "first". If the flag not specified, it would fall back to the current sum based approach.

Please assign it to me. I would hopefully raise PR in next few days

**Comment by tomohideshibata** [comment]
@prajaktakini-vmware 
I am who raised this issue. Sorry for leaving this untouched.
Thank you very much for adding options for fixing this issue!
