### ISSUE TITLE
Multi-threaded execution on the demo

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#443]
When @joelgrus and I first enabled a multi-threaded web application, PyTorch threw some exceptions that we did not want to investigate.  To avoid this issue, we created 4 replicas of the demo.  However, a multi-threaded application would be more performant, as it would allow parallel usage without incurring a large memory requirement per "thread".  Presently, each replica requires 2 GB of memory, and this requirement will only increase as we add more models.

**Comment by joelgrus** [comment]
two data points:

(1) I spent some time digging into where num_workers=2 crashes, and it's when pytorch makes a call to BLAS. That makes me suspect that it's going to be hard to fix this, because it looks something that's happening in C.

(2) even with one worker you can hammer the server and it's pretty OK? like, I just set up the server locally, queued up 100 requests against backend, and then tried to use the demo at the same time. it was a little slower than usual, but not hugely so, and everything still worked, so I'm not sure this is that big a deal (at least, not for demo purposes, if we want to really serve models at scale we'll probably have to do something that's not sanic or flask anyway)

**Comment by schmmd** [comment]
Thanks for the details. I agree it's low priority for now. Hopefully a PyTorch upgrade fixes it.

**Comment by grahamannett** [comment]
Ran into same issue for project im working on.  Not entirely sure but wouldn't using sanic workers not be multithreaded, the name implies multiple worker processes, each worker is still single threaded and seems to be an issue with sanic itself (no idea but how it forks the process probably, and would still result in more memory since each worker still has its own 'independent memory space') not with pytorch since running from gunicorn with
```
gunicorn server:app --worker-class sanic.worker.GunicornWorker --workers 1 --threads 2 
```
works perfect and uses same memory footprint as running via sanic directly and allows parallelism 

and even 
``` 
gunicorn  server:app --worker-class sanic.worker.GunicornWorker --workers 2 
```
works fine as well (which would be similar to how sanic uses workers=N i believe) but has a larger memory footprint.  

Just fyi

**Comment by matt-gardner** [comment]
I'm guessing this will be addressed by a re-engineering of the demo architecture, separating different models?  Closing this.

**Comment by schmmd** [comment]
Yes, it would (and it's tracked on allennlp-demo).
