### ISSUE TITLE
BERT sliding window embedding size smaller than number of tokens

### ISSUE THREAD

**Issue by j6mes** [allenai/allennlp#4430]
I have a question about the behaviour o embeddings generated by BERT for long token sequences.

I'm aware there is some functionality for generating embeddings using a sliding window approach (#2537) -- and in v1.0.0 of allennlp, I no longer get warnings about long sequences being truncated (so I assume that embeddings are now generated with a sliding window for long token sequences.  

With a batch-size of 1, I would expect the length of the textfields and length of the embeddings generated by BERT to be equivalent. However, in a simple SQuAD style evaluation with an input sequence of 1088 tokens I am finding that my embedding size is only 1080 after using the BERT embedder. I have added this assertion which fails:

```
    def forward(  # type: ignore
        self,
        question_with_context: Dict[str, Dict[str, torch.LongTensor]],
        context_span: torch.IntTensor,
        answer_span: Optional[torch.IntTensor] = None,
        metadata: List[Dict[str, Any]] = None
    ) -> Dict[str, torch.Tensor]:
        embedded_text = self._text_field_embedder(question_with_context)
        assert embedded_text.shape[1] == question_with_context["tokens"]["token_ids"].shape[1], "Expected embedding size and sequence length to be equal, but instead got an embedding size of {} for {} tokens".format(embedded_text.shape[1], question_with_context["tokens"]["token_ids"].shape[1])
```

```
AssertionError: Expected embedding size and sequence length to be equal, but instead got an embedding size of 1080 for 1088 tokens
```

If this is expected, how would the original tokens map to the embedded tokens? If it is not expected, what could the source of the issue be? Could it be something silly I'm doing?

Thanks

**Comment by matt-gardner** [comment]
Whether that assertion should be valid depends entirely on the token indexer that you're using.  Can you tell me what that is?  If you're using a mismatched indexer (or, for pre-1.0 code, a BertIndexer, or whatever we called it), then this assertion will fail by design.  See [this chapter of the guide](https://guide.allennlp.org/representing-text-as-features) for how these options work.

If you're *not* using a mismatched indexer, then I would expect that assertion to work, though I might be missing something about the context.

**Comment by j6mes** [comment]
Hi @matt-gardner - thanks for the fast reply.  I'm running the following install and using the bert-base-uncased tokenizers.

```
allennlp==1.0.0
transformers==2.11.0
```

With a config like this:

```
local transformer_model = "bert-base-uncased";
local transformer_dim = 768;

{
    "dataset_reader": {
      "type": "squad_variant",
      "token_indexers": {
        "tokens": {
          "type": "pretrained_transformer",
          "model_name": transformer_model,
          "max_length": 256
        },
      },
      "tokenizer": {
        "type":"pretrained_transformer",
        "add_special_tokens": false,
        "model_name": transformer_model
      }
    },
    "model": {
        "type": "bert_squad_variant",
        "text_field_embedder": {
          "token_embedders": {
            "tokens": {
              "type": "pretrained_transformer",
              "model_name": transformer_model,
              "max_length": 256,
          },
       }
     ...
   },
   ...
```

There might be something fishy with using part of the old squad reader from the archived `allennlp_rc` repo. But I've done a good job at porting it to 1.0, using the tokenizer and token indexer that are constructed from the config file rather than hard-coding their constructors (like the original allennlp_rc repo had).

My dataset reader constructing a textfield that looks something like this:

```
        # make the question field
        cls_token = Token(
            self._tokenizer.tokenizer.cls_token,
            text_id=self._tokenizer.tokenizer.cls_token_id,        
            type_id=self.non_content_type_id,
        )

        sep_token = Token(
            self._tokenizer.tokenizer.sep_token,
            text_id=self._tokenizer.tokenizer.sep_token_id,
            type_id=self.non_content_type_id,
        )

        all_toks = [cls_token] \
                + tokenized_question \
                + [sep_token, sep_token] \
                + canned_answers \
                + [sep_token] \
                + tokenized_context \
                + [sep_token] \

        question_field = TextField(
            all_toks,
            self._token_indexers,
        )
```

I first had an issue with a sequence of 550 tokens that was embedded in 768x546 dimensions, but I can't seem to replicate that now. The assertion does still fail when I artificially make my context more than 1000 tokens though.

**Comment by matt-gardner** [comment]
Hmm, it's possible there's a bug somewhere when the contexts get really long.  Two thoughts: 

1. You mention the `allennlp_rc` repo; we do still have a reader in the [`allennlp-models` repo](https://github.com/allenai/allennlp-models); we just changed our plans on how exactly we were going to split things.  Not sure if that's helpful for you or not.

2. Can you construct an input for which the code reliably fails?  If so, it would be great to have that as a failing test case that we can try to figure out.  Looking at the input would likely tell us what the problem is, because this does sound like a bug to me.

**Comment by j6mes** [comment]
It's a tricky one to reproduce, but I've got a repeatable instances where it works and where it fails.

The `transformer_bug.py` in the zip file contains a set of unit tests that perform the tokenization and embedding for a single instance on the CPU and there doesn't appear to be any problem here with the sliding window for the text field embedder. But I did spot an issue with the `max_length` property for the tokenizer where if you encode a sequence with a length greater than the max_length. The CLS and SEP tokens are not counted and the new token list is longer than max_length by 2 characters. Apart from that, there were no issues.

When I create a synthetic dataset reader which creates a sentence_pair encoding for squad, I'm hitting that assertion again. I've stripped out most of the clutter from the SQuAD readers (both allennlp-rc and allennlp-models variants) and am struggling to see how it differs to the working test cases in the standalone file.

[allennlp issue 4430.zip](https://github.com/allenai/allennlp/files/4864255/allennlp.issue.4430.zip)

**Comment by matt-gardner** [comment]
Ok, got it.  I wasn't really familiar with how we handled long sequences, but now I know a bit more.  The key issue is this: if you look at the number of tokens in your `TextField`, it's the same as the number of embeddings you get out of the `TextFieldEmbedder` (this is the fundamental contract that AllenNLP upholds).  So the reason there are extra tokens in the `'token_ids'` tensor is because they were added to signal where to break up segments for the sliding window encoding.  You can see this if you just decrease the max length in your config file; the lower it is, the larger the discrepancy between the two numbers you're comparing.

If you want to see the code where this happens, look here for where the extra tokens are added: https://github.com/allenai/allennlp/blob/60deece9fca2da6b66bfcde44484384bdefa3fe7/allennlp/data/token_indexers/pretrained_transformer_indexer.py#L149-L182 (and hence they show up in the `"token_ids"` tensor), and here for where they are removed: https://github.com/allenai/allennlp/blob/60deece9fca2da6b66bfcde44484384bdefa3fe7/allennlp/modules/token_embedders/pretrained_transformer_embedder.py#L201-L235
