### ISSUE TITLE
How can we tokenize sentence pair with 'PretrainedTransformerTokenizer'

### ISSUE THREAD

**Issue by wlhgtc** [allenai/allennlp#4532]
@dirkgr  Seem the new version code remove  @ZhaofengWu 's changes to support sentence pairs in #3868 
How can we tokenizer sentence pair in 1.1.0 ?

**Comment by wlhgtc** [comment]
@ZhaofengWu  I read your discussion in #3868, but still confused with the change.
What changes leads no support for sentence pair  or  any other ways to do it ? Maybe you could help me ?

**Comment by dirkgr** [comment]
Use `PretrainedTransformerTokenizer.add_special_tokens()`. Make sure that the input you pass to that function doesn't have special tokens in it already.

The reason I split it this way is because we were on the path of creating a single `tokenize()` call that does everything, like huggingface has. I don't think that's a good design. I think we need to have separate functions for tokenization, adding special tokens, splitting long sequences, and so on. This was one step in that direction. Sadly, for backwards compatibility, we didn't fully commit to it, so all we have is the `add_special_tokens()` call. I am hoping to rectify that situation later.

**Comment by wlhgtc** [comment]
@dirkgr   Thanks for your quickly reply. 

In my view, suppose the 2 part is  `tokens2` and `tokens2` code is as follows ?
```
def text_to_instance(tokens1:str,tokens2:str)
    ...
    tokens1 = self.tokenize(pair1)
    tokens2 = self.tokenize(pair2)
    concat_tokens = self.add_special_tokens(tokens1, tokens2)
    field['tokens'] = TextField(concat_tokens, self._token_indexers)
    ...
```

**Comment by dirkgr** [comment]
That is correct!

**Comment by wlhgtc** [comment]
Case solved, close this issue
