### ISSUE TITLE
Use model(**inputs) rather than model.forward(**inputs)

### ISSUE THREAD

**Issue by OyvindTafjord** [allenai/allennlp#456]
Follow up from email discussion, we should change usages of `model.forward(**inputs)` to `model(**inputs)` as the invoked `__call__` method for `torch.nn.Module` also includes some handling of hooks (code [here](https://github.com/pytorch/pytorch/blob/53b01527f446c1940e2dc1c2023575e51d93919c/torch/nn/modules/module.py#L316)). 

I don't think there are currently known issues from this, so low urgency, but could arise, say, if adding hooks to a model and then running predictions.

**Comment by DeNeutoy** [comment]
FYI The reason this is like this is because previously backward hooks weren't compatible with signatures of forward which returned dictionaries, which we fixed in Pytorch: https://github.com/pytorch/pytorch/pull/2037

This was merged on Oct 1st, so actually I'm not sure we should fix this until pytorch release again, because adding a backward hook to one of our models will make it crash (I think).
