### ISSUE TITLE
**kwargs handling is not ideal when interfacing with non-FromParams code

### ISSUE THREAD

**Issue by EazyReal** [allenai/allennlp#4592]
I am encountering

```
 File "/opt/conda/lib/python3.7/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 96, in __init__
    super(RGCNConv, self).__init__(aggr=aggr, node_dim=0, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'serialization_dir'
```
To my understanding, this is because **extras is passed to **kwargs, so the `__init__` of `MessagePassing` in pytorch_geometric reported an error.

Is there a way to prevent **extra to pass to a certain `Registrable`?  In my case, `Graph2GraphEncoder`.
Thanks!

Here is my code for `Graph2GraphEncoder`.
```
from typing import Callable

import torch
import torch_geometric ## nn __init__ has from .conv import * can use directly
from overrides import overrides

from allennlp.common import Registrable
#from torch_geometric.nn import GATConv, RGCNConv, CGConv

"""
An `Graph2GraphEncoder` is known as `GraphConvolutionLayer`
that takes some graph input and return its updated version.
For the most part we just use
[PyTorch Geometric GraphConvs](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html).
Here we provide a thin wrapper to allow registering them and instantiating them `from_params`.
The available options are
* ["gat"](link_to_gat)
* ["rgcn"](link_to_rgcn)
"""


class Graph2GraphEncoder(torch.nn.Module, Registrable):
    """
    A `Graph2GraphEncoder` is a `Module` that
    takes a graph and returs its updated version
    
    the API to outside world are `self.in_channels`, `self.out_channels`
    
    Input shape :
        `(SparseBatch, SparseGraphBatch)`;
    output shape:
        `(SparseBatch, SparseGraphBatch)`.
    """
    
    def get_input_dim(self) -> int: # not used
        """
        Returns the dimension of the vector input for each element in the sequence input
        to a `Seq2VecEncoder`.
        """
        return self.in_channels
        
    def get_output_dim(self) -> int: # not used
        """
        Returns the dimension of the final vector output by this `Seq2VecEncoder`.  This is `not`
        the shape of the returned tensor, but the last element of that shape.
        """
        return self.out_channels
        #raise NotImplementedError


class _Graph2GraphEncoderLambda(torch.nn.Module):
    """
    Wrapper around non PyTorch, lambda based Graph2GraphEncoders
    to display them as modules whenever printing model.
    """

    def __init__(self, func: Callable[[torch.Tensor], torch.Tensor], name: str):
        super().__init__()
        self._name = name
        self._func = func

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self._func(x)

    @overrides
    def _get_name(self):
        return self._name


# There are no classes to decorate, so we hack these into Registrable._registry.
# If you want to instantiate it, you can do like this:
# <T:Registrable>.by_name('relu')()
Registrable._registry[Graph2GraphEncoder] = {
    "gat": (torch_geometric.nn.conv.GATConv, None),
    "rgcn": (torch_geometric.nn.conv.RGCNConv, None), 
    # "linear": (lambda: _Graph2GraphEncoderLambda(lambda x: x, "Linear"), None),  # type: ignore
}

```

**Comment by EazyReal** [comment]
By the way,
I currently bypass the problem by simply modify RGCNConv from the source of pytorch_geometric.
But I think it is not a healthy way to do it (for every classes that takes `**kwargs`, I have to comment **kwargs` to use it).
Is there a better way to achieve a similar result?

**Comment by matt-gardner** [comment]
I'm pretty sure that the problem is that the `torch_geometric` classes don't inherit from `FromParams`, so the code that we have that handles `**kwargs` and such isn't operating correctly, because it basically gives up with it encounters something that doesn't inherit from `FromParams`.  I checked the `torch_geometric` code, though, and it uses type annotations on its constructor arguments (yay!), so we could conceivably be able to have things just work.

I see three potential solutions here:

1. Make it so that you don't need to inherit from `FromParams` to have an object be constructed using `FromParams`, as long as it has type annotations (and all of the objects it creates also have type annotations).  This would also let us remove the need to inherit from `FromParams` in our own code (except for a few circumstances where we need special handling), which would be a nice simplification.
2. Figure out a more local bugfix for this particular problem.  We'd need a better stack trace to even diagnose why exactly this is happening, but I _think_ the code is going through [this logic](https://github.com/allenai/allennlp/blob/f464aa38629979ff3f4974bea0e625d4d3a28bc1/allennlp/common/from_params.py#L584-L592), where we basically give up.  It might be reasonable to just remove the `**extras` there, as they probably aren't needed at that point.  I'd have to see if this breaks any of our tests.
3. You make little shims in your code to add compatibility between `torch_geometric` classes and `FromParams` instantiation.  This is what we did for, e.g., [pytorch's RNNs](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py), and several other places.

The first one is something that I'd like to do anyway, but is pretty involved and is not high on our priority list right now.  The second is very simple and it will probably work, but needs some testing to be sure it doesn't break anything.  The third is something you can do in your own code without needing to change allennlp, though it's a bit more annoying for you.

If you want to submit a PR for option 2 (or even option 1!), contributions welcome.

**Comment by EazyReal** [comment]
Thanks for your reply. 
I now fixed it with way 3, which may not be the best way but is enough for my development of my experimental model now.

There is an additional question, though.
My model is now overfitting, and when I try to add `L2 Regularizer,` I found the document is almost empty.
I can inference the usage by the document provided by the `InitializerApplicator`.
But to my knowledge (from config files), the examples in `allennlp-model` repo are not using regularization, why is that?

And a final point, if I want to ask questions (maybe not about a `feature request` or `bug`), where should I comment?

**Comment by matt-gardner** [comment]
> There is an additional question, though.
> My model is now overfitting, and when I try to add `L2 Regularizer,` I found the document is almost empty.
> I can inference the usage by the document provided by the `InitializerApplicator`.
> But to my knowledge (from config files), the examples in `allennlp-model` repo are not using regularization, why is that?

Some optimizers also have a "weight_decay" option, which is regularization that happens in the optimizer instead of the loss.  Several of the models have non-zero weight decay values.  If all you need is L2 regularization, that's the easiest way to get it.  If you want something different, you can use the other regularizers we have.

> And a final point, if I want to ask questions (maybe not about a `feature request` or `bug`), where should I comment?

We have a [discourse forum](https://discourse.allennlp.org/) that's our recommended spot for asking questions.  We like to keep github issues for things that require changes to the code.
