### ISSUE TITLE
How I can use Masked Language Modeling in Python

### ISSUE THREAD

**Issue by taicaile** [allenai/allennlp#4594]
Hello,

I am running demo of  Masked Language Modeling task in <https://demo.allennlp.org/>,  I want to confirm if I can use the same model in Python by install allennlp?

Thanks.

**Comment by matt-gardner** [comment]
Yes, you can!  The model can be found here: https://storage.googleapis.com/allennlp-public-models/bert-masked-lm-2019.09.17.tar.gz.  You load it with `predictor = Predictor.from_archive(the_url_above)`, and you can call `predictor.predict("some [MASK] string")`.

**Comment by NinaTian98369** [comment]
> Yes, you can! The model can be found here: https://storage.googleapis.com/allennlp-public-models/bert-masked-lm-2019.09.17.tar.gz. You load it with `predictor = Predictor.from_archive(the_url_above)`, and you can call `predictor.predict("some [MASK] string")`.

Thanks @matt-gardner! 

One additional question that would appreciate your answer: is it possible to get more than five predictions for each [MASK] in Python? Also curious if it's possible to get probability for a specific word, just like https://github.com/huggingface/transformers/issues/547#issuecomment-692616754. Thank you.

**Comment by matt-gardner** [comment]
You can see [here](https://github.com/allenai/allennlp-models/blob/dd368903a85a4590da5db92c17d1a429c15760a3/allennlp_models/lm/models/masked_language_model.py#L132) that the value of 5 is hard-coded into the model.  You'd have to change that in order to get more than 5 values out.  Perhaps best to just add a constructor parameter to set that threshold value.  Also you could imagine adding an output that returns the probabilities of the target ids; we already compute a loss, from which you could derive the probabilities, but that's a bit annoying.

You could do this by just copying that model and modifying it as you which; a PR to submit those particular changes back would be welcome.
