### ISSUE TITLE
Can't load a model from a readonly file system because of Filelock

### ISSUE THREAD

**Issue by theashworld** [allenai/allennlp#4838]
Basically see here https://github.com/allenai/allennlp/blob/b7cec515448f46daec9a76551d0a3342ef51b27b/allennlp/data/vocabulary.py#L341 the `FileLock` tries to lock the file in the same directory as the model. This means that if the model is not on a writable file system, it will not be able to get a lock and fails. Existing code
```
        # We use a lock file to avoid race conditions where multiple processes
        # might be reading/writing from/to the same vocab files at once.
        with FileLock(os.path.join(directory, ".lock")):
```

This seems like an unnecessary restriction, why should we not be able to load the model from a readonly file system. More specifically, a docker image can be run on another machine where assumptions about the machine cannot be made, (e.g AWS Lambda)

Ideally, given that we have a cache directory, why not hold the `.lock` file in the cache directory. It is a fair assumption that the cache dir is writable.

**Comment by epwalsh** [comment]
Thanks for bring this up @theashworld. I actually ran into this issue yesterday with `.lock` files that were in the cache directory (the root user was writing to the cache, but a non-root user needed to read from the cache).

I think a reasonable solution would be to issue a warning when we are trying to **read** a resource (like a vocab or something from the cache) but can't get a handle on the file lock due to a permissions issue, and then just ignore the lock and continue reading.

What do you think?

**Comment by theashworld** [comment]
> I think a reasonable solution would be to issue a warning when we are trying to read a resource (like a vocab or something from the cache) but can't get a handle on the file lock due to a permissions issue, and then just ignore the lock and continue reading.


That would be great! :-)

**Comment by epwalsh** [comment]
Thank you @github-actions, can't you see that I made a PR???
