### ISSUE TITLE
A serialization directory isn't created in v2.0.0 GradientDescentTrainer?

### ISSUE THREAD

**Issue by himkt** [allenai/allennlp#4939]
- reproduce code: https://gist.github.com/himkt/beda05df92699de726a527bd1ad64d71

In AllenNLP v2.0.0, `GradientDescentTrainer.train()` doesn't create a serialization directory, which is inconsistent with v1.x.x, I think. I couldn't find any mention of this behavior in the release note. Is this an intended change?

**Comment by epwalsh** [comment]
This was not intended. I'm guessing the only reason `GradientDescentTraininer.train()` created the directory before was because the `TensorBoardWriter` class would create the directory if it didn't exist, but now the `TensorBoardWriter` isn't used by default.

But if you'd like to make a PR on the `GradientDescientTrainer` to create the directory when it's instantiated, I think that would be good to have.

**Comment by himkt** [comment]
Closed in #4940. Thank you for the quick review!
