### ISSUE TITLE
miss O in allowed_transitions ?

### ISSUE THREAD

**Issue by flyangovoyang** [allenai/allennlp#5210]
https://github.com/allenai/allennlp/blob/79d16af1f9d719934a1aa4a3506482c05e24aae6/allennlp/modules/conditional_random_field.py#L14-L56

https://github.com/allenai/allennlp/blob/79d16af1f9d719934a1aa4a3506482c05e24aae6/allennlp/modules/conditional_random_field.py#L138-L154

according to the codes above, O -> B-PER is not allowed when calling:

```python
id2tag = {0: 'O', 1: 'B-PER', 2: 'M-PER', 3: 'E-PER', 4: 'S-PER'}
allowed_transitions('BMES', id2tag)
```

**Comment by AkshitaB** [comment]
@flyangovoyang Can you clarify a bit more? From my understanding, the `BMES` tagging scheme is character-based sequence labeling, rather than words. Each character in the text would either be the beginning, middle, or end character in a word, or else a single character word. So, for this tagging scheme, you would never expect to transition to/from `O`.
