### ISSUE TITLE
Add a "disable_tqdm" flag to all commands, not just Trainer

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#524]

**Comment by matt-gardner** [comment]
By "commands", do you mean things like "evaluate", "predict", etc.?  Or do you mean the dataset readers, indexers, etc.?  The trouble is that either it's really verbose to specify this individually in the config file everywhere you want to disable a tqdm bar, or you need some global state that gets passed around somehow to everywhere that needs it...  Maybe there's some crazy hack that would let us globally replace all `tqdm` imports.  I'm not sure that we should use such a crazy hack even if it existed, though...

Maybe we could introduce a `ProgressBar` interface, and have it either pass through to `tqdm` or use simple logging statements.  This would be much like what `Trainer` has now, except made a bit cleaner.  And then this class could have a class variable that sets which implementation to use, and that class variable could be set globally by the base command.  Then we only have to set the flag once, and everywhere that uses a progress bar is affected by it.  There's still some global state, but it's just a little bit, and it's only affecting how logging statements are printed, so it doesn't feel that bad (e.g., we already have global state in `logging` that we modify, for very similar reasons).

Getting this API right is a little tricky, though, because you have to mimic tqdm correctly.

**Comment by DeNeutoy** [comment]
I meant for the `evaluate` and `predict` commands. This arose because Nikett was evaluating on the test data within the `train` command, which calls `evaluate` - the ouput in the Beaker logs is not nice:
http://beaker.allenai.org/ex/ex_xxksjeu41a9b
see the last line of the preview of the logs. Maybe we just need to add that `TeeLogger` feature back in which appends `\n` to lines, which would solve most of the issue here.

**Comment by matt-gardner** [comment]
Oh, yeah, our TeeLogger used to do this for keras-related stuff.  If we could figure out a way to make that work for tqdm, that'd be an easier way to get the global behavior we want.  Seems like it could easily get _really_ hacky, though...

**Comment by DeNeutoy** [comment]
Fixed by #722
