### ISSUE TITLE
'optional' multitask scheduler is not optional

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp#5346]
The docstring for the `MultiTaskDataLoader` indicates the `scheduler` argument is optional

https://github.com/allenai/allennlp/blob/311f1104bf4762b7b5c1172eb874276343d562c9/allennlp/data/data_loaders/multitask_data_loader.py#L54

However, it's declared as a required positional argument 

https://github.com/allenai/allennlp/blob/311f1104bf4762b7b5c1172eb874276343d562c9/allennlp/data/data_loaders/multitask_data_loader.py#L106

And I don't see any indication that if not supplied it's set to `HomogeneousRoundRobinScheduler`

**Comment by amitkparekh** [comment]
I don't work for AllenAI, but I was wondering the same thing. 

For AllenNLP to work out-of-the-box, modules will have some necessary requirements. To reduce overhead for new people as they're likely to use defaults anyway so could omit it anyway. 

Modules in AllenNLP are designed such that `Registrable`'s (like `MultiTaskScheduler`) have a `default_implementation` attribute. All modules from `Registrable` that I've used (YMMY) have the `default_implementation` attribute. 

This behaviour is mentioned in the documentation for `Registrable`.

https://github.com/allenai/allennlp/blob/90bf33b899fd3f2a59c87b27f5b5d24062746ef4/allennlp/common/registrable.py#L33-L34

As for why, I assume maybe performance?

**Comment by david-waterworth** [comment]
So are you saying that if the configuration doesn't contain `scheduler` then `from_params` will construct a `default_implementation` even though the type isn't annotated with Optional[MultiTaskScheduler]?

**Comment by amitkparekh** [comment]
Yup!

That's my understanding because the documentation indicates it's optional if building a model using the configs. 

When you look at the class on it's own, it _needs_ a scheduler to work. If you import and use the `MultiTaskDataLoader` in a python module, then the `MultiTaskScheduler` is needed for it to work. 

But since using configs are not strongly-typed, it's easier to use a common-sense default instead of sending users loads of errors.

**Comment by david-waterworth** [comment]
Cool thanks!
