### ISSUE TITLE
we need better documentation about what to put in a config file

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#546]
this has several components

* for sure all of our `from_params` methods need much clearer documentation about what their params should look like
* we should consider avoiding using implicit default "type" parameters in our example code, I think it's potentially confusing
* we probably need a tutorial on this (or possibly just to expand the `configuring a model` tutorial)

**Comment by matt-gardner** [comment]
We decided early on to omit docstrings for `from_params`, because they duplicate the parameters in the class docstring.  The assumption there is that anything that shows up in the constructor can be specified in the params, and you only need docs if that's not true.

It'd be pretty amazing if we had a page in our docs that let you interactively walk through all of the configuration options, starting with the command to `run.py`.  It might be possible to write a script to do this, by walking through the code and examining all of the calls to `from_params`.  Probably more work than it's worth, though...

**Comment by matt-gardner** [comment]
If we adopted a particular convention for documenting `from_params`, we could probably make such a script way easier to write, and such an interactive page possible.  If adding some documentation for all of our `from_params` methods results in such a page, I'd say it's _definitely_ worth it, even if it duplicates information in the class docstrings.

**Comment by schmmd** [comment]
One idea is to build a React APP to help users build configurations.

**Comment by matt-gardner** [comment]
@joelgrus, just going through some old issues.  I think we're really close on this one.  Maybe add getting your config explorer up somewhere as a Q4 goal?

**Comment by schmmd** [comment]
Closing, since we've released a beta version of the config explorer.  See https://github.com/allenai/allennlp/pull/2118
