### ISSUE TITLE
Make checklist an optional dependency

### ISSUE THREAD

**Issue by AkshitaB** [allenai/allennlp#5483]

**Comment by h-vetinari** [comment]
What's the intention behind making checklist optional? Are people having problems installing that package somehow?

I can follow this PR in conda-forge and have `allennlp` without checklist, `allennlp-checklist` with checklist, as well as `allennlp-all`, but first I wanted to understand if this is even necessary, because conda-forge might not be having the same problem...

CC @dirkgr @epwalsh

**Comment by dirkgr** [comment]
The `checklist` package has a huge number of dependencies that most people don't care about. I think it was responsible for well over half of all of our recursive dependencies.

**Comment by h-vetinari** [comment]
OK. I presume the best is then to mirror the setup here in conda-forge (and add the correct installation instructions for conda-forge to the notes/warnings - I can probably raise a PR for that).

**Comment by dirkgr** [comment]
:+1:
