### ISSUE TITLE
cannot import name 'allowed_transitions' from 'allennlp.modules.conditional_random_field'

### ISSUE THREAD

**Issue by KaiyeYang-git** [allenai/allennlp#5695]
I can't import the tweetnlp package with this warning tags, also coming with this address:'Programs\Python\Python39\lib\site-packages\allennlp\modules\conditional_random_field\__init__.py'. 

Does anyone know what happened?

**Comment by iamlockelightning** [comment]
+1

**Comment by erzaliator** [comment]
I have run into the same issue. I am running allennlp==2.10.0 and allennlp-models==2.10.0 . I have to stick to this constraint: allennlp>=2.0,<3.0
But I haven't been able to solve this issue.

**Comment by iamlockelightning** [comment]
Have made a PR(https://github.com/allenai/allennlp/pull/5697) and waiting for reviewing.

**Comment by erzaliator** [comment]
So I found that the code was importing sub modules recursively. I went to the respective python scripts that this code was recursively referring to and corrected the imports. 
The code base was old and I have to change the sciprts to refer to the new path: `import allennlp.modules.conditional_random_field.conditional_random_field` instead of `import allennlp.modules.conditional_random_field`

**Comment by KaiyeYang-git** [comment]
Here comes solutions where I solved it already.
https://github.com/cardiffnlp/tweetnlp/issues/3
