### ISSUE TITLE
Weird comma swapping in demo

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#601]
Noticed in the demo @codeviking gave today: http://demo.allennlp.org/semantic-role-labeling/NTc1OA==.  The comma gets moved to after "which" in the heirplane visualization.  This doesn't happen in the text visualization.

**Comment by matt-gardner** [comment]
Interestingly, also, this only happens on the first verb - when you click over to the second verb, the comma goes back to where it should be.

**Comment by codeviking** [comment]
Interesting.  Punctuation handling in `hierplane` is a bit tricky.  I'll take a look first thing on Monday.  Thanks!

**Comment by schmmd** [comment]
@codeviking hi Sam, this isn't urgent (and doesn't need attention) but I'm pinging you in case you forgot to look at this yet want to.

**Comment by codeviking** [comment]
Doh.  I did.

It'd likely be good to have @aaronsarnat take a look, since he's officially taking over Hierplane.  @aaronsarnat would you have time before sabbatical to take a look?

**Comment by codeviking** [comment]
Also, @schmmd I can't for some reason assign @aaronsarnat, so if that works for you (and Aaron) let's swap it into his court.

**Comment by aaronsarnat** [comment]
My pre-sabbatical responsibilities have expanded recently, so give me a few days to follow up on this.

**Comment by codeviking** [comment]
Fantastic, thanks @aaronsarnat !

**Comment by aaronsarnat** [comment]
Sorry, what I meant by "follow up" is I need to check w/ Mark H. about this ask relative to my other priorities which have increased in scope this month. I want to help if I can, but am already on borrowed time. Will circle back here tomorrow after I've had my 1:1 w/ Mark.

**Comment by aaronsarnat** [comment]
@codeviking when this came up before, had you by chance done any investigation yet to get a sense for the nature of the problem or what kind of time might be involved in addressing it? If so, this might be helpful to know when I'm talking w/ Mark.

**Comment by codeviking** [comment]
No clue, unfortunately.

The way punctuation is handled is currently pretty hacky, as you know.  It could be a straightforward fix -- it also could be as simple as an issue with the data (I'd start by inspecting the returned parses and see if the comma is in fact being put in a different location).

If it's related to the data, it's super easy, in that you just have to note this and punt it back to Michael :).  If it's not that, we'll have to assess how hard it'll be to fix -- and it might be "won't fix" for now given the state of how the lib under the hood handles punctuation.

**Comment by DeNeutoy** [comment]
I think this is caused by the way we are adding reference nodes to spans. In the example Matt gave above, [The keys] is a span, which then gets a `Node` added to it by [which], which is rendered before the ignored spans from the [The keys] `Node`, which (hopefully) includes the comma. I'm not exactly clear on how the `ignoredSpans` are rendered with respect to the `text` from a `Node` though.

**Comment by aaronsarnat** [comment]
Hey guys, sorry I haven't followed up yet. Mark H. is out of office this week, so haven't caught up with him yet about this. Briefly chatted w/ Michael and it sounds like this issue is not a super high priority. I've got this item on my "nice to have" list and would like to help if I can, but need to crank through some of the bigger ticket items on my list first before I go on break.

I will check back in on this in the coming weeks to see how things are shaping on on my end.

And thanks @DeNeutoy for the investigation!

**Comment by matt-gardner** [comment]
Closing this in favor of the issue on the demo repo.
