### ISSUE TITLE
Data pipeline tutorial issues

### ISSUE THREAD

**Issue by ChristophAlt** [allenai/allennlp#610]
While working through the data pipeline tutorial (http://allennlp.org/tutorials/data-pipeline), I noticed a couple of things:

1. when installing allennlp v0.2.3 via pip (python 3.6.1), the tutorial fails, because at this point Dataset has no as_tensor_dict(..) method.

2. in the second example, in
```
print(vocab.get_index_to_token_vocabulary("tokens"), "\n")
.
print(vocab.get_index_to_token_vocabulary("chars"), "\n")
```
"vocab" should be replaced with "word_and_char_vocab"

3. there is a missing comma between "good" and "." in line
```
review2 = TextField(list(map(Token, ["This", "movie", "was", "quite", "slow", "but", "good" "."])), token_indexers={"tokens": SingleIdTokenIndexer()})
```

**Comment by matt-gardner** [comment]
@joelgrus, @schmmd, issue 1 is a fundamental problem with how our systems are set up.  In order to merge a PR that updates an API, I have to update the notebook tutorials so that CI passes.  Those tutorials then get deployed on merge, which makes them out of sync with our pip version.  I don't think we actually want to automatically deploy our tutorials, or we need to have them versioned.

For 2 and 3, I'm not sure how these are passing tests.  @DeNeutoy, shouldn't the notebook test be failing if there's invalid syntax?  Oh, nevermind.  2 is because there's prior state from earlier notebook cells (jupyter fail...), and 3 is because two strings next to each other are concatenated in python, so it's actually valid.  We can get these fixed.

**Comment by joelgrus** [comment]
the tutorials are going to be out of sync one way or another, so I think having them versioned is the right approach. let me think about the right way to do this

**Comment by schmmd** [comment]
My approach would be:

1.  Move [our release process](https://github.com/allenai/allennlp-internal/blob/master/RELEASE.md) to a TeamCity configuration so it's scripted.

2.  Trigger deploying tutorials on successful release.  Tutorial deployment can update the tutorials to explicitly mention the pip installation they work for (latest).

**Comment by matt-gardner** [comment]
Can we at least disable tutorial pushes now, and rollback the tutorials to the 0.2.3 release commit?  That way we'll have working tutorials while we figure out a better long term solution.

**Comment by schmmd** [comment]
That should be easy.

@joelgrus are you able to roll back the tutorials?

I will add deploying tutorials to our release process, and we can do it manually for now.

Peace.  Michael

**Comment by joelgrus** [comment]
should be easy
