### ISSUE TITLE
Is it ok to have all zero grads sometimes?

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#650]
Consider a case, where you have some RNN that embeds a sentence that consists of only one word. <br>
In the simplest case, it has two sets of parameters: input2hidden, and hidded2hidden. In our case we have only one timestep, so no grads are computed for hidden2hidden parameters, and thus the test below will fail, despite the behavior is intended.

https://github.com/allenai/allennlp/blob/4cda858012261c5fa5f668236abaeb4333d587ec/allennlp/common/testing/model_test_case.py#L119-L121

**Comment by matt-gardner** [comment]
There are a few options here, given in order of preference:

1. Make your test have another timestep.  Presumably when you're actually training your model, you'll have more timesteps?  Otherwise why do you have those parameters in the first place?
2. Move the gradient check out of the `ensure_model_can_train_save_and_load()` test, and make each model call that test individually.  Your test can just not call that method, because it's not checking anything useful for you.  It's a little annoying though, because it'll need more setup if it's not inside the existing method.
3. After doing 2, make the method configurable, so that only _some_ of the parameters are checked.  Then you can still have the check for `input2hidden` but not `hidden2hidden`.

If we think it'll be a not-too-uncommon occurrence that you will have models that only sometimes have gradients (e.g., multi-task training, GANs, other kinds of multi-stage setups), then we should at least do 2, so that the gradient issue doesn't cause the main test to fail.  Though, you can probably fix those failures in the multi-task setting by making sure that the dataset has all of the tasks...  In any event, my guess is that 1 will be enough for you right now, unless I'm misunderstanding your issue.

**Comment by schmmd** [comment]
Closing for now, feel free to re-open.
