### ISSUE TITLE
unlabeled test set cannot be included in training vocabulary 

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#654]
In the "Kaggle competition" use case, the test dataset has no labels. This means that if you try to specify `test_data_path` (e.g. in order to get the embeddings for that vocabulary), the trainer will crash with

```
allennlp.common.checks.ConfigurationError: 'You cannot construct a Dataset with non-homogeneous Instances.'
```

I was able to workaround this by having the `DatasetReader` generate fake labels, but that's not a good solution.

**Comment by matt-gardner** [comment]
I think the way to handle multi-task training is to have the model take all possible inputs, and just have some of them be `None` some of the time.  That's basically the same case that we have here, where some of the instances have the output field and some don't.  So, yeah, we'll have to fix this eventually anyway.

Probably the thing to do is to check that if there's something that's different, it's only due to a _missing_ key, and nothing else.  And then our batching code has to group instances such that each batch is homogeneous.

**Comment by schmmd** [comment]
This won't be an issue for vocabulary building once Joel merges his dataset change.
