### ISSUE TITLE
`AdaptiveIterator` cannot be instantiated from JSON config file because it requires a `Callable` param

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#693]
https://github.com/allenai/allennlp/blob/master/allennlp/data/iterators/adaptive_iterator.py#L54

I guess if you wanted to use it you'd have to write your own custom `train` command? That seems not optimal. (I don't know what a good solution is.)

**Comment by matt-gardner** [comment]
Yeah, the adaptive iterator hasn't ever actually worked in AllenNLP. It worked in DeepQA, but we never figured out how to make it fit the new way we structured the data code. And because we haven't figured out the right way to handle learning rate stuff, figuring out the right API for this hasn't been a priority.

I'm not sure if we should just get rid of the code, or move it to some experimental repo, or something, but it probably doesn't belong in the main repo right now.

**Comment by DeNeutoy** [comment]
The right way to have this would be to have some `registerable` functions for the `padding_memory_scaling` options which have some uniform structure. However, I agree that this isn't super high priority because the learning rate question is non-trivial (and probably actually a research project).

**Comment by schmmd** [comment]
We're not even sure the AdaptiveIterator is useful presently, so making this P3.

**Comment by DeNeutoy** [comment]
#1433
