### ISSUE TITLE
enable lazy datasets

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#737]
there's currently a `LazyDataset` abstraction, and then #725 will get rid of Datasets all together and basically just replace them with `Iterable[Instance]`. This results in a cleaner API, but is a breaking change.

**Comment by matt-gardner** [comment]
Do you think it's feasible to unify the iterators / get rid of the lazy iterator for the 0.4 release?  So that we don't have a breaking change in 0.4, and then shortly after have another breaking change related to the same API.

**Comment by jacklone** [comment]
Does it mean that I can generate the data on-the-fly instead of loading all the data into memory? I'm looking for a method to process huge dataset.

**Comment by matt-gardner** [comment]
Yes, this is now possible, with #725 and #743 being merged into master.  Please try it out and let us know if you run into any issues!

For a couple of examples of how to modify a `DatasetReader` that uses the old API to one that uses the new one, see these two PRs: https://github.com/allenai/allennlp/pull/751/files, https://github.com/allenai/allennlp-as-a-library-example/pull/1/files.  It looks like we forgot to pass in the `lazy` flag in the second PR, which is important if you want to actually load data on-the-fly, but the first one shows how to do that part correctly.

I'm closing this issue now, as it's been fixed by @joelgrus's PRs.
