### ISSUE TITLE
"error: unrecognized arguments" when running prediction tutorial

### ISSUE THREAD

**Issue by maoredman** [allenai/allennlp#885]
Hi, in response to #884 , I am trying to get this tutorial running: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md
But when I run the command provided in the tutorial:
```
python -m allennlp.run predict \
    tests/fixtures/model.tar.gz \
    tests/fixtures/s2_papers.jsonl \
    --include-package my_library \
    --predictor paper-classifier
```

I encounter this error:
`error: unrecognized arguments: --include-package my_library --predictor paper-classifier`

After looking at allennlp's `run.py` (https://github.com/allenai/allennlp/blob/master/allennlp/run.py)
I find it calls `python -m allennlp.run`, which I presume is still currently at the 0.3 version? Does that mean I need to wait until I can download v0.4 from pip, or is there a quick fix available?

**Comment by joelgrus** [comment]
for most of our tutorials you can browse them at the 0.3.0 tag to get the right version, but this is a new tutorial and doesn't have a 0.3.0 version. 

you have three options

(1) wait for 0.4 to come out on pip
(2) clone the latest from github and use that
(3) create a custom `run.py` like in https://github.com/allenai/allennlp/blob/v0.3.0/tutorials/getting_started/creating_a_model.md#putting-it-all-together (the new --include-packages flag makes it so you don't have to do that anymore in 0.4)

if you do the last one, you'll need to pass in `predictor_overrides` to `main()` which is just a dictionary { registered-name-of-model: registered-name-of-predictor }, so that `predict` knows which predictor to use for your model. (in 0.4 this is handled by the `--predictor-name` parameter)

**Comment by maoredman** [comment]
Thanks! After using `pip install git+https://github.com/allenai/allennlp`, the new flags are now included. Hope the 0.4 release goes well!

**Comment by schmmd** [comment]
@maoredman 0.4 is released FYI.

**Comment by maoredman** [comment]
Awesome! Thanks for the heads-up :)
