### ISSUE TITLE
Printing additional variables from model's forward( ) after it has already been trained?

### ISSUE THREAD

**Issue by maoredman** [allenai/allennlp#899]
Hi, I've been through the tutorial on making predictions with a trained model (https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md)

I'm wondering if there's a way of printing additional variables from `academic_paper_classifier.py`'s `forward()` function once a tar.gz model archive has already been generated from training? For example, if I have finished training, but now decide I want to additionally write the `encoded_abstract` variable to the output JSON generated by `python3 -m allennlp.run predict`. Is there a better way than retraining the model from scratch?

**Comment by DeNeutoy** [comment]
Hello! 

Pytorch uses dynamic graphs, so it's actually ok to modify your model so long as you don't add or remove any parameters or things that are stored in the weights dictionary which is serialised. So because this change just changes the output spec, you should just be able to modify the `academic_paper_classifier` to return the `encoded_abstract` in `forward` and then use predict as normal. Did that not work for some reason?

**Comment by maoredman** [comment]
Ah yes, everything works fine. Thanks Mark!
