### ISSUE TITLE
SRL dataset copies instances

### ISSUE THREAD

**Issue by dheerajrajagopal** [allenai/allennlp#949]
Hi, 

A newbie here. I was trying to run the SRL model from allennlp and after I read the data, I see that the instances are repeated twice, thrice or four times in random. Not sure if I am missing something. 

```
# coding: utf-8
from allennlp.data import Token, Instance
from allennlp.data.dataset import Batch
from allennlp.data.vocabulary import Vocabulary
from allennlp.data.fields import TextField, LabelField
from allennlp.data.dataset_readers import SrlReader
from allennlp.data.token_indexers import SingleIdTokenIndexer, TokenCharactersIndexer
from allennlp.models import semantic_role_labeler
from allennlp.common.util import ensure_list
from allennlp.data.iterators.bucket_iterator import BucketIterator, BasicIterator

DATASET_FOLDER = 'data/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/'

dataset_reader = SrlReader()
instances = dataset_reader.read(DATASET_FOLDER)
#instances = ensure_list(instances)
vocab = Vocabulary.from_instances(instances)
for instance in instances:
    instance.fields['tokens'].index(vocab)


for i in instances[0:100]:
    print (i.fields['tokens'].tokens)

```

Thank you so much for the help

**Comment by DeNeutoy** [comment]
Hi, no problem to ask questions - you are looking at the text tokens only. In SRL, the data is loaded into instances as (text, label) pairs, so for a given sentence, it will be repeated in the dataset per verb in the sentence, because for each verb, we want to predict its arguments as a BIO sequence. If you look at the labels too, there shouldn't be any duplicated elements.

**Comment by dheerajrajagopal** [comment]
Ah okay, thank you so much.
