### ISSUE TITLE
How to reuse all_datasets?

### ISSUE THREAD

**Issue by phiedulxp** [allenai/allennlp#958]
I try to pickle the all_datasets, but it doesn't work due to spacy tokenizer.
` 
File "D:\Anaconda3\lib\site-packages\allennlp\commands\train.py", line 149, in datasets_to_file
    pickle.dump(all_datasets,gzip.open(os.path.join(dataset_dir,'dataset.pickle.gz'),'wb'))
  File "stringsource", line 2, in spacy.tokens.token.Token.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
`

**Comment by matt-gardner** [comment]
Yeah, we've run into this before.  Does it work if you use `dill` instead of `pickle`?

**Comment by matt-gardner** [comment]
Yeah, we've talked about having some kind of multi-processing to have the data loading and training going in separate threads when you're loading data lazily.  It's a lot of work, and it's not very high priority for us right now.  If someone wants to contribute it, we'd appreciate it, but we're not likely to get to this any time soon.

I'm closing this for now.  Feel free to re-open it if you have more questions.

**Comment by valsworthen** [comment]
Sorry to reopen the issue but I am encountering the same problem.

I have tried with `dill` but it does not work. Also @phiedulxp mentioned that using a simple tokenizer works, but I don't know if that means using something as `string.split()` or `nltk.word_tokenize`.

More generally, is there now a solution to save and quickly load Instances, rather than having to call the Reader for every training which can be really long?

Thank you

**Comment by matt-gardner** [comment]
See https://github.com/allenai/allennlp/issues/2123.

**Comment by valsworthen** [comment]
I have also read the mentioned issue but I don't think that it solves the spaCy tokens problem. @joelgrus says that the `DatasetReader` should be modified to handle case where preprocessed data exists, but not how to save this data in the first place.

**Comment by matt-gardner** [comment]
It really depends on what exactly is taking a long time.  In general, we don't worry about this too much because during development we test our models using tiny test fixtures, so preprocessing time isn't an issue.  When we're ready to actually train on real data, preprocessing time is typically negligible compared to training time, so it doesn't really matter if it takes a while.  We've had a few cases where preprocessing time was actually pretty bad, even relative to training time, and there we wrote some preprocessing scripts.  See how the `DatasetReader` for one example handles it [here](https://github.com/allenai/allennlp/blob/a89aebaede1608fa584925f16e15155ebd05c220/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py#L162-L168), and the script to do the preprocessing [here](https://github.com/allenai/allennlp/blob/master/scripts/wikitables/preprocess_data.py).
