### ISSUE TITLE
SRL model breaks down for some sentences

### ISSUE THREAD

**Issue by lan2720** [allenai/allennlp#996]
Hi, I quite enjoy this project.
But I found some sentences could cause the breakdown when using SRL model.

The error shows like this:
```
    result = predictor.predict_json(batch_data[0], cuda_device)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/service/predictors/semantic_role_labeler.py", line 177, in predict_json
    outputs = self._model.forward_on_instances(instances, cuda_device)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/models/model.py", line 137, in forward_on_instances
    model_input = dataset.as_tensor_dict(cuda_device=cuda_device, for_training=False)
  File "/Users/Lan/.pyenv/versions/3.6.4/lib/python3.6/site-packages/allennlp/data/dataset.py", line 152, in as_tensor_dict
    field_classes = self.instances[0].fields
IndexError: list index out of range
```

Here is  some sample sentences to cause this error:
```
What 2015 NFL team one the AFC playoff?
Who if the commissioner of the NFL?
Universal Paid for The Secret Life of Pets and which other film trailer?
What pope as a native of Poland?
The mountain ranges tail off into what kind of geographical formation?
```

Is there anyone know how to fix it? Thank you.

**Comment by matt-gardner** [comment]
This is happening because the SRL model requires a verb as an additional input to the model.  We use spacy to predict POS tags for each word in the input, and spacy is not finding a verb in any of those sentences, so no `Instances` are getting created.  For some of those sentences, that's because there is no verb, and the sentence is ungrammatical.  For others, spacy just didn't recognize the verb as a verb (e.g., "tail off").

We need to make the predictor robust to cases where spacy finds no verb.  The simplest thing to do would be to return an empty dictionary here: https://github.com/allenai/allennlp/blob/0c532d50ac52bca48bf9906864daf6735d5d02de/allennlp/service/predictors/semantic_role_labeler.py#L117-L118

If you want to submit a PR for this, great, otherwise we'll get to it when we have time.

**Comment by lan2720** [comment]
@matt-gardner Thank you for the detailed explanation. As recommended, I tried to fix this issue but failed. It's more complicated than I thought.
Anyway, I could skip those cases first.
